-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'A-10 Thunderbolt II',
    'A-10 Thunderbolt II',
    'Fairchild Republic A-10 Thunderbolt II',
    'Fairchild Republic A-10 Thunderbolt II',
    'Avion d''appui aérien rapproché américain de 4e génération',
    'American 4th-generation close air support aircraft',
    '/assets/airplanes/a10-thunderbolt-2.jpg',
    'Le Fairchild Republic A-10 Thunderbolt II, surnommé "Warthog", est un avion d''appui aérien rapproché conçu pour l''US Air Force. Classé dans la 4e génération, il est spécialisé dans la destruction de blindés et de cibles au sol grâce à son canon GAU-8 Avenger et sa robustesse exceptionnelle. Utilisé dans de nombreux conflits modernes, il est célèbre pour sa durabilité et son efficacité au combat.',
    'The Fairchild Republic A-10 Thunderbolt II, nicknamed "Warthog", is a close air support aircraft designed for the US Air Force. Classified as 4th generation, it specializes in the destruction of armor and ground targets thanks to its GAU-8 Avenger cannon and exceptional ruggedness. Used in numerous modern conflicts, it is famous for its durability and combat effectiveness.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1970-01-01',
    '1972-05-10',
    '1977-03-10',
    706.0,
    4150.0,
    (SELECT id FROM manufacturer WHERE code = 'LM'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Appui aérien'),
    'Actif',
    'Active',
    12000.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM tech WHERE name = 'Canon GAU-8 Avenger')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM tech WHERE name = 'Blindage en titane')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM tech WHERE name = 'Moteurs à turbofan')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM armement WHERE name = 'GAU-8 Avenger')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM armement WHERE name = 'AGM-65 Maverick')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM armement WHERE name = 'Mk 82')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM armement WHERE name = 'Hydra 70')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM armement WHERE name = 'CBU-97'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM wars WHERE name = 'Guerre de Yougoslavie')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM wars WHERE name = 'Guerre d''Irak'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM missions WHERE name = 'Suppression des défenses aériennes ennemies')),
((SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II'), (SELECT id FROM missions WHERE name = 'Reconnaissance armée'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 16.26, wingspan = 17.53, height = 4.47, wing_area = 47.0,
  empty_weight = 11321, mtow = 23000, service_ceiling = 13700, climb_rate = 30.5,
  combat_radius = 463, crew = 1,
  engine_name = 'General Electric TF34-GE-100', engine_count = 2,
  engine_type = 'Turbofan', engine_type_en = 'Turbofan',
  thrust_dry = 40.32,
  production_start = 1972, production_end = 1984, units_built = 716,
  operators_count = 1,
  nickname = 'Warthog',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Fairchild_A-10_Thunderbolt_II',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Fairchild_Republic_A-10_Thunderbolt_II',
  variants    = E'- **A-10A** : version initiale\n- **A-10C** : modernisation avionique, suite de guerre électronique',
  variants_en = E'- **A-10A** : initial version\n- **A-10C** : avionics upgrade, electronic warfare suite'
WHERE name = 'A-10 Thunderbolt II';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 18800000, unit_cost_year = 1998
WHERE name = 'A-10 Thunderbolt II';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nDéveloppé dans les années 1970 en réponse à la menace des chars soviétiques massés en Europe, l''A-10 fut le premier avion de l''USAF conçu spécifiquement pour l''appui aérien rapproché. L''architecture entière tourne autour du canon **GAU-8/A Avenger de 30 mm**, l''arme la plus lourde jamais montée sur avion de combat.\n\n## Carrière opérationnelle\nRévélation de la guerre du Golfe en 1991, où il détruit plus de 900 chars irakiens en 100 heures. Engagé ensuite au Kosovo, en Afghanistan, en Irak et en Syrie. Le blindage en titane du cockpit (« baignoire ») et la redondance systémique lui valent une légendaire capacité de survie.\n\n## Héritage\nSymbole vivant du CAS moderne, l''A-10 a repoussé plusieurs tentatives de retrait grâce à la pression du Congrès et des troupes au sol. La version modernisée **A-10C** reste en service jusque vers 2028-2030, sans successeur direct prévu.',
  description_en = E'## Genesis\nDeveloped in the 1970s in response to massed Soviet tanks in Europe, the A-10 was the first USAF aircraft designed specifically for close air support. The entire airframe is built around its **30 mm GAU-8/A Avenger cannon**, the heaviest gun ever mounted on a combat aircraft.\n\n## Operational career\nDecisive in the 1991 Gulf War, where it destroyed more than 900 Iraqi tanks in 100 hours. Later deployed to Kosovo, Afghanistan, Iraq and Syria. Its titanium cockpit "bathtub" and systemic redundancy give it legendary survivability.\n\n## Legacy\nA living symbol of modern CAS, the A-10 has repeatedly survived retirement attempts thanks to Congress and ground troops. The **A-10C** upgrade keeps it in service until roughly 2028-2030, with no direct successor planned.'
WHERE name = 'A-10 Thunderbolt II';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=1hWtPOH4DVQ'
WHERE name = 'A-10 Thunderbolt II';
