-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'B-1 Lancer',
    'B-1 Lancer',
    'Rockwell B-1 Lancer',
    'Rockwell B-1 Lancer',
    'Bombardier stratégique américain de 4e génération',
    'American 4th-generation strategic bomber',
    '/assets/airplanes/b1-lancer.jpg',
    'Le Rockwell B-1 Lancer est un bombardier stratégique à géométrie variable développé pour l''US Air Force. Classé dans la 4e génération, il est conçu pour des missions de pénétration à basse altitude et à haute vitesse, capable de transporter une large gamme d''armes conventionnelles et nucléaires. Utilisé dans des conflits modernes, il excelle dans les frappes stratégiques de précision.',
    'The Rockwell B-1 Lancer is a variable-geometry strategic bomber developed for the US Air Force. Classified as 4th generation, it is designed for low-altitude high-speed penetration missions, capable of carrying a wide range of conventional and nuclear weapons. Used in modern conflicts, it excels in precision strategic strikes.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1970-01-01',
    '1974-12-23',
    '1986-10-01',
    1330.0,
    12000.0,
    (SELECT id FROM manufacturer WHERE code = 'BOE'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Bombardier'),
    'Actif',
    'Active',
    87000.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM tech WHERE name = 'Aile à géométrie variable')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM tech WHERE name = 'Matériaux composites')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM tech WHERE name = 'Moteurs à turbofan'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM armement WHERE name = 'B61')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM armement WHERE name = 'B83')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM armement WHERE name = 'GBU-31 JDAM')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM armement WHERE name = 'Mk 84')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM armement WHERE name = 'CBU-87'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM wars WHERE name = 'Guerre d''Irak')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM missions WHERE name = 'Dissuasion nucléaire')),
((SELECT id FROM airplanes WHERE name = 'B-1 Lancer'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 44.5, wingspan = 41.8, height = 10.4, wing_area = 181.2,
  empty_weight = 87090, mtow = 216634, service_ceiling = 18000, climb_rate = 87,
  combat_radius = 5543, crew = 4,
  engine_name = 'General Electric F101-GE-102', engine_count = 4,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 64.9, thrust_wet = 136.9,
  production_start = 1983, production_end = 1988, units_built = 104,
  operators_count = 1,
  nickname = 'Bone',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Rockwell_B-1_Lancer',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Rockwell_B-1_Lancer'
WHERE name = 'B-1 Lancer';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 283000000, unit_cost_year = 1998,
  manufacturer_page = 'https://www.boeing.com/defense/bomber/b-1b-lancer/'
WHERE name = 'B-1 Lancer';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nConçu dans les années 1970 comme bombardier stratégique supersonique à basse altitude, capable de pénétrer les défenses soviétiques en se cachant sous la couverture radar. Annulé par Carter en 1977, ressuscité par Reagan en 1981.\n\n## Carrière opérationnelle\nInitialement dédié à la mission nucléaire, reconverti au bombardement conventionnel après la guerre froide. Engagé au Kosovo (1999), en Irak (2003), en Afghanistan et en Libye. Capable d''emporter plus de 34 tonnes d''armement.\n\n## Héritage\nSeul bombardier supersonique à aile à géométrie variable encore en service américain. Doit rester opérationnel jusque vers 2036, date de remplacement par le **B-21 Raider** furtif.',
  description_en = E'## Genesis\nConceived in the 1970s as a low-altitude supersonic strategic bomber capable of penetrating Soviet defences below radar coverage. Cancelled by Carter in 1977, revived by Reagan in 1981.\n\n## Operational career\nInitially nuclear-dedicated, repurposed for conventional bombing after the Cold War. Engaged in Kosovo (1999), Iraq (2003), Afghanistan and Libya. Capable of carrying more than 34 tonnes of ordnance.\n\n## Legacy\nThe only supersonic variable-sweep-wing bomber still in US service. Planned to remain operational until around 2036, when it will be replaced by the stealth **B-21 Raider**.'
WHERE name = 'B-1 Lancer';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  manufacturer_page = 'https://www.boeing.com/defense/b-1b-lancer'
WHERE name = 'B-1 Lancer';

-- [auto:010] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  manufacturer_page = 'https://www.boeing.com/defense/fighters-and-bombers/b-1-lancer'
WHERE name = 'B-1 Lancer';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=FMtvkh2_8gg'
WHERE name = 'B-1 Lancer';
