-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'B-2 Spirit',
    'B-2 Spirit',
    'Northrop Grumman B-2 Spirit',
    'Northrop Grumman B-2 Spirit',
    'Bombardier furtif américain de 5e génération',
    'American 5th-generation stealth bomber',
    '/assets/airplanes/b2-spirit.jpg',
    'Le Northrop Grumman B-2 Spirit est un bombardier stratégique furtif développé pour l''US Air Force. Classé dans la 5e génération, il est conçu pour des missions de pénétration furtive à haute altitude, capable de transporter des armes nucléaires et conventionnelles. Surnommé l''avion furtif par excellence, il a été utilisé dans des conflits modernes pour des frappes stratégiques de précision.',
    'The Northrop Grumman B-2 Spirit is a stealth strategic bomber developed for the US Air Force. Classified as 5th generation, it is designed for high-altitude stealth penetration missions, capable of carrying nuclear and conventional weapons. Nicknamed the stealth aircraft par excellence, it has been used in modern conflicts for precision strategic strikes.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1979-01-01',
    '1989-07-17',
    '1997-04-01',
    1010.0,
    11100.0,
    (SELECT id FROM manufacturer WHERE code = 'LM'),
    (SELECT id FROM generation WHERE generation = 5),
    (SELECT id FROM type WHERE name = 'Bombardier'),
    'Actif',
    'Active',
    71600.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM tech WHERE name = 'Conception furtive')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM tech WHERE name = 'Système de gestion de mission avancé')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM tech WHERE name = 'Matériaux composites')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM tech WHERE name = 'Moteurs à turbofan')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM armement WHERE name = 'B61')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM armement WHERE name = 'B83')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM armement WHERE name = 'GBU-31 JDAM')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM armement WHERE name = 'Mk 84')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM armement WHERE name = 'GBU-39 SDB'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM wars WHERE name = 'Guerre de Yougoslavie')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM wars WHERE name = 'Guerre d''Irak'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM missions WHERE name = 'Dissuasion nucléaire')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'B-2 Spirit'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 21.0, wingspan = 52.4, height = 5.18, wing_area = 460.0,
  empty_weight = 71700, mtow = 170600, service_ceiling = 15200, climb_rate = NULL,
  combat_radius = 6000, crew = 2,
  engine_name = 'General Electric F118-GE-100', engine_count = 4,
  engine_type = 'Turbofan', engine_type_en = 'Turbofan',
  thrust_dry = 77.0,
  production_start = 1987, production_end = 2000, units_built = 21,
  operators_count = 1,
  stealth_level = 'tres_elevee',
  nickname = 'Spirit',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Northrop_B-2_Spirit',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Northrop_B-2_Spirit'
WHERE name = 'B-2 Spirit';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 737000000, unit_cost_year = 1997,
  manufacturer_page = 'https://www.northropgrumman.com/what-we-do/air/b-2-spirit/'
WHERE name = 'B-2 Spirit';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nProgramme top-secret lancé en 1981 dans le cadre du **Advanced Technology Bomber**. Le B-2 est le premier bombardier furtif opérationnel au monde, avec une aile volante exploitant des matériaux absorbants révolutionnaires.\n\n## Carrière opérationnelle\nPremier engagement au Kosovo (1999) avec des vols directs depuis le Missouri (30 heures aller-retour). Utilisé en Irak (2003), Libye (2011), Yémen et Afghanistan. Seul bombardier capable de délivrer la bombe anti-bunker **GBU-57 MOP** de 14 tonnes.\n\n## Héritage\nProgramme arrêté à 21 exemplaires (sur 132 prévus) pour un coût total dépassant **2 milliards $ par avion**, ce qui en fait l''avion le plus cher de l''histoire. Successeur direct : le **B-21 Raider**, première sortie publique en 2022.',
  description_en = E'## Genesis\nTop-secret programme launched in 1981 under the **Advanced Technology Bomber** banner. The B-2 is the first operational stealth bomber in the world, a flying wing using revolutionary radar-absorbent materials.\n\n## Operational career\nFirst combat use in Kosovo (1999) with direct round trips from Missouri (30-hour missions). Deployed in Iraq (2003), Libya (2011), Yemen and Afghanistan. Sole carrier of the 14-tonne **GBU-57 MOP** anti-bunker bomb.\n\n## Legacy\nProduction capped at 21 aircraft (from 132 planned) with a total cost exceeding **US $ 2 billion per aircraft**, making it the most expensive aircraft in history. Direct successor: the **B-21 Raider**, publicly unveiled in 2022.'
WHERE name = 'B-2 Spirit';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  manufacturer_page = 'https://www.northropgrumman.com/what-we-do/air/b-2-spirit'
WHERE name = 'B-2 Spirit';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=u7QYT5UoumQ'
WHERE name = 'B-2 Spirit';
