-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'B-52 Stratofortress',
    'B-52 Stratofortress',
    'Boeing B-52 Stratofortress',
    'Boeing B-52 Stratofortress',
    'Bombardier stratégique américain de 2e génération',
    'American 2nd-generation strategic bomber',
    '/assets/airplanes/b52-stratofortress.jpg',
    'Le Boeing B-52 Stratofortress est un bombardier stratégique à longue portée développé pour l''US Air Force. Classé dans la 2e génération, il est conçu pour des missions de frappe stratégique et nucléaire, avec une capacité exceptionnelle de charge utile et de portée. En service depuis les années 1950, il a été modernisé à plusieurs reprises et reste actif, participant à presque tous les conflits majeurs américains depuis la Guerre froide.',
    'The Boeing B-52 Stratofortress is a long-range strategic bomber developed for the US Air Force. Classified as 2nd generation, it is designed for strategic and nuclear strike missions, with exceptional payload capacity and range. In service since the 1950s, it has been modernized several times and remains active, participating in almost all major American conflicts since the Cold War.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1950-01-01',
    '1952-04-15',
    '1955-02-01',
    957.0,
    14800.0,
    (SELECT id FROM manufacturer WHERE code = 'BOE'),
    (SELECT id FROM generation WHERE generation = 2),
    (SELECT id FROM type WHERE name = 'Bombardier'),
    'Actif',
    'Active',
    83000.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM tech WHERE name = 'Moteurs à turbofan')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM tech WHERE name = 'Système de ravitaillement en vol automatique'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM armement WHERE name = 'B61')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM armement WHERE name = 'B83')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM armement WHERE name = 'GBU-31 JDAM')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM armement WHERE name = 'Mk 84')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM armement WHERE name = 'AGM-86 ALCM'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM wars WHERE name = 'Guerre de Corée')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM wars WHERE name = 'Guerre du Vietnam')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM wars WHERE name = 'Guerre froide')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM wars WHERE name = 'Guerre d''Irak'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM missions WHERE name = 'Dissuasion nucléaire')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'B-52 Stratofortress'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 48.5, wingspan = 56.4, height = 12.4, wing_area = 371.6,
  empty_weight = 83250, mtow = 220000, service_ceiling = 15200, climb_rate = 31.85,
  combat_radius = 7210, crew = 5,
  engine_name = 'Pratt & Whitney TF33-P-3/103', engine_count = 8,
  engine_type = 'Turbofan', engine_type_en = 'Turbofan',
  thrust_dry = 75.6,
  production_start = 1952, production_end = 1962, units_built = 744,
  operators_count = 1,
  nickname = 'BUFF',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Boeing_B-52_Stratofortress',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Boeing_B-52_Stratofortress',
  variants    = E'- **B-52D/F/G** : versions initiales et intermédiaires\n- **B-52H** : seule version encore en service (moteurs TF33)',
  variants_en = E'- **B-52D/F/G** : initial and interim versions\n- **B-52H** : only version still in service (TF33 engines)'
WHERE name = 'B-52 Stratofortress';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 84000000, unit_cost_year = 1962,
  manufacturer_page = 'https://www.boeing.com/defense/b-52-stratofortress/'
WHERE name = 'B-52 Stratofortress';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nConçu à la fin des années 1940 pour frapper l''URSS depuis les bases continentales américaines en emportant des bombes nucléaires thermonucléaires. Premier vol du prototype YB-52 en 1952.\n\n## Carrière opérationnelle\nPilier du **Strategic Air Command** durant toute la guerre froide. Engagé massivement au Vietnam (opérations **Arc Light** et **Linebacker II**), puis en Irak (1991, 2003), Afghanistan, Yougoslavie, Syrie. Reconverti à la frappe conventionnelle longue distance avec missiles de croisière.\n\n## Héritage\nPlus longue carrière opérationnelle de tous les bombardiers militaires (70 ans et plus). Doit rester en service **jusque vers 2050**, avec un remplacement progressif de ses moteurs et radars pour rejoindre l''ère B-52J.',
  description_en = E'## Genesis\nDesigned in the late 1940s to strike the USSR from continental US bases carrying thermonuclear bombs. Prototype YB-52 first flew in 1952.\n\n## Operational career\nPillar of **Strategic Air Command** throughout the Cold War. Heavily used in Vietnam (**Arc Light** and **Linebacker II** operations), then Iraq (1991, 2003), Afghanistan, Yugoslavia and Syria. Repurposed for long-range conventional strike with cruise missiles.\n\n## Legacy\nLongest operational career of any military bomber (70+ years). Scheduled to stay in service **until around 2050**, with progressive engine and radar upgrades as the B-52J standard.'
WHERE name = 'B-52 Stratofortress';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  manufacturer_page = 'https://www.boeing.com/defense/b-52-stratofortress'
WHERE name = 'B-52 Stratofortress';

-- [auto:010] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  manufacturer_page = 'https://www.boeing.com/defense/fighters-and-bombers/b-52'
WHERE name = 'B-52 Stratofortress';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=PRxIlDU8B64'
WHERE name = 'B-52 Stratofortress';
