-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Étendard IV',
    'Étendard IV',
    'Dassault Étendard IV',
    'Dassault Étendard IV',
    'Chasseur naval français de 2e génération',
    'French 2nd-generation naval fighter',
    '/assets/airplanes/etendard4.jpg',
    'Le Dassault Étendard IV est un avion de chasse embarqué développé par Dassault Aviation pour la Marine nationale française. Classé dans la 2e génération, il a été conçu pour des missions d''attaque au sol et de reconnaissance depuis des porte-avions. Premier avion naval français de série, il a servi de base au développement du Super Étendard.',
    'The Dassault Étendard IV is a carrier-based fighter developed by Dassault Aviation for the French Navy. Classified as 2nd generation, it was designed for ground attack and reconnaissance missions from aircraft carriers. The first French production naval aircraft, it served as the basis for the development of the Super Étendard.',
    (SELECT id FROM countries WHERE code = 'FRA'),
    '1954-01-01',
    '1958-05-21',
    '1962-07-01',
    1099.0,
    1700.0,
    (SELECT id FROM manufacturer WHERE code = 'DAS'),
    (SELECT id FROM generation WHERE generation = 2),
    (SELECT id FROM type WHERE name = 'Appui aérien'),
    'Retiré',
    NULL,
    6100.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Étendard IV'), (SELECT id FROM tech WHERE name = 'Système navalisé')),
((SELECT id FROM airplanes WHERE name = 'Étendard IV'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Étendard IV'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Étendard IV'), (SELECT id FROM armement WHERE name = 'DEFA 552')),
((SELECT id FROM airplanes WHERE name = 'Étendard IV'), (SELECT id FROM armement WHERE name = 'Bombe lisse 250 kg')),
((SELECT id FROM airplanes WHERE name = 'Étendard IV'), (SELECT id FROM armement WHERE name = 'SNEB 68 mm'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Étendard IV'), (SELECT id FROM wars WHERE name = 'Guerre d''Algérie'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Étendard IV'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Étendard IV'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'Étendard IV'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 14.4, wingspan = 9.6, height = 3.85, wing_area = 29.0,
  empty_weight = 5900, mtow = 10200, service_ceiling = 15500, climb_rate = 100,
  combat_radius = 700, crew = 1, g_limit_pos = 7.0,
  engine_name = 'SNECMA Atar 08B', engine_count = 1,
  engine_type = 'Turboréacteur', engine_type_en = 'Turbojet',
  thrust_dry = 43.2,
  production_start = 1961, production_end = 1965, units_built = 90,
  successor_id = (SELECT id FROM airplanes WHERE name = 'Super Étendard' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Dassault_%C3%89tendard_IV',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Dassault_%C3%89tendard_IV'
WHERE name = 'Étendard IV';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 2000000, unit_cost_year = 1962,
  operators_count = 1,
  manufacturer_page = 'https://www.dassault-aviation.com/fr/'
WHERE name = 'Étendard IV';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nDéveloppé dans les années 1950 par Dassault pour la **Marine nationale**, dans le cadre du besoin OTAN d''un chasseur léger. Le programme est remanié pour s''adapter aux porte-avions Clemenceau et Foch récemment lancés.\n\n## Carrière opérationnelle\nPremier avion de combat français à catapultage depuis porte-avions. Engagé lors de la **guerre du Golfe** (1991) pour l''appui aux frégates françaises. Versions IVM, IVP et IVPM.\n\n## Héritage\nRetiré en 1991, remplacé par le Super Étendard. Premier de la lignée française d''avions embarqués : Étendard IV → Super Étendard → Rafale M.',
  description_en = E'## Genesis\nDeveloped in the 1950s by Dassault for the **French Navy**, within the NATO light-fighter requirement. The programme was reshaped to match the newly launched Clemenceau and Foch carriers.\n\n## Operational career\nFirst French combat aircraft launched from a carrier catapult. Engaged in the **Gulf War** (1991) supporting French frigates. IVM, IVP and IVPM variants.\n\n## Legacy\nRetired in 1991, replaced by the Super Étendard. First of the French carrier-aircraft lineage: Étendard IV → Super Étendard → Rafale M.'
WHERE name = 'Étendard IV';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = 'https://www.dassault-aviation.com/fr/defense/' WHERE name = 'Étendard IV';
