-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'F-111 Aardvark',
    'F-111 Aardvark',
    'General Dynamics F-111 Aardvark',
    'General Dynamics F-111 Aardvark',
    'Bombardier tactique américain de 3e génération',
    'American 3rd-generation tactical bomber',
    '/assets/airplanes/f111-aardvark.jpg',
    'Le General Dynamics F-111 Aardvark est un bombardier tactique à géométrie variable développé pour l''US Air Force. Classé dans la 3e génération, il est conçu pour des missions de frappe stratégique et tactique à basse altitude, avec une capacité de pénétration avancée grâce à son radar de suivi de terrain. Utilisé principalement pendant la Guerre du Vietnam et la Guerre du Golfe, il est célèbre pour sa polyvalence et sa vitesse.',
    'The General Dynamics F-111 Aardvark is a variable-geometry tactical bomber developed for the US Air Force. Classified as 3rd generation, it is designed for strategic and tactical strike missions at low altitude, with advanced penetration capability thanks to its terrain-following radar. Used mainly during the Vietnam War and the Gulf War, it is famous for its versatility and speed.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1963-01-01',
    '1964-12-21',
    '1967-10-18',
    2655.0,
    6700.0,
    (SELECT id FROM manufacturer WHERE code = 'LM'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Bombardier'),
    'Retiré',
    NULL,
    20900.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM tech WHERE name = 'Aile à géométrie variable')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM tech WHERE name = 'Radar de suivi de terrain')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion' )),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM armement WHERE name = 'M61 Vulcan')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM armement WHERE name = 'AGM-69 SRAM')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM armement WHERE name = 'Mk 84')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM armement WHERE name = 'GBU-10 Paveway II')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM armement WHERE name = 'CBU-87'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM wars WHERE name = 'Guerre du Vietnam')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM missions WHERE name = 'Suppression des défenses aériennes ennemies')),
((SELECT id FROM airplanes WHERE name = 'F-111 Aardvark'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 22.4, wingspan = 19.55, height = 5.02, wing_area = 61.9,
  empty_weight = 14954, mtow = 45359, service_ceiling = 19300, climb_rate = 127,
  combat_radius = 2140, crew = 2, g_limit_pos = 7.5,
  engine_name = 'Pratt & Whitney TF30-P-100', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 64.5, thrust_wet = 112.1,
  production_start = 1964, production_end = 1976, units_built = 563,
  operators_count = 2,
  nickname = 'Aardvark',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/General_Dynamics_F-111_Aardvark',
  wikipedia_en = 'https://en.wikipedia.org/wiki/General_Dynamics_F-111_Aardvark'
WHERE name = 'F-111 Aardvark';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 30000000, unit_cost_year = 1973,
  variants    = E'- **F-111A** : USAF tactique (141 ex.)\n- **F-111B** : projet Navy avorté\n- **F-111C** : export Australie (24 ex.)\n- **F-111E/F** : versions évoluées USAF\n- **FB-111A** : bombardier stratégique SAC\n- **EF-111A Raven** : guerre électronique',
  variants_en = E'- **F-111A** : USAF tactical (141 built)\n- **F-111B** : cancelled Navy project\n- **F-111C** : Australian export (24 built)\n- **F-111E/F** : USAF upgrades\n- **FB-111A** : SAC strategic bomber\n- **EF-111A Raven** : electronic warfare'
WHERE name = 'F-111 Aardvark';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nPremier avion de combat à aile à géométrie variable en service, développé dans les années 1960 comme bombardier tactique capable de pénétration à basse altitude. Conçu à l''origine pour l''USAF et la Navy (F-111B abandonné).\n\n## Carrière opérationnelle\nEngagé au Vietnam (opérations **Combat Lancer**, **Linebacker II**), en Libye (opération **El Dorado Canyon**, 1986), dans la guerre du Golfe (1991). Redoutable par mauvais temps grâce à son radar **TFR** de suivi de terrain.\n\n## Héritage\nRetiré par l''USAF en 1998, par la RAAF australienne en 2010 — opérateur final. Sa technologie d''aile à géométrie variable et son système TFR ont inspiré le Tornado européen et le Su-24 soviétique.',
  description_en = E'## Genesis\nFirst operational variable-sweep-wing combat aircraft, developed in the 1960s as a tactical bomber capable of low-altitude penetration. Originally designed for both the USAF and the Navy (F-111B cancelled).\n\n## Operational career\nUsed in Vietnam (**Combat Lancer**, **Linebacker II** operations), Libya (Operation **El Dorado Canyon**, 1986), the Gulf War (1991). Feared in bad weather thanks to its **TFR** terrain-following radar.\n\n## Legacy\nRetired by the USAF in 1998, by Australia''s RAAF in 2010 — the final operator. Its variable-sweep-wing technology and TFR system inspired the European Tornado and the Soviet Su-24.'
WHERE name = 'F-111 Aardvark';
