-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'F-14 Tomcat',
    'F-14 Tomcat',
    'Grumman F-14 Tomcat',
    'Grumman F-14 Tomcat',
    'Chasseur embarqué américain de 4e génération',
    'American 4th-generation carrier-based fighter',
    '/assets/airplanes/f14-tomcat.jpg',
    'Le Grumman F-14 Tomcat est un avion de chasse embarqué développé pour l''US Navy, célèbre pour ses ailes à géométrie variable et sa capacité à intercepter à longue portée. Classé dans la 4e génération, il a été conçu pour la supériorité aérienne et la défense des flottes, avec des capacités secondaires air-sol. Utilisé principalement pendant la Guerre froide, il reste une icône de l''aviation navale.',
    'The Grumman F-14 Tomcat is a carrier-based fighter aircraft developed for the US Navy, famous for its variable-geometry wings and its ability to intercept at long range. Classified as 4th generation, it was designed for air superiority and fleet defense, with secondary air-to-ground capabilities. Used mainly during the Cold War, it remains an icon of naval aviation.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1968-01-01',
    '1970-12-21',
    '1974-09-22',
    2485.0,
    2965.0,
    (SELECT id FROM manufacturer WHERE code = 'LM'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Intercepteur'),
    'Retiré',
    NULL,
    19940.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM tech WHERE name = 'Aile à géométrie variable')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM tech WHERE name = 'Radar AN/AWG-9')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM tech WHERE name = 'Système de contrôle de vol numérique')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM tech WHERE name = 'Système navalisé')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM armement WHERE name = 'M61 Vulcan')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM armement WHERE name = 'AIM-9 Sidewinder')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM armement WHERE name = 'AIM-7 Sparrow')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM armement WHERE name = 'AIM-54 Phoenix')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM armement WHERE name = 'Mk 84'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'F-14 Tomcat'), (SELECT id FROM missions WHERE name = 'Escorte'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 19.13, wingspan = 19.55, height = 4.88, wing_area = 54.5,
  empty_weight = 19838, mtow = 33724, service_ceiling = 15200, climb_rate = 229,
  combat_radius = 926, crew = 2, g_limit_pos = 7.5,
  engine_name = 'Pratt & Whitney F110-GE-400', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 75.62, thrust_wet = 122.77,
  production_start = 1969, production_end = 1991, units_built = 712,
  operators_count = 2,
  nickname = 'Tomcat',
  rival_id = (SELECT id FROM airplanes WHERE name = 'MiG-31' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Grumman_F-14_Tomcat',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Grumman_F-14_Tomcat'
WHERE name = 'F-14 Tomcat';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 38000000, unit_cost_year = 1998,
  variants    = E'- **F-14A** : moteurs TF30, série initiale (557 ex.)\n- **F-14B** : remoteurisation F110-GE-400\n- **F-14D Super Tomcat** : radar APG-71, avionique glass cockpit',
  variants_en = E'- **F-14A** : TF30 engines, initial production (557 built)\n- **F-14B** : F110-GE-400 re-engining\n- **F-14D Super Tomcat** : APG-71 radar, glass cockpit'
WHERE name = 'F-14 Tomcat';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nDéveloppé dans les années 1960 pour la US Navy comme intercepteur à long rayon d''action, chargé de protéger les porte-avions contre les bombardiers soviétiques. Aile à géométrie variable, radar AWG-9 couplé au missile AIM-54 Phoenix.\n\n## Carrière opérationnelle\nEngagé dans le golfe de Sidra (1981, 1989) contre la Libye. Seul client export : l''**Iran impérial** (80 ex. livrés avant la révolution). Rôle iconique dans *Top Gun* (1986). Engagements également en Afghanistan et Irak comme bombardier (Bombcat).\n\n## Héritage\nRetiré par la US Navy en 2006 au profit du F/A-18E/F Super Hornet. Toujours en service en **Iran** (~40 exemplaires actifs), seul opérateur restant au monde.',
  description_en = E'## Genesis\nDeveloped in the 1960s for the US Navy as a long-range interceptor protecting carriers against Soviet bombers. Variable-sweep wing, AWG-9 radar paired with the AIM-54 Phoenix missile.\n\n## Operational career\nEngaged in the Gulf of Sidra (1981, 1989) against Libya. Sole export customer: **Imperial Iran** (80 delivered before the revolution). Iconic role in *Top Gun* (1986). Also used in Afghanistan and Iraq as a bomber (Bombcat).\n\n## Legacy\nRetired by the US Navy in 2006 in favour of the F/A-18E/F Super Hornet. Still in service in **Iran** (~40 active airframes), the only remaining operator in the world.'
WHERE name = 'F-14 Tomcat';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=HgFOvlW_aEo'
WHERE name = 'F-14 Tomcat';
