-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'F-15E Strike Eagle',
    'F-15E Strike Eagle',
    'McDonnell Douglas F-15E Strike Eagle',
    'McDonnell Douglas F-15E Strike Eagle',
    'Chasseur-bombardier multirôle américain de 4e génération',
    'American 4th-generation multirole fighter-bomber',
    '/assets/airplanes/f15-eagle.jpg',
    'Le McDonnell Douglas F-15E Strike Eagle est une variante multirôle du F-15 Eagle, optimisée pour les missions de frappe au sol tout en conservant des capacités de supériorité aérienne. Classé dans la 4e génération, il est équipé de systèmes avancés pour les frappes de précision à longue portée et a été largement utilisé dans des conflits modernes par l''US Air Force.',
    'The McDonnell Douglas F-15E Strike Eagle is a multirole variant of the F-15 Eagle, optimized for ground strike missions while retaining air superiority capabilities. Classified as 4th generation, it is equipped with advanced systems for long-range precision strikes and has been widely used in modern conflicts by the US Air Force.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1982-01-01',
    '1986-12-11',
    '1988-09-30',
    2655.0,
    3900.0,
    (SELECT id FROM manufacturer WHERE code = 'BOE'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Actif',
    'Active',
    14300.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM tech WHERE name = 'Aile en flèche')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM tech WHERE name = 'Radar AN/APG-63')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM tech WHERE name = 'Système de contrôle de vol numérique')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM tech WHERE name = 'Moteurs à poussée vectorielle')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM armement WHERE name = 'M61 Vulcan')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM armement WHERE name = 'AIM-9 Sidewinder')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM armement WHERE name = 'AIM-120 AMRAAM')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM armement WHERE name = 'AGM-65 Maverick')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM armement WHERE name = 'GBU-10 Paveway II'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM wars WHERE name = 'Guerre de Yougoslavie')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM wars WHERE name = 'Guerre d''Irak'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 19.43, wingspan = 13.05, height = 5.63, wing_area = 56.5,
  empty_weight = 14300, mtow = 36741, service_ceiling = 18200, climb_rate = 254,
  combat_radius = 1270, crew = 2, g_limit_pos = 9.0,
  engine_name = 'Pratt & Whitney F100-PW-229', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 79.18, thrust_wet = 129.45,
  production_start = 1985, production_end = NULL, units_built = 236,
  operators_count = 5,
  nickname = 'Strike Eagle',
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'F-4 Phantom II' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/McDonnell_Douglas_F-15E_Strike_Eagle',
  wikipedia_en = 'https://en.wikipedia.org/wiki/McDonnell_Douglas_F-15E_Strike_Eagle'
WHERE name = 'F-15E Strike Eagle';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 87700000, unit_cost_year = 2021,
  manufacturer_page = 'https://www.boeing.com/defense/f-15-eagle/',
  variants    = E'- **F-15E** : biplace attaque tous temps (USAF)\n- **F-15I Ra''am** : Israël\n- **F-15S/SA** : Arabie saoudite\n- **F-15K Slam Eagle** : Corée du Sud\n- **F-15SG** : Singapour\n- **F-15QA** : Qatar\n- **F-15EX Eagle II** : dernière version (2020), successor USAF',
  variants_en = E'- **F-15E** : two-seat all-weather strike (USAF)\n- **F-15I Ra''am** : Israel\n- **F-15S/SA** : Saudi Arabia\n- **F-15K Slam Eagle** : South Korea\n- **F-15SG** : Singapore\n- **F-15QA** : Qatar\n- **F-15EX Eagle II** : latest (2020), USAF successor'
WHERE name = 'F-15E Strike Eagle';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nVersion biplace multi-rôle du F-15 Eagle, conçue par McDonnell Douglas dans les années 1980 pour combiner supériorité aérienne et attaque tous temps. Le système de désignation laser **LANTIRN** lui permet de frapper avec précision de nuit.\n\n## Carrière opérationnelle\nEngagé durant la guerre du Golfe (1991), au Kosovo, en Afghanistan, en Irak, en Syrie. Zéro perte en combat aérien (capacité dual-role). Les dérivés export (Israël F-15I, Arabie saoudite F-15SA, Corée F-15K, Qatar F-15QA) dominent le segment haut de gamme.\n\n## Héritage\nBase du nouveau **F-15EX Eagle II** commandé par l''USAF en 2020 — preuve que la cellule reste pertinente 50 ans après le premier vol du F-15A. Rival direct du Su-27 Flanker.',
  description_en = E'## Genesis\nTwo-seat multi-role version of the F-15 Eagle, designed by McDonnell Douglas in the 1980s to combine air superiority and all-weather strike. The **LANTIRN** laser-designation system enables precision night strikes.\n\n## Operational career\nUsed during the Gulf War (1991), Kosovo, Afghanistan, Iraq, Syria. Zero losses in air combat (dual-role capability). Export derivatives (Israeli F-15I, Saudi F-15SA, Korean F-15K, Qatari F-15QA) dominate the high-end segment.\n\n## Legacy\nBasis for the new **F-15EX Eagle II** ordered by the USAF in 2020 — proof that the airframe remains relevant 50 years after the F-15A first flight. Direct rival of the Su-27 Flanker.'
WHERE name = 'F-15E Strike Eagle';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  manufacturer_page = 'https://www.boeing.com/defense/f-15ex'
WHERE name = 'F-15E Strike Eagle';

-- [auto:010] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  manufacturer_page = 'https://www.boeing.com/defense/fighters-and-bombers/f-15ex-eagle'
WHERE name = 'F-15E Strike Eagle';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=QTEv03ep3To'
WHERE name = 'F-15E Strike Eagle';
