-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'F-16 Fighting Falcon',
    'F-16 Fighting Falcon',
    'General Dynamics F-16 Fighting Falcon',
    'General Dynamics F-16 Fighting Falcon',
    'Chasseur multirôle américain de 4e génération',
    'American 4th-generation multirole fighter',
    '/assets/airplanes/f16-fighting-falcon.jpg',
    'Le General Dynamics F-16 Fighting Falcon est un avion de chasse multirôle emblématique de l''US Air Force. Classé dans la 4e génération, il est réputé pour sa maniabilité exceptionnelle grâce à son système fly-by-wire, son coût abordable et sa polyvalence dans les missions air-air et air-sol. Largement exporté, il a été utilisé dans de nombreux conflits à travers le monde.',
    'The General Dynamics F-16 Fighting Falcon is an iconic multirole fighter of the US Air Force. Classified as 4th generation, it is renowned for its exceptional maneuverability thanks to its fly-by-wire system, its affordable cost and its versatility in air-to-air and air-to-ground missions. Widely exported, it has been used in numerous conflicts around the world.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1972-01-01',
    '1974-02-02',
    '1979-08-17',
    2410.0,
    4220.0,
    (SELECT id FROM manufacturer WHERE code = 'LM'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Actif',
    'Active',
    8570.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM tech WHERE name = 'Aile en flèche')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM tech WHERE name = 'Commande de vol électrique (fly-by-wire)')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM tech WHERE name = 'Radar AN/APG-68')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM tech WHERE name = 'Siège incliné')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM armement WHERE name = 'M61 Vulcan')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM armement WHERE name = 'AIM-9 Sidewinder')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM armement WHERE name = 'AIM-120 AMRAAM')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM armement WHERE name = 'AGM-65 Maverick')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM armement WHERE name = 'GBU-12 Paveway II'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM wars WHERE name = 'Guerre de Yougoslavie')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM wars WHERE name = 'Guerre d''Irak'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 15.06, wingspan = 9.96, height = 4.88, wing_area = 27.87,
  empty_weight = 8570, mtow = 19187, service_ceiling = 15240, climb_rate = 254,
  combat_radius = 550, crew = 1, g_limit_pos = 9.0, g_limit_neg = -3.0,
  engine_name = 'Pratt & Whitney F100-PW-229 ou General Electric F110-GE-129', engine_count = 1,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 76.3, thrust_wet = 131.6,
  production_start = 1973, production_end = NULL, units_built = 4600,
  operators_count = 26,
  nickname = 'Viper',
  rival_id = (SELECT id FROM airplanes WHERE name = 'MiG-29' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/General_Dynamics_F-16_Fighting_Falcon',
  wikipedia_en = 'https://en.wikipedia.org/wiki/General_Dynamics_F-16_Fighting_Falcon',
  variants    = E'- **F-16A/B** : versions initiales, monoplace et biplace\n- **F-16C/D** : Block 25 à 52, radar AN/APG-68\n- **F-16V (Block 70/72)** : dernière version, radar AESA APG-83',
  variants_en = E'- **F-16A/B** : initial single- and two-seat versions\n- **F-16C/D** : Block 25–52, AN/APG-68 radar\n- **F-16V (Block 70/72)** : latest version, APG-83 AESA radar'
WHERE name = 'F-16 Fighting Falcon';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 30000000, unit_cost_year = 2020,
  manufacturer_page = 'https://www.lockheedmartin.com/en-us/products/f-16.html'
WHERE name = 'F-16 Fighting Falcon';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nIssu du programme **LWF** (Lightweight Fighter) des années 1970 de l''USAF, en opposition au F-15 plus lourd. Conçu autour de l''agilité et du coût réduit, premier chasseur à utiliser des commandes de vol électriques *relaxed stability*.\n\n## Carrière opérationnelle\nChasseur occidental le plus exporté depuis la Seconde Guerre mondiale : **26 pays** utilisateurs, **plus de 4 600 exemplaires** produits. Engagé dans pratiquement tous les conflits majeurs depuis 1981 : Liban, golfe Persique, Balkans, Afghanistan, Irak, Syrie.\n\n## Héritage\nDernière version **F-16V Block 70/72** (radar AESA APG-83) produite jusqu''au début des années 2030. Surnommé « Viper » par ses pilotes. Rival historique du MiG-29, opposé à lui en combat aérien lors des guerres yougoslaves.',
  description_en = E'## Genesis\nBorn from the USAF **LWF** (Lightweight Fighter) programme of the 1970s, positioned against the heavier F-15. Designed around agility and low cost, the first fighter to use *relaxed-stability* fly-by-wire controls.\n\n## Operational career\nThe most-exported Western fighter since World War II: **26 operator countries**, **more than 4,600 built**. Engaged in virtually every major conflict since 1981: Lebanon, Persian Gulf, Balkans, Afghanistan, Iraq, Syria.\n\n## Legacy\nLatest **F-16V Block 70/72** version (APG-83 AESA radar) in production through the early 2030s. Nicknamed "Viper" by its pilots. Historical rival of the MiG-29, opposed in air combat during the Yugoslav wars.'
WHERE name = 'F-16 Fighting Falcon';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=vmptTqsYPcw'
WHERE name = 'F-16 Fighting Falcon';
