INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'F-22 Raptor',
    'F-22 Raptor',
    'Lockheed Martin F-22 Raptor',
    'Lockheed Martin F-22 Raptor',
    'Chasseur furtif américain de 5e génération',
    'American 5th-generation stealth fighter',
    '/assets/airplanes/f22-raptor.jpg',
    'Le Lockheed Martin F-22 Raptor est un avion de chasse furtif de supériorité aérienne développé pour l''US Air Force. Premier avion opérationnel de 5e génération, il combine furtivité, supercroisière, agilité exceptionnelle et une intégration avancée de capteurs pour dominer les combats aériens. Utilisé principalement pour des missions de supériorité aérienne, il a aussi des capacités air-sol limitées.',
    'The Lockheed Martin F-22 Raptor is a stealth air-superiority fighter aircraft developed for the US Air Force. The first operational 5th-generation aircraft, it combines stealth, supercruise, exceptional agility and advanced sensor integration to dominate air combat. Used primarily for air superiority missions, it also has limited air-to-ground capabilities.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1985-01-01',
    '1997-09-07',
    '2005-12-15',
    3065.0,
    2960.0,
    (SELECT id FROM manufacturer WHERE code = 'LM'),
    (SELECT id FROM generation WHERE generation = 5),
    (SELECT id FROM type WHERE name = 'Chasseur'),
    'Actif',
    'Active',
    19700.0
);

INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM tech WHERE name = 'Conception furtive')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM tech WHERE name = 'Radar AN/APG-77')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM tech WHERE name = 'Système de contrôle de vol numérique')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM tech WHERE name = 'Système de fusion de capteurs')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM tech WHERE name = 'Moteurs à poussée vectorielle'));

INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM armement WHERE name = 'M61 Vulcan')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM armement WHERE name = 'AIM-9 Sidewinder')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM armement WHERE name = 'AIM-120 AMRAAM')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM armement WHERE name = 'GBU-32 JDAM')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM armement WHERE name = 'GBU-39 SDB'));

INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'F-22 Raptor'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 18.90, wingspan = 13.56, height = 5.08, wing_area = 78.0,
  empty_weight = 19700, mtow = 38000, service_ceiling = 19800, climb_rate = 254,
  combat_radius = 760, crew = 1, g_limit_pos = 9.0, g_limit_neg = -3.0,
  engine_name = 'Pratt & Whitney F119-PW-100', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 104.0, thrust_wet = 156.0,
  production_start = 1996, production_end = 2011, units_built = 195,
  operators_count = 1,
  stealth_level = 'tres_elevee',
  nickname = 'Raptor',
  rival_id = (SELECT id FROM airplanes WHERE name = 'Su-57' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Lockheed_Martin_F-22_Raptor',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Lockheed_Martin_F-22_Raptor'
WHERE name = 'F-22 Raptor';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 150000000, unit_cost_year = 2009,
  manufacturer_page = 'https://www.lockheedmartin.com/en-us/products/f-22.html',
  variants    = E'- **F-22A** : seule version produite (195 exemplaires)\n- **F-22B** : biplace d''entraînement — projet annulé en 1996\n- Modernisation **Block 20/30/35** : radar AESA, avionique, armement',
  variants_en = E'- **F-22A** : only produced version (195 built)\n- **F-22B** : two-seat trainer — cancelled 1996\n- **Block 20/30/35** upgrades : AESA radar, avionics, weapons'
WHERE name = 'F-22 Raptor';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nIssu du programme **ATF** (Advanced Tactical Fighter) lancé en 1981 pour concevoir le premier chasseur de 5e génération : furtivité, supercroisière (vol supersonique sans postcombustion), poussée vectorielle, radar AESA.\n\n## Carrière opérationnelle\nPremier chasseur furtif opérationnel au monde (2005). Utilisé en Syrie depuis 2014 pour la surveillance de l''espace aérien et la désignation de cibles, mais jamais engagé en combat aérien réel. Capable de « voir » sans être vu.\n\n## Héritage\nProgramme arrêté à **195 exemplaires** sous l''administration Obama (2009) alors que 750 étaient initialement prévus. Seul pour les États-Unis : exportation interdite par le Congrès. Rival du Su-57 et du J-20.',
  description_en = E'## Genesis\nProduct of the **ATF** (Advanced Tactical Fighter) programme launched in 1981 to design the first fifth-generation fighter: stealth, supercruise (supersonic flight without afterburner), thrust vectoring, AESA radar.\n\n## Operational career\nFirst operational stealth fighter in the world (2005). Used over Syria since 2014 for airspace surveillance and target designation, but never engaged in actual air combat. Capable of "seeing" without being seen.\n\n## Legacy\nProduction stopped at **195 aircraft** under the Obama administration (2009) from an initial target of 750. US-only: Congress banned exports. Rival of the Su-57 and J-20.'
WHERE name = 'F-22 Raptor';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=nflTkCwYPDs'
WHERE name = 'F-22 Raptor';
