-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'F-35 Lightning II',
    'F-35 Lightning II',
    'Lockheed Martin F-35 Lightning II',
    'Lockheed Martin F-35 Lightning II',
    'Avion multirôle furtif américain de 5e génération',
    'American 5th-generation stealth multirole aircraft',
    '/assets/airplanes/f35-lightning-2.jpg',
    'Le Lockheed Martin F-35 Lightning II est un avion de combat multirôle furtif conçu pour l''US Air Force, la Navy et le Marine Corps. Appartenant à la 5e génération, il excelle dans les missions air-air, air-sol et de reconnaissance grâce à sa furtivité, sa fusion de capteurs et ses capacités STOVL (décollage court et atterrissage vertical) dans certaines variantes. Utilisé par de nombreux pays alliés, il est un pilier des forces aériennes modernes.',
    'The Lockheed Martin F-35 Lightning II is a stealth multirole combat aircraft designed for the US Air Force, Navy and Marine Corps. Belonging to the 5th generation, it excels in air-to-air, air-to-ground and reconnaissance missions thanks to its stealth, sensor fusion and STOVL (short take-off and vertical landing) capabilities in certain variants. Used by many allied countries, it is a pillar of modern air forces.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1996-01-01',
    '2006-12-15',
    '2016-08-02',
    2000.0,
    2200.0,
    (SELECT id FROM manufacturer WHERE code = 'LM'),
    (SELECT id FROM generation WHERE generation = 5),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Actif',
    'Active',
    13200.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM tech WHERE name = 'Conception furtive')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM tech WHERE name = 'Radar AN/APG-81')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM tech WHERE name = 'Système de fusion de capteurs')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM tech WHERE name = 'Système de contrôle de vol numérique')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM tech WHERE name = 'Moteur à poussée vectorielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM armement WHERE name = 'M61 Vulcan')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM armement WHERE name = 'AIM-9 Sidewinder')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM armement WHERE name = 'AIM-120 AMRAAM')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM armement WHERE name = 'GBU-12 Paveway II')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM armement WHERE name = 'GBU-31 JDAM')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM armement WHERE name = 'GBU-39 SDB'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'F-35 Lightning II'), (SELECT id FROM missions WHERE name = 'Guerre électronique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 15.7, wingspan = 10.7, height = 4.38, wing_area = 42.7,
  empty_weight = 13290, mtow = 31800, service_ceiling = 15240, climb_rate = NULL,
  combat_radius = 1239, crew = 1, g_limit_pos = 9.0,
  engine_name = 'Pratt & Whitney F135-PW-100', engine_count = 1,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 128.1, thrust_wet = 191.3,
  production_start = 2006, production_end = NULL, units_built = 1000,
  operators_count = 19,
  stealth_level = 'elevee',
  nickname = 'Lightning II',
  rival_id = (SELECT id FROM airplanes WHERE name = 'Su-57' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Lockheed_Martin_F-35_Lightning_II',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Lockheed_Martin_F-35_Lightning_II',
  variants    = E'- **F-35A** : CTOL conventionnel (Air Force)\n- **F-35B** : STOVL décollage court / atterrissage vertical (USMC, UK)\n- **F-35C** : CATOBAR navalisé (US Navy)',
  variants_en = E'- **F-35A** : conventional CTOL (Air Force)\n- **F-35B** : STOVL (USMC, UK)\n- **F-35C** : carrier CATOBAR (US Navy)'
WHERE name = 'F-35 Lightning II';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 80000000, unit_cost_year = 2023,
  manufacturer_page = 'https://www.lockheedmartin.com/en-us/products/f-35.html'
WHERE name = 'F-35 Lightning II';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nProgramme **JSF** (Joint Strike Fighter) lancé en 1994 pour remplacer simultanément F-16, F/A-18, A-10, AV-8B et F-117 chez l''USAF, la Navy et les Marines. Développement record de 25 ans et 400 milliards de dollars.\n\n## Carrière opérationnelle\nPremier engagement en 2018 par Israël (F-35I Adir) contre des cibles en Syrie. Utilisé également par le Royaume-Uni, la Norvège, les Pays-Bas, le Japon, la Corée, l''Australie. Plus de **19 pays** opérateurs, ce qui en fait la plate-forme de chasse occidentale de référence du XXIe siècle.\n\n## Héritage\nProduction cible : **3 500+ exemplaires** d''ici 2045. Chasseur le plus ambitieux jamais produit en série, mais critiqué pour ses coûts de maintenance élevés. Rival du Su-57 russe et du J-20 chinois.',
  description_en = E'## Genesis\nThe **JSF** (Joint Strike Fighter) programme launched in 1994 to simultaneously replace the F-16, F/A-18, A-10, AV-8B and F-117 across the USAF, Navy and Marines. A record 25-year development costing 400 billion dollars.\n\n## Operational career\nFirst combat use in 2018 by Israel (F-35I Adir) against targets in Syria. Also used by the United Kingdom, Norway, Netherlands, Japan, South Korea, Australia. More than **19 operator countries**, making it the reference Western fighter of the 21st century.\n\n## Legacy\nTarget production: **3,500+ aircraft** by 2045. The most ambitious fighter ever mass-produced, though criticised for its high maintenance costs. Rival of Russia''s Su-57 and China''s J-20.'
WHERE name = 'F-35 Lightning II';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=W41nCCFZgyA'
WHERE name = 'F-35 Lightning II';
