-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'F-4 Phantom II',
    'F-4 Phantom II',
    'McDonnell Douglas F-4 Phantom II',
    'McDonnell Douglas F-4 Phantom II',
    'Chasseur-bombardier multirôle américain de 3e génération',
    'American 3rd-generation multirole fighter-bomber',
    '/assets/airplanes/f4-phantom-2.jpg',
    'Le McDonnell Douglas F-4 Phantom II est un avion de chasse-bombardier multirôle emblématique, développé pour l''US Navy et l''US Air Force. Classé dans la 3e génération, il est connu pour sa polyvalence, sa vitesse et sa robustesse, servant dans des rôles d''interception, de supériorité aérienne et d''attaque au sol. Largement exporté, il a été un pilier des forces aériennes occidentales pendant la Guerre froide et au-delà.',
    'The McDonnell Douglas F-4 Phantom II is an iconic multirole fighter-bomber aircraft developed for the US Navy and US Air Force. Classified as 3rd generation, it is known for its versatility, speed and ruggedness, serving in interception, air superiority and ground attack roles. Widely exported, it was a pillar of Western air forces during the Cold War and beyond.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1955-01-01',
    '1958-05-27',
    '1960-12-30',
    2370.0,
    2600.0,
    (SELECT id FROM manufacturer WHERE code = 'BOE'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Retiré',
    NULL,
    12700.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM tech WHERE name = 'Aile en flèche')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM tech WHERE name = 'Radar AN/APQ-120')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM armement WHERE name = 'M61 Vulcan')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM armement WHERE name = 'AIM-9 Sidewinder')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM armement WHERE name = 'AIM-7 Sparrow')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM armement WHERE name = 'AGM-65 Maverick')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM armement WHERE name = 'Mk 84'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM wars WHERE name = 'Guerre du Vietnam')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM wars WHERE name = 'Guerre du Kippour')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'F-4 Phantom II'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 19.2, wingspan = 11.77, height = 5.0, wing_area = 49.2,
  empty_weight = 13757, mtow = 28030, service_ceiling = 18300, climb_rate = 210,
  combat_radius = 680, crew = 2, g_limit_pos = 8.5,
  engine_name = 'General Electric J79-GE-17', engine_count = 2,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 52.9, thrust_wet = 79.6,
  production_start = 1958, production_end = 1981, units_built = 5195,
  operators_count = 11,
  nickname = 'Phantom',
  successor_id = (SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/McDonnell_Douglas_F-4_Phantom_II',
  wikipedia_en = 'https://en.wikipedia.org/wiki/McDonnell_Douglas_F-4_Phantom_II'
WHERE name = 'F-4 Phantom II';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 2400000, unit_cost_year = 1965,
  variants    = E'- **F-4B/J/N** : versions Navy / Marines\n- **F-4C/D** : Air Force\n- **F-4E** : version majoritaire (5 057 ex.), canon interne M61\n- **F-4G Wild Weasel** : suppression défenses ennemies\n- **RF-4C/E** : reconnaissance',
  variants_en = E'- **F-4B/J/N** : Navy / Marines versions\n- **F-4C/D** : Air Force\n- **F-4E** : most-produced variant (5 057 built), internal M61 gun\n- **F-4G Wild Weasel** : SEAD role\n- **RF-4C/E** : reconnaissance'
WHERE name = 'F-4 Phantom II';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nDéveloppé dans les années 1950 par McDonnell pour la Navy comme intercepteur embarqué. L''USAF adopte la cellule devant ses performances exceptionnelles, donnant naissance à une carrière quasi-universelle.\n\n## Carrière opérationnelle\nEngagé massivement au Vietnam (280 pertes au combat), puis au Moyen-Orient (guerre du Kippour, guerres israélo-arabes), en Irak, au Pakistan, en Corée. Une véritable encyclopédie de combats aériens modernes.\n\n## Héritage\nPlus de **5 195 exemplaires** produits — le chasseur occidental le plus construit depuis 1945. Dernier retrait de la Luftwaffe en 2013. Reste en service dans quelques armées comme cible-drone ou avion de reconnaissance.',
  description_en = E'## Genesis\nDeveloped in the 1950s by McDonnell as a Navy carrier interceptor. The USAF adopted the airframe after witnessing its exceptional performance, launching a near-universal career.\n\n## Operational career\nHeavily used in Vietnam (280 combat losses), then the Middle East (Yom Kippur War, Arab-Israeli conflicts), Iraq, Pakistan, Korea. Effectively a textbook of modern air combat.\n\n## Legacy\nMore than **5,195 built** — the most-produced Western fighter since 1945. Finally retired from the Luftwaffe in 2013. Still operated by a few air forces as drone-target or reconnaissance platforms.'
WHERE name = 'F-4 Phantom II';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=2bzjFDmLETc'
WHERE name = 'F-4 Phantom II';
