-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'F-5 Freedom Fighter',
    'F-5 Freedom Fighter',
    'Northrop F-5 Freedom Fighter',
    'Northrop F-5 Freedom Fighter',
    'Chasseur léger américain de 3e génération',
    'American 3rd-generation light fighter',
    '/assets/airplanes/f5-freedom-fighter.jpg',
    'Le Northrop F-5 Freedom Fighter est un avion de chasse léger développé par Northrop pour l''US Air Force et ses alliés. Classé dans la 3e génération, il est conçu pour être économique, maniable et facile à entretenir, avec des capacités de supériorité aérienne et d''attaque au sol. Largement exporté, il a été utilisé dans de nombreux conflits, notamment pendant la Guerre du Vietnam.',
    'The Northrop F-5 Freedom Fighter is a light fighter aircraft developed by Northrop for the US Air Force and its allies. Classified as 3rd generation, it is designed to be economical, maneuverable and easy to maintain, with air superiority and ground attack capabilities. Widely exported, it has been used in many conflicts, notably during the Vietnam War.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1955-01-01',
    '1959-07-30',
    '1964-03-01',
    1700.0,
    2870.0,
    (SELECT id FROM manufacturer WHERE code = 'LM'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Chasseur'),
    'Retiré',
    NULL,
    4240.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM tech WHERE name = 'Aile en flèche légère')),
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle')),
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM tech WHERE name = 'Canon M39'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM armement WHERE name = 'Canon M39')),
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM armement WHERE name = 'AIM-9 Sidewinder')),
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM armement WHERE name = 'Mk 82')),
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM armement WHERE name = 'Hydra 70'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM wars WHERE name = 'Guerre du Vietnam')),
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 14.38, wingspan = 8.13, height = 4.08, wing_area = 17.28,
  empty_weight = 4410, mtow = 11187, service_ceiling = 15800, climb_rate = 175,
  combat_radius = 1405, crew = 1, g_limit_pos = 7.33,
  engine_name = 'General Electric J85-GE-21B', engine_count = 2,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 15.57, thrust_wet = 22.2,
  production_start = 1962, production_end = 1987, units_built = 2246,
  operators_count = 30,
  nickname = 'Tiger II',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Northrop_F-5',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Northrop_F-5'
WHERE name = 'F-5 Freedom Fighter';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 2100000, unit_cost_year = 1975,
  variants    = E'- **F-5A/B** : Freedom Fighter initial\n- **F-5E/F Tiger II** : version modernisée, radar AN/APQ-159\n- **F-5G / F-20 Tigershark** : prototype avorté (un seul moteur F404)',
  variants_en = E'- **F-5A/B** : initial Freedom Fighter\n- **F-5E/F Tiger II** : modernised variant, AN/APQ-159 radar\n- **F-5G / F-20 Tigershark** : aborted single-F404 prototype'
WHERE name = 'F-5 Freedom Fighter';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nConçu dans les années 1950 pour offrir aux alliés des États-Unis un chasseur supersonique simple, léger et économique. Le F-5 est l''avion de l''« allié » par excellence durant la guerre froide.\n\n## Carrière opérationnelle\nExporté dans plus de 30 pays : Iran, Corée du Sud, Vietnam du Sud, Jordanie, Arabie saoudite, Brésil, Norvège. Souvent premier appareil supersonique des forces aériennes émergentes. Engagé au Vietnam et lors des conflits du Moyen-Orient.\n\n## Héritage\nEncore en service dans plusieurs pays (Brésil, Chili, Corée du Sud, Mexique, Suisse) grâce à sa simplicité et ses coûts de maintenance modestes. Base du projet **F-20 Tigershark** avorté.',
  description_en = E'## Genesis\nDesigned in the 1950s to give US allies a simple, light and affordable supersonic fighter. The F-5 is the quintessential Cold War "ally" aircraft.\n\n## Operational career\nExported to more than 30 countries: Iran, South Korea, South Vietnam, Jordan, Saudi Arabia, Brazil, Norway. Often the first supersonic aircraft of emerging air forces. Used in Vietnam and Middle East conflicts.\n\n## Legacy\nStill in service in several countries (Brazil, Chile, South Korea, Mexico, Switzerland) thanks to its simplicity and low maintenance costs. Basis for the aborted **F-20 Tigershark** project.'
WHERE name = 'F-5 Freedom Fighter';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=_OC8gae2H7g'
WHERE name = 'F-5 Freedom Fighter';
