-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'F-8E (FN) Crusader',
    'F-8E (FN) Crusader',
    'Vought F-8E (FN) Crusader',
    'Vought F-8E (FN) Crusader',
    'Chasseur naval français de 3e génération',
    'French 3rd-generation naval fighter',
    '/assets/airplanes/f8-crusader-fr.jpg',
    'Le Vought F-8E (FN) Crusader est une version modifiée du F-8 Crusader américain, adaptée pour la Marine nationale française (Aéronavale). Classé dans la 3e génération, il a été utilisé comme intercepteur embarqué sur les porte-avions Clemenceau et Foch. Avec ses ailes à incidence variable et sa capacité tous temps, il a servi pendant 35 ans avant d’être remplacé par le Rafale Marine.',
    'The Vought F-8E (FN) Crusader is a modified version of the American F-8 Crusader, adapted for the French Navy (Aéronavale). Classified as 3rd generation, it was used as a carrier-based interceptor on the Clemenceau and Foch aircraft carriers. With its variable-incidence wings and all-weather capability, it served for 35 years before being replaced by the Rafale Marine.',
    (SELECT id FROM countries WHERE code = 'FRA'),
    '1952-01-01',
    '1964-02-27',
    '1964-11-01',
    1915.0,
    1730.0,
    (SELECT id FROM manufacturer WHERE code = 'LM'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Intercepteur'),
    'Retiré',
    NULL,
    10990.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM tech WHERE name = 'Aile à incidence variable')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM tech WHERE name = 'Système navalisé')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM tech WHERE name = 'Système de caméra intégré')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM tech WHERE name = 'Radar AN/APQ-94'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM armement WHERE name = 'Colt Mk 12')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM armement WHERE name = 'Matra R530')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM armement WHERE name = 'Matra R550 Magic')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM armement WHERE name = 'Zuni 127 mm'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM wars WHERE name = 'Guerre du Liban')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM wars WHERE name = 'Guerre de Yougoslavie'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM missions WHERE name = 'Patrouille aérienne de combat')),
((SELECT id FROM airplanes WHERE name = 'F-8E (FN) Crusader'), (SELECT id FROM missions WHERE name = 'Escorte'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 16.6, wingspan = 10.7, height = 4.8, wing_area = 32.5,
  empty_weight = 9038, mtow = 15500, service_ceiling = 17700, climb_rate = 160,
  combat_radius = 660, crew = 1, g_limit_pos = 6.4,
  engine_name = 'Pratt & Whitney J57-P-20A', engine_count = 1,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 47.6, thrust_wet = 80.1,
  production_start = 1954, production_end = 1964, units_built = 1261,
  nickname = 'Crusader',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Vought_F-8_Crusader',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Vought_F-8_Crusader'
WHERE name = 'F-8E (FN) Crusader';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 1500000, unit_cost_year = 1960,
  operators_count = 1,
  variants    = E'- **F-8A/C/D/E** : versions US Navy\n- **F-8E (FN)** : version française pour la Marine nationale (35 exemplaires, porte-avions Clemenceau/Foch)\n- **RF-8A** : reconnaissance (impliqué dans la crise de Cuba)',
  variants_en = E'- **F-8A/C/D/E** : US Navy versions\n- **F-8E (FN)** : French Navy variant (35 built, Clemenceau/Foch carriers)\n- **RF-8A** : reconnaissance (Cuban Missile Crisis)'
WHERE name = 'F-8E (FN) Crusader';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nIntercepteur embarqué US Navy des années 1950, réputé pour sa vitesse (Mach 1.8) mais aussi pour sa difficulté de pilotage à basse vitesse lors des appontages. Dernier chasseur à usage du canon comme arme principale.\n\n## Carrière opérationnelle\nRôle majeur au Vietnam (surnom : « *MiG Master* » pour ses 19 victoires contre les MiG-17 et MiG-21). La **Marine nationale française** reçoit 42 F-8E (FN) en 1964-1965, opérant depuis les porte-avions Clemenceau et Foch pendant 35 ans.\n\n## Héritage\nRetraité par la US Navy en 1976, mais prolongé par la Marine française jusqu''en 1999. Dernier chasseur français à catapultage classique avant l''ère Rafale M.',
  description_en = E'## Genesis\n1950s US Navy carrier interceptor, famous for its speed (Mach 1.8) but also for its tricky low-speed handling during carrier landings. The last fighter to rely on the gun as its primary weapon.\n\n## Operational career\nMajor role in Vietnam (nicknamed "*MiG Master*" for its 19 victories against MiG-17s and MiG-21s). The **French Navy** received 42 F-8E (FN) in 1964-1965, operating from the Clemenceau and Foch carriers for 35 years.\n\n## Legacy\nRetired by the US Navy in 1976, but extended by the French Navy until 1999. The last French fighter using conventional catapult launch before the Rafale M era.'
WHERE name = 'F-8E (FN) Crusader';
