-- Insertion du nouveau constructeur
INSERT INTO manufacturer (name, country_id, code) VALUES
('Hawker Siddeley', (SELECT id FROM countries WHERE code = 'GBR'), 'HS');

-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Hawker Siddeley Harrier',
    'Hawker Siddeley Harrier',
    'Hawker Siddeley Harrier GR.1/GR.3',
    'Hawker Siddeley Harrier GR.1/GR.3',
    'Avion d''attaque VTOL britannique de 3e génération',
    'British 3rd-generation VTOL attack aircraft',
    '/assets/airplanes/hawker-siddeley-harrier.jpg',
    'Le Hawker Siddeley Harrier est le premier avion de combat à décollage et atterrissage verticaux (VTOL) opérationnel au monde. Développé à partir du prototype Hawker P.1127, il utilise un unique réacteur Rolls-Royce Pegasus à quatre tuyères orientables permettant de diriger la poussée du vol vertical au vol horizontal. Entré en service dans la RAF en 1969, le Harrier a révolutionné les opérations aériennes tactiques en permettant de se passer de pistes conventionnelles, opérant depuis des clairières, des routes ou des navires. Il s''est illustré de manière spectaculaire lors de la guerre des Malouines en 1982, où les Sea Harrier de la Royal Navy ont dominé l''aviation argentine. Exporté vers les États-Unis (AV-8A), l''Espagne et l''Inde, il a ouvert la voie au Harrier II et au F-35B. Le Harrier reste un jalon majeur de l''histoire de l''aviation militaire.',
    'The Hawker Siddeley Harrier is the world',
    (SELECT id FROM countries WHERE code = 'GBR'),
    '1957-01-01',
    '1967-08-31',
    '1969-04-01',
    1176.0,
    3300.0,
    (SELECT id FROM manufacturer WHERE code = 'HS'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Appui aérien'),
    'Retiré',
    NULL,
    5530.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM tech WHERE name = 'Aile en flèche')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM tech WHERE name = 'Moteur à poussée vectorielle')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM tech WHERE name = 'Système de navigation attaque à basse altitude')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM armement WHERE name = 'ADEN 30 mm')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM armement WHERE name = 'AIM-9 Sidewinder')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM armement WHERE name = 'SNEB 68 mm')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM armement WHERE name = 'BL755')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM armement WHERE name = 'Mk 82'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM wars WHERE name = 'Guerre des Malouines')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM wars WHERE name = 'Guerre froide'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM missions WHERE name = 'Reconnaissance armée')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier'), (SELECT id FROM missions WHERE name = 'Attaque antinavire'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 14.27, wingspan = 7.70, height = 3.45, wing_area = 18.68,
  empty_weight = 6340, mtow = 14060, service_ceiling = 15000, climb_rate = 75,
  combat_radius = 370, crew = 1, g_limit_pos = 8.0,
  engine_name = 'Rolls-Royce Pegasus 103', engine_count = 1,
  engine_type = 'Turbofan à tuyères vectorielles', engine_type_en = 'Vectored-thrust turbofan',
  thrust_dry = 95.6,
  production_start = 1967, production_end = 1997, units_built = 278,
  operators_count = 4,
  successor_id = (SELECT id FROM airplanes WHERE name = 'F-35B Lightning II Anglais' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Hawker_Siddeley_Harrier',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Hawker_Siddeley_Harrier'
WHERE name = 'Hawker Siddeley Harrier';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 7000000, unit_cost_year = 1980,
  variants    = E'- **Harrier GR.1/GR.3** : RAF\n- **AV-8A/C** : US Marine Corps\n- **Harrier T.2/T.4** : biplaces d''entraînement\n- **AV-8S Matador** : export Espagne',
  variants_en = E'- **Harrier GR.1/GR.3** : RAF\n- **AV-8A/C** : US Marine Corps\n- **Harrier T.2/T.4** : two-seat trainers\n- **AV-8S Matador** : Spanish export'
WHERE name = 'Hawker Siddeley Harrier';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nPremier avion à décollage et atterrissage verticaux (**VTOL**) produit en série, développé dans les années 1960 par Hawker Siddeley. Utilise un **moteur à tuyères vectorielles Pegasus** de Rolls-Royce — innovation révolutionnaire.\n\n## Carrière opérationnelle\nEngagé par la RAF en Allemagne (bases avancées décentralisées, immunité aux frappes soviétiques). Utilisé par l''USMC (AV-8A/B). Démontrée sa pertinence lors de la guerre des Malouines (1982) avec 20 victoires sans perte en combat.\n\n## Héritage\nRetiré par la RAF en 2010. Successeur direct : le **F-35B** STOVL. Concept révolutionnaire qui a inspiré le Yak-38 soviétique.',
  description_en = E'## Genesis\nFirst mass-produced **VTOL** (Vertical Take-Off and Landing) aircraft, developed in the 1960s by Hawker Siddeley. Uses a Rolls-Royce **vectored-thrust Pegasus engine** — a revolutionary innovation.\n\n## Operational career\nUsed by the RAF in Germany (decentralised forward bases, immune to Soviet strikes). Also by the USMC (AV-8A/B). Proven in the Falklands War (1982) with 20 air-to-air victories and no combat losses.\n\n## Legacy\nRetired by the RAF in 2010. Direct successor: the **F-35B** STOVL. A revolutionary concept that inspired the Soviet Yak-38.'
WHERE name = 'Hawker Siddeley Harrier';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=5Lw8eWE7aQ8'
WHERE name = 'Hawker Siddeley Harrier';
