-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Chengdu J-10',
    'Chengdu J-10',
    'Chengdu J-10 Vigorous Dragon',
    'Chengdu J-10 Vigorous Dragon',
    'Chasseur multirôle chinois de 4e génération',
    'Chinese 4th-generation multirole fighter',
    '/assets/airplanes/j10.jpg',
    'Le Chengdu J-10 Vigorous Dragon est un chasseur multirôle développé par Chengdu Aerospace Corporation pour l''Armée populaire de libération. Classé dans la 4e génération, il est conçu pour la supériorité aérienne et les missions air-sol, avec une configuration delta-canard et un système fly-by-wire. Introduit dans les années 2000, il est un pilier moderne de l''aviation chinoise et a été exporté sous des variantes comme le J-10C.',
    'The Chengdu J-10 Vigorous Dragon is a multirole fighter developed by Chengdu Aerospace Corporation for the People',
    (SELECT id FROM countries WHERE code = 'CHN'),
    '1994-01-01',
    '1998-03-23',
    '2004-07-01',
    2200.0,
    1850.0,
    (SELECT id FROM manufacturer WHERE code = 'CAC'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Actif',
    'Active',
    9750.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM tech WHERE name = 'Aile canard delta')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM tech WHERE name = 'Commande de vol électrique (fly-by-wire)')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM tech WHERE name = 'Réacteur AL-31FN')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM tech WHERE name = 'Radar KLJ-7'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM armement WHERE name = 'GSh-23')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM armement WHERE name = 'PL-8')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM armement WHERE name = 'PL-12')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM armement WHERE name = 'Kh-31P')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM armement WHERE name = 'FAB-500'));

-- Insertion des guerres
-- Le J-10 n'a pas été engagé dans des conflits majeurs à ce jour, donc pas d'entrée dans airplane_wars

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-10'), (SELECT id FROM missions WHERE name = 'Patrouille aérienne de combat'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 15.49, wingspan = 9.75, height = 5.43, wing_area = 33.0,
  empty_weight = 9750, mtow = 19277, service_ceiling = 18000, climb_rate = 300,
  combat_radius = 1240, crew = 1, g_limit_pos = 9.0,
  engine_name = 'Saturn AL-31FN ou WS-10B', engine_count = 1,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 79.0, thrust_wet = 130.0,
  production_start = 1998, production_end = NULL, units_built = 600,
  operators_count = 2,
  rival_id = (SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Chengdu_J-10',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Chengdu_J-10'
WHERE name = 'Chengdu J-10';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 41000000, unit_cost_year = 2022,
  variants    = E'- **J-10A** : version initiale\n- **J-10B** : radar PESA, prise d''air DSI\n- **J-10C** : radar AESA, PL-15\n- **J-10CE** : export Pakistan (2022)',
  variants_en = E'- **J-10A** : initial version\n- **J-10B** : PESA radar, DSI inlet\n- **J-10C** : AESA radar, PL-15\n- **J-10CE** : Pakistani export (2022)'
WHERE name = 'Chengdu J-10';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nPremier chasseur de **4e génération** entièrement conçu en Chine. Développement lancé dans les années 1980 avec assistance israélienne et russe, premier vol en 1998. Canards couplés, commandes de vol électriques, radar AESA sur les dernières versions.\n\n## Carrière opérationnelle\nChasseur principal de la PLA Air Force moderne. Plusieurs variantes : J-10A (initial), J-10B (PESA), J-10C (AESA, PL-15). Exporté au **Pakistan** sous le nom J-10CE depuis 2022 (20 livrés).\n\n## Héritage\nPlus de **600 exemplaires** produits. Équivalent fonctionnel chinois du F-16 américain. Prouve la capacité de l''industrie chinoise à concevoir un chasseur moderne autonome.',
  description_en = E'## Genesis\nFirst **4th-generation** fighter fully designed in China. Development launched in the 1980s with Israeli and Russian assistance, first flew in 1998. Close-coupled canards, fly-by-wire controls, AESA radar on the latest versions.\n\n## Operational career\nMain fighter of the modern PLA Air Force. Several variants: J-10A (initial), J-10B (PESA), J-10C (AESA, PL-15). Exported to **Pakistan** as J-10CE since 2022 (20 delivered).\n\n## Legacy\nMore than **600 built**. Chinese functional equivalent of the US F-16. Proves the Chinese industry''s capability to design a modern fighter independently.'
WHERE name = 'Chengdu J-10';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=Sv9JLFE7Acs'
WHERE name = 'Chengdu J-10';
