-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Shenyang J-11',
    'Shenyang J-11',
    'Shenyang J-11 Flanker',
    'Shenyang J-11 Flanker',
    'Chasseur de supériorité aérienne chinois de 4e génération',
    'Chinese 4th-generation air superiority fighter',
    '/assets/airplanes/j11.jpg',
    'Le Shenyang J-11 est un chasseur de supériorité aérienne produit par Shenyang Aircraft Corporation, dérivé du Sukhoi Su-27 russe sous licence. Le programme a débuté dans les années 1990 avec l''assemblage sous licence de Su-27SK, avant d''évoluer vers le J-11B, une version entièrement sinisée intégrant des systèmes avioniques chinois, un radar AESA national et des réacteurs WS-10. Plus lourd et mieux armé que le J-10, le J-11 constitue l''épine dorsale de la chasse lourde de l''Armée populaire de libération et reste en production active avec des variantes modernisées.',
    'The Shenyang J-11 is an air superiority fighter produced by Shenyang Aircraft Corporation, derived from the Russian Sukhoi Su-27 under license. The program began in the 1990s with the licensed assembly of Su-27SK, before evolving into the J-11B, a fully sinicized version integrating Chinese avionics systems, a national AESA radar and WS-10 engines. Heavier and better armed than the J-10, the J-11 forms the backbone of the People',
    (SELECT id FROM countries WHERE code = 'CHN'),
    '1995-01-01',
    '1998-12-16',
    '2000-06-01',
    2500.0,
    3530.0,
    (SELECT id FROM manufacturer WHERE code = 'SAC'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Chasseur'),
    'Actif',
    'Active',
    16380.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM tech WHERE name = 'Aile à forte flèche')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM tech WHERE name = 'Commande de vol électrique (fly-by-wire)')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM tech WHERE name = 'Réacteur WS-10')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM tech WHERE name = 'Radar AESA')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM tech WHERE name = 'Système de fusion de capteurs'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM armement WHERE name = 'GSh-30-1')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM armement WHERE name = 'PL-8')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM armement WHERE name = 'PL-12')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM armement WHERE name = 'R-73')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM armement WHERE name = 'R-77')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM armement WHERE name = 'FAB-500'));

-- Insertion des guerres
-- Le J-11 n'a pas été engagé dans des conflits majeurs à ce jour, donc pas d'entrée dans airplane_wars

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM missions WHERE name = 'Patrouille aérienne de combat')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-11'), (SELECT id FROM missions WHERE name = 'Escorte'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 21.9, wingspan = 14.7, height = 5.9, wing_area = 62.0,
  empty_weight = 17700, mtow = 33000, service_ceiling = 19000, climb_rate = 300,
  combat_radius = 1500, crew = 1,
  engine_name = 'Saturn AL-31F ou WS-10A', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 74.5, thrust_wet = 122.6,
  production_start = 1998, production_end = NULL, units_built = 450,
  operators_count = 1,
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Shenyang_J-11',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Shenyang_J-11'
WHERE name = 'Shenyang J-11';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 30000000, unit_cost_year = 2010,
  variants    = E'- **J-11A** : copie sous licence Su-27SK\n- **J-11B** : version chinoise avec WS-10, avionique locale\n- **J-11BS** : biplace',
  variants_en = E'- **J-11A** : licence-built Su-27SK\n- **J-11B** : Chinese variant with WS-10 engine and local avionics\n- **J-11BS** : two-seater'
WHERE name = 'Shenyang J-11';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nCopie chinoise sous licence du **Su-27 soviétique**, produite à partir de 1998 comme J-11A, puis développée en version entièrement chinoise **J-11B** avec moteur WS-10 et avionique locale. Litige russe sur la propriété intellectuelle.\n\n## Carrière opérationnelle\nPilier de l''aviation de chasse chinoise, assignation prioritaire aux unités de défense aérienne du pays. Plusieurs centaines d''exemplaires en service. Biplace J-11BS pour entraînement avancé.\n\n## Héritage\nBase de la famille **J-15** (navalisé) et **J-16** (multi-rôle biplace). Symbole de la capacité chinoise à **reverser l''ingénierie soviétique** pour construire une flotte moderne indépendante.',
  description_en = E'## Genesis\nChinese licence-built copy of the Soviet **Su-27**, produced from 1998 as J-11A, then developed into a fully Chinese **J-11B** with WS-10 engine and local avionics. Russian intellectual-property dispute.\n\n## Operational career\nBackbone of the Chinese fighter fleet, priority assignment to the country''s air-defence units. Several hundred in service. Two-seat J-11BS for advanced training.\n\n## Legacy\nBasis of the **J-15** (carrier-borne) and **J-16** (two-seat multi-role) families. Symbol of China''s ability to **reverse-engineer Soviet designs** into an independent modern fleet.'
WHERE name = 'Shenyang J-11';
