-- Insertion des nouveaux armements spécifiques au J-20
INSERT INTO armement (name, description) VALUES
('PL-10', 'Missile air-air courte portée, guidage infrarouge à imagerie, 20 km'),
('PL-15', 'Missile air-air longue portée, guidage radar actif, 200+ km');

-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Chengdu J-20',
    'Chengdu J-20',
    'Chengdu J-20 Mighty Dragon',
    'Chengdu J-20 Mighty Dragon',
    'Chasseur furtif chinois de 5e génération',
    'Chinese 5th-generation stealth fighter',
    '/assets/airplanes/j20.jpg',
    'Le Chengdu J-20 Mighty Dragon est le premier avion de combat furtif de 5e génération développé par la Chine. Conçu par Chengdu Aerospace Corporation, il a effectué son premier vol en 2011 et est entré en service actif en 2017. Le J-20 combine une conception furtive avancée, une configuration delta-canard, des capacités de supercroisière et une fusion de capteurs sophistiquée. Destiné à la supériorité aérienne et à l''interception à longue portée, il est conçu pour rivaliser avec les chasseurs de 5e génération occidentaux comme le F-22 Raptor et le F-35 Lightning II. Équipé de missiles à très longue portée, il représente un bond technologique majeur pour l''aviation militaire chinoise.',
    'The Chengdu J-20 Mighty Dragon is the first 5th-generation stealth combat aircraft developed by China. Designed by Chengdu Aerospace Corporation, it made its first flight in 2011 and entered active service in 2017. The J-20 combines advanced stealth design, a delta-canard configuration, supercruise capabilities and sophisticated sensor fusion. Intended for air superiority and long-range interception, it is designed to compete with Western 5th-generation fighters such as the F-22 Raptor and the F-35 Lightning II. Equipped with very long-range missiles, it represents a major technological leap for Chinese military aviation.',
    (SELECT id FROM countries WHERE code = 'CHN'),
    '1997-01-01',
    '2011-01-11',
    '2017-03-09',
    2100.0,
    2000.0,
    (SELECT id FROM manufacturer WHERE code = 'CAC'),
    (SELECT id FROM generation WHERE generation = 5),
    (SELECT id FROM type WHERE name = 'Chasseur'),
    'Actif',
    'Active',
    19390.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM tech WHERE name = 'Conception furtive')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM tech WHERE name = 'Aile delta-canard')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM tech WHERE name = 'Commande de vol électrique (fly-by-wire)')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM tech WHERE name = 'Réacteur WS-10')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM tech WHERE name = 'Radar AESA')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM tech WHERE name = 'Système de fusion de capteurs'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM armement WHERE name = 'GSh-23')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM armement WHERE name = 'PL-10')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM armement WHERE name = 'PL-12')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM armement WHERE name = 'PL-15')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM armement WHERE name = 'LS-6'));

-- Insertion des guerres
-- Le J-20 n'a pas été engagé dans des conflits majeurs à ce jour, donc pas d'entrée dans airplane_wars

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-20'), (SELECT id FROM missions WHERE name = 'Patrouille aérienne de combat'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 21.2, wingspan = 13.01, height = 4.45, wing_area = 78.0,
  empty_weight = 17000, mtow = 37000, service_ceiling = 20000, climb_rate = 300,
  combat_radius = 2000, crew = 1,
  engine_name = 'WS-10C', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 81.0, thrust_wet = 147.0,
  production_start = 2011, production_end = NULL, units_built = 250,
  operators_count = 1,
  stealth_level = 'elevee',
  rival_id = (SELECT id FROM airplanes WHERE name = 'F-22 Raptor' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Chengdu_J-20',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Chengdu_J-20'
WHERE name = 'Chengdu J-20';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 110000000, unit_cost_year = 2017,
  variants    = E'- **J-20A** : version de série initiale (moteurs AL-31FN russes)\n- **J-20B** : version modernisée (moteur WS-10C)\n- **J-20S** : biplace (2022+)',
  variants_en = E'- **J-20A** : initial production (Russian AL-31FN engines)\n- **J-20B** : upgraded variant (WS-10C engine)\n- **J-20S** : two-seat version (2022+)'
WHERE name = 'Chengdu J-20';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nPremier chasseur de **5e génération** chinois, développé secrètement dans les années 2000 par le **Chengdu Aircraft Institute**. Premier vol public en 2011, mise en service opérationnelle en 2017. Canards couplés, furtivité frontale élevée.\n\n## Carrière opérationnelle\nDéployé prioritairement face à Taïwan et en mer de Chine méridionale. Versions successives : J-20A (moteurs russes AL-31FN), J-20B (WS-10C chinois), J-20S (biplace). Seul chasseur furtif opérationnel asiatique avec le F-35.\n\n## Héritage\nPlus de **250 exemplaires** estimés en 2024. Symbole de la montée en puissance militaire chinoise. Rival du F-22 Raptor américain et du Su-57 russe. Prochain pas : un dérivé 6e génération sans équipage.',
  description_en = E'## Genesis\nFirst Chinese **5th-generation** fighter, developed secretly in the 2000s by the **Chengdu Aircraft Institute**. First public flight in 2011, operational service in 2017. Close-coupled canards, high frontal stealth.\n\n## Operational career\nDeployed primarily against Taiwan and in the South China Sea. Successive variants: J-20A (Russian AL-31FN engines), J-20B (Chinese WS-10C), J-20S (two-seat). The only operational Asian stealth fighter alongside the F-35.\n\n## Legacy\nMore than **250 estimated** by 2024. Symbol of China''s military rise. Rival of the US F-22 Raptor and the Russian Su-57. Next step: a 6th-generation unmanned derivative.'
WHERE name = 'Chengdu J-20';
