-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Shenyang J-5',
    'Shenyang J-5',
    'Shenyang J-5 Fresco',
    'Shenyang J-5 Fresco',
    'Chasseur chinois de 2e génération',
    'Chinese 2nd-generation fighter',
    '/assets/airplanes/j5.jpg',
    'Le Shenyang J-5 Fresco est une copie chinoise sous licence du MiG-17 soviétique, développée par Shenyang Aircraft Corporation pour l''Armée populaire de libération. Classé dans la 2e génération, il est conçu comme un chasseur-intercepteur subsonique avec des capacités air-air et air-sol limitées. Utilisé principalement pendant la Guerre froide, il a été exporté à plusieurs pays alliés de la Chine.',
    'The Shenyang J-5 Fresco is a Chinese licensed copy of the Soviet MiG-17, developed by Shenyang Aircraft Corporation for the People',
    (SELECT id FROM countries WHERE code = 'CHN'),
    '1954-01-01',
    '1956-07-19',
    '1956-09-01',
    1145.0,
    1420.0,
    (SELECT id FROM manufacturer WHERE code = 'SAC'),
    (SELECT id FROM generation WHERE generation = 2),
    (SELECT id FROM type WHERE name = 'Chasseur'),
    'Retiré',
    NULL,
    3930.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-5'), (SELECT id FROM tech WHERE name = 'Aile en flèche')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-5'), (SELECT id FROM tech WHERE name = 'Réacteur Klimov VK-1')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-5'), (SELECT id FROM tech WHERE name = 'Système de navigation semi-automatique'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-5'), (SELECT id FROM armement WHERE name = 'Canon NR-23')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-5'), (SELECT id FROM armement WHERE name = 'FAB-250'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-5'), (SELECT id FROM wars WHERE name = 'Guerre de Corée')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-5'), (SELECT id FROM wars WHERE name = 'Guerre du Vietnam'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-5'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-5'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-5'), (SELECT id FROM missions WHERE name = 'Frappe tactique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 11.36, wingspan = 10.08, height = 3.8, wing_area = 22.6,
  empty_weight = 3939, mtow = 6055, service_ceiling = 14700, climb_rate = 35,
  combat_radius = 560, crew = 1,
  engine_name = 'WP-5D', engine_count = 1,
  engine_type = 'Turboréacteur', engine_type_en = 'Turbojet',
  thrust_dry = 26.48,
  production_start = 1956, production_end = 1959, units_built = 767,
  successor_id = (SELECT id FROM airplanes WHERE name = 'Shenyang J-6' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Shenyang_J-5',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Shenyang_J-5'
WHERE name = 'Shenyang J-5';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 200000, unit_cost_year = 1958,
  operators_count = 15
WHERE name = 'Shenyang J-5';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nCopie chinoise sous licence du **MiG-17F soviétique** produite à partir de 1956. Premier chasseur à réaction produit en Chine, base de l''industrie aéronautique militaire chinoise.\n\n## Carrière opérationnelle\nEngagé dans les affrontements **Chine-Taïwan** des années 1950-60 (crise du détroit de Formose). Exporté en Corée du Nord, Vietnam, Albanie, Égypte, Pakistan. Premiers combats aériens de l''aviation chinoise.\n\n## Héritage\nRetiré depuis les années 1990. Pierre fondatrice de l''industrie aéronautique militaire chinoise, qui aboutira 70 ans plus tard au J-20 furtif.',
  description_en = E'## Genesis\nChinese licence-built copy of the Soviet **MiG-17F**, produced from 1956. First jet fighter produced in China, foundation stone of the Chinese military aviation industry.\n\n## Operational career\nUsed in the **China-Taiwan** clashes of the 1950s-60s (Taiwan Strait crises). Exported to North Korea, Vietnam, Albania, Egypt, Pakistan. First air combats of Chinese aviation.\n\n## Legacy\nRetired since the 1990s. Foundation stone of the Chinese military aviation industry, which would lead 70 years later to the stealth J-20.'
WHERE name = 'Shenyang J-5';
