-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Shenyang J-6',
    'Shenyang J-6',
    'Shenyang J-6 Farmer',
    'Shenyang J-6 Farmer',
    'Chasseur chinois de 2e génération',
    'Chinese 2nd-generation fighter',
    '/assets/airplanes/j6.jpg',
    'Le Shenyang J-6 Farmer est une copie chinoise sous licence du MiG-19 soviétique, développée par Shenyang Aircraft Corporation pour l''Armée populaire de libération. Classé dans la 2e génération, il est le premier chasseur supersonique chinois, conçu pour la supériorité aérienne et des missions d''interception. Utilisé pendant la Guerre froide, il a été largement exporté à des pays alliés comme le Pakistan et la Corée du Nord.',
    'The Shenyang J-6 Farmer is a Chinese licensed copy of the Soviet MiG-19, developed by Shenyang Aircraft Corporation for the People',
    (SELECT id FROM countries WHERE code = 'CHN'),
    '1956-01-01',
    '1958-09-30',
    '1960-01-01',
    1450.0,
    1390.0,
    (SELECT id FROM manufacturer WHERE code = 'SAC'),
    (SELECT id FROM generation WHERE generation = 2),
    (SELECT id FROM type WHERE name = 'Chasseur'),
    'Retiré',
    NULL,
    5770.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM tech WHERE name = 'Aile en flèche')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM tech WHERE name = 'Réacteur WP-6')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM tech WHERE name = 'Système de navigation semi-automatique'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM armement WHERE name = 'NR-30')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM armement WHERE name = 'FAB-250')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM armement WHERE name = 'S-5'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM wars WHERE name = 'Guerre du Vietnam')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM wars WHERE name = 'Guerre Indo-Pakistanaise de 1971'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-6'), (SELECT id FROM missions WHERE name = 'Frappe tactique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 14.9, wingspan = 9.04, height = 3.88, wing_area = 25.0,
  empty_weight = 5760, mtow = 10000, service_ceiling = 17900, climb_rate = 180,
  combat_radius = 700, crew = 1,
  engine_name = 'WP-6', engine_count = 2,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 25.5, thrust_wet = 31.87,
  production_start = 1958, production_end = 1981, units_built = 3000,
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'Shenyang J-5' LIMIT 1),
  successor_id = (SELECT id FROM airplanes WHERE name = 'Chengdu J-7' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Shenyang_J-6',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Shenyang_J-6'
WHERE name = 'Shenyang J-6';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 500000, unit_cost_year = 1965,
  operators_count = 10
WHERE name = 'Shenyang J-6';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nCopie chinoise du **MiG-19 soviétique** produite à partir de 1958. Premier chasseur supersonique de la Chine. Production massive : plus de 3 000 exemplaires.\n\n## Carrière opérationnelle\nChasseur principal de la **PLA Air Force** et **PLA Navy Aviation** pendant 30 ans. Engagé dans les crises avec Taïwan, au Vietnam (livré à Hanoï). Utilisé comme bombardier d''attaque au sol en fin de carrière.\n\n## Héritage\nRetiré de Chine en 2010 — dernier chasseur supersonique de 1re génération en service au monde à ce moment-là. Toujours en service en Corée du Nord. Base technologique du Q-5 d''attaque.',
  description_en = E'## Genesis\nChinese copy of the Soviet **MiG-19**, produced from 1958. China''s first supersonic fighter. Mass production: more than 3,000 built.\n\n## Operational career\nMain fighter of the **PLA Air Force** and **PLA Navy Aviation** for 30 years. Used in Taiwan crises, Vietnam (delivered to Hanoi). Used as ground-attack bomber at the end of its career.\n\n## Legacy\nRetired from China in 2010 — the last 1st-generation supersonic fighter in service worldwide at that time. Still operated by North Korea. Technological base for the Q-5 attack aircraft.'
WHERE name = 'Shenyang J-6';
