-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Chengdu J-7',
    'Chengdu J-7',
    'Chengdu J-7 Fishcan',
    'Chengdu J-7 Fishcan',
    'Chasseur chinois de 3e génération',
    'Chinese 3rd-generation fighter',
    '/assets/airplanes/j7.jpg',
    'Le Chengdu J-7 Fishcan est une version chinoise sous licence et améliorée du MiG-21 soviétique, développée par Chengdu Aerospace Corporation pour l''Armée populaire de libération. Classé dans la 3e génération, ce chasseur supersonique est conçu pour la supériorité aérienne et l''interception, avec des capacités air-sol limitées. Largement exporté, il a été utilisé dans plusieurs conflits pendant et après la Guerre froide.',
    'The Chengdu J-7 Fishcan is a Chinese licensed and improved version of the Soviet MiG-21, developed by Chengdu Aerospace Corporation for the People',
    (SELECT id FROM countries WHERE code = 'CHN'),
    '1961-01-01',
    '1966-01-17',
    '1967-04-01',
    2230.0,
    1700.0,
    (SELECT id FROM manufacturer WHERE code = 'CAC'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Chasseur'),
    'Retiré',
    NULL,
    5843.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM tech WHERE name = 'Aile delta')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM tech WHERE name = 'Réacteur WP-7')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM tech WHERE name = 'Radar Type 226'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM armement WHERE name = 'NR-30')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM armement WHERE name = 'PL-2')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM armement WHERE name = 'FAB-250'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM wars WHERE name = 'Guerre du Vietnam')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Chengdu J-7'), (SELECT id FROM missions WHERE name = 'Frappe tactique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 13.95, wingspan = 7.15, height = 4.10, wing_area = 23.0,
  empty_weight = 5292, mtow = 8655, service_ceiling = 17500, climb_rate = 195,
  combat_radius = 850, crew = 1,
  engine_name = 'WP-13F', engine_count = 1,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 44.1, thrust_wet = 64.7,
  production_start = 1966, production_end = 2013, units_built = 2400,
  operators_count = 18,
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'Shenyang J-6' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Chengdu_J-7',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Chengdu_J-7'
WHERE name = 'Chengdu J-7';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 2500000, unit_cost_year = 1985,
  variants    = E'- **J-7I/II** : versions initiales\n- **J-7E/G** : aile delta double, modernisation avionique\n- **J-7MG** : version export F-7MG\n- **J-7PG** : version Pakistan',
  variants_en = E'- **J-7I/II** : initial versions\n- **J-7E/G** : double-delta wing, avionics upgrade\n- **J-7MG** : F-7MG export version\n- **J-7PG** : Pakistani variant'
WHERE name = 'Chengdu J-7';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nCopie chinoise du **MiG-21 soviétique**, produite à partir de 1966. Évolution locale très poussée avec versions E (double delta) et G/MG (avionique occidentale). Plus produite que l''original russe en Chine.\n\n## Carrière opérationnelle\nExporté massivement dans **18 pays** : Pakistan (conflits avec l''Inde), Bangladesh, Sri Lanka, Myanmar, Zimbabwe, Nigeria, Soudan. Plus de 2 400 exemplaires construits. Version JF-17 dérivée avec le Pakistan.\n\n## Héritage\nDernier J-7 chinois retiré en 2023. Toujours en service dans plusieurs pays pauvres ou sous embargo. Base du JF-17 Thunder, chasseur de 4e génération pakistano-chinois actuel.',
  description_en = E'## Genesis\nChinese copy of the Soviet **MiG-21**, produced from 1966. Deep local evolution with E (double-delta) and G/MG (Western avionics) variants. More produced in China than the Russian original.\n\n## Operational career\nMassively exported to **18 countries**: Pakistan (conflicts with India), Bangladesh, Sri Lanka, Myanmar, Zimbabwe, Nigeria, Sudan. More than 2,400 built. Derivative JF-17 variant with Pakistan.\n\n## Legacy\nLast Chinese J-7 retired in 2023. Still in service in several poor or embargoed countries. Base of the JF-17 Thunder, the current Pakistani-Chinese 4th-generation fighter.'
WHERE name = 'Chengdu J-7';
