-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Shenyang J-8',
    'Shenyang J-8',
    'Shenyang J-8 Finback',
    'Shenyang J-8 Finback',
    'Intercepteur chinois de 3e génération',
    'Chinese 3rd-generation interceptor',
    '/assets/airplanes/j8.jpg',
    'Le Shenyang J-8 Finback est un chasseur-intercepteur développé par Shenyang Aircraft Corporation pour l''Armée populaire de libération. Classé dans la 3e génération, il est conçu pour des missions d''interception à haute altitude et grande vitesse, évoluant à partir des bases du MiG-21 avec des améliorations chinoises. Utilisé pendant la Guerre froide, il a été modernisé dans des variantes comme le J-8II pour inclure des capacités multirôles.',
    'The Shenyang J-8 Finback is a fighter-interceptor developed by Shenyang Aircraft Corporation for the People',
    (SELECT id FROM countries WHERE code = 'CHN'),
    '1964-01-01',
    '1969-07-05',
    '1980-03-01',
    2350.0,
    2200.0,
    (SELECT id FROM manufacturer WHERE code = 'SAC'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Intercepteur'),
    'Retiré',
    NULL,
    9820.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-8'), (SELECT id FROM tech WHERE name = 'Aile delta')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-8'), (SELECT id FROM tech WHERE name = 'Réacteur WP-7')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-8'), (SELECT id FROM tech WHERE name = 'Radar Type 242'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-8'), (SELECT id FROM armement WHERE name = 'NR-30')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-8'), (SELECT id FROM armement WHERE name = 'PL-2')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-8'), (SELECT id FROM armement WHERE name = 'PL-5'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-8'), (SELECT id FROM wars WHERE name = 'Guerre froide'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Shenyang J-8'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-8'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Shenyang J-8'), (SELECT id FROM missions WHERE name = 'Frappe tactique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 21.59, wingspan = 9.34, height = 5.41, wing_area = 42.2,
  empty_weight = 9820, mtow = 18879, service_ceiling = 20200, climb_rate = 224,
  combat_radius = 800, crew = 1,
  engine_name = 'WP-13B II', engine_count = 2,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 44.1, thrust_wet = 66.7,
  production_start = 1985, production_end = 2010, units_built = 300,
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Shenyang_J-8',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Shenyang_J-8'
WHERE name = 'Shenyang J-8';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 10000000, unit_cost_year = 1990,
  operators_count = 1
WHERE name = 'Shenyang J-8';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nPremier avion de combat entièrement conçu en **Chine** (et non plus une copie soviétique). Intercepteur lourd développé à partir des années 1960, mais dont la mise au point traîne jusqu''aux années 1980. Nez supersonique à cône central.\n\n## Carrière opérationnelle\nRôle d''intercepteur de la PLA Air Force, surveillance des côtes chinoises. Plusieurs versions successives : J-8A, J-8B, J-8D (ravitaillement en vol), J-8F (radar moderne).\n\n## Héritage\nRetiré progressivement face au J-10, J-11 et J-16. Premier pas crucial de l''industrie chinoise vers l''indépendance technologique aéronautique.',
  description_en = E'## Genesis\nFirst combat aircraft fully designed in **China** (no longer a Soviet copy). Heavy interceptor developed from the 1960s but whose development dragged on until the 1980s. Supersonic nose with central cone.\n\n## Operational career\nInterceptor role for the PLA Air Force, surveillance of Chinese coasts. Several successive variants: J-8A, J-8B, J-8D (in-flight refuelling), J-8F (modern radar).\n\n## Legacy\nGradually retired in favour of the J-10, J-11 and J-16. A crucial first step of the Chinese industry towards aeronautical technological independence.'
WHERE name = 'Shenyang J-8';
