-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Jaguar',
    'Jaguar',
    'SEPECAT Jaguar',
    'SEPECAT Jaguar',
    'Chasseur-bombardier franco-britannique de 3e génération',
    'Franco-British 3rd-generation fighter-bomber',
    '/assets/airplanes/jaguar.jpg',
    'Le SEPECAT Jaguar est un avion de chasse-bombardier développé conjointement par la France et le Royaume-Uni (SEPECAT). Classé dans la 3e génération, il a été conçu pour des missions d''attaque au sol à basse altitude et d''appui aérien rapproché, avec des capacités secondaires de supériorité aérienne. Utilisé par l''Armée de l''Air française et la Royal Air Force, il a servi dans plusieurs conflits avant d’être retiré.',
    'The SEPECAT Jaguar is a fighter-bomber aircraft jointly developed by France and the United Kingdom (SEPECAT). Classified as 3rd generation, it was designed for low-altitude ground attack and close air support missions, with secondary air superiority capabilities. Used by the French Air Force and the Royal Air Force, it served in several conflicts before being retired.',
    (SELECT id FROM countries WHERE code = 'FRA'),
    '1965-01-01',
    '1968-09-08',
    '1973-06-01',
    1700.0,
    3524.0,
    (SELECT id FROM manufacturer WHERE code = 'DAS'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Appui aérien'),
    'Retiré',
    NULL,
    7700.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM tech WHERE name = 'Aile en flèche')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM tech WHERE name = 'Système de navigation attaque à basse altitude')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM tech WHERE name = 'Pod désignateur laser')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM armement WHERE name = 'ADEN 30 mm')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM armement WHERE name = 'Matra R550 Magic')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM armement WHERE name = 'AS-30L')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM armement WHERE name = 'BL755')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM armement WHERE name = 'Bombe lisse 1000 kg'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM wars WHERE name = 'Guerre de Yougoslavie'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'Jaguar'), (SELECT id FROM missions WHERE name = 'Suppression des défenses aériennes ennemies'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 16.83, wingspan = 8.69, height = 4.89, wing_area = 24.18,
  empty_weight = 7000, mtow = 15700, service_ceiling = 14000, climb_rate = 200,
  combat_radius = 908, crew = 1, g_limit_pos = 8.6,
  engine_name = 'Rolls-Royce / Turbomeca Adour Mk.102/106', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 22.7, thrust_wet = 32.5,
  production_start = 1968, production_end = 1981, units_built = 543,
  operators_count = 8,
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/SEPECAT_Jaguar',
  wikipedia_en = 'https://en.wikipedia.org/wiki/SEPECAT_Jaguar'
WHERE name = 'Jaguar';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 8000000, unit_cost_year = 1983,
  manufacturer_page = 'https://www.dassault-aviation.com/fr/',
  variants    = E'- **Jaguar GR1/GR3** : RAF (attaque tactique + reconnaissance)\n- **Jaguar A/E** : Armée de l''air française (monoplace / biplace)\n- **Jaguar International** : export (Inde, Oman, Équateur, Nigeria)',
  variants_en = E'- **Jaguar GR1/GR3** : RAF (tactical strike + recce)\n- **Jaguar A/E** : French Air Force (single- / two-seat)\n- **Jaguar International** : export (India, Oman, Ecuador, Nigeria)'
WHERE name = 'Jaguar';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nDéveloppé dans les années 1960 par le consortium franco-britannique **SEPECAT**, le Jaguar répond à un besoin commun d''entraînement et d''attaque tactique. Reconverti dès sa conception en avion d''attaque à part entière.\n\n## Carrière opérationnelle\nEngagé durant la guerre du Golfe (1991), où il démontre une précision remarquable en frappes laser. Utilisé ensuite au Tchad, au Kosovo, en Irak (No-Fly Zone). Vendu à l''Inde, Oman, Équateur, Nigeria.\n\n## Héritage\nRetiré de l''Armée de l''air française en 2005. Toujours en service en Inde (modernisation DARIN III jusqu''en 2027+), seul opérateur actif. Base du programme qui inspirera le Mirage F1.',
  description_en = E'## Genesis\nDeveloped in the 1960s by the Franco-British **SEPECAT** consortium, the Jaguar answered a common need for training and tactical strike. Reworked from the outset into a full-fledged attack aircraft.\n\n## Operational career\nEngaged during the Gulf War (1991), where it showcased remarkable precision in laser strikes. Later used in Chad, Kosovo, Iraq (No-Fly Zone). Exported to India, Oman, Ecuador, Nigeria.\n\n## Legacy\nRetired by the French Air Force in 2005. Still in service in India (DARIN III upgrade through 2027+), the only active operator. Basis for the programme that inspired the Mirage F1.'
WHERE name = 'Jaguar';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = 'https://www.dassault-aviation.com/fr/defense/' WHERE name = 'Jaguar';
