-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'MiG-31',
    'MiG-31',
    'Mikoyan-Gourevitch MiG-31 Foxhound',
    'Mikoyan-Gurevich MiG-31 Foxhound',
    'Intercepteur soviétique/russe de 4e génération',
    'Soviet/Russian 4th-generation interceptor',
    '/assets/airplanes/mig31.jpg',
    'Le Mikoyan-Gourevitch MiG-31 Foxhound est un avion intercepteur supersonique développé pour les forces aériennes soviétiques, puis russes. Classé dans la 4e génération, il est conçu pour intercepter des cibles à haute altitude et grande vitesse, comme les bombardiers et missiles de croisière, avec son radar avancé Zaslon et ses missiles à longue portée. Toujours en service, il demeure un élément clé de la défense aérienne russe.',
    'The Mikoyan-Gurevich MiG-31 Foxhound is a supersonic interceptor aircraft developed for the Soviet and later Russian air forces. Classified as 4th generation, it is designed to intercept high-altitude, high-speed targets such as bombers and cruise missiles, with its advanced Zaslon radar and long-range missiles. Still in service, it remains a key element of Russian air defense.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1972-01-01',
    '1975-09-16',
    '1981-05-06',
    3000.0,
    3000.0,
    (SELECT id FROM manufacturer WHERE code = 'MIG'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Intercepteur'),
    'Actif',
    'Active',
    21825.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM tech WHERE name = 'Radar Zaslon')),
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM tech WHERE name = 'Moteurs D-30F6')),
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle')),
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM tech WHERE name = 'Système de contrôle de vol numérique')),
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM tech WHERE name = 'Système de fusion de capteurs'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM armement WHERE name = 'GSh-6-23')),
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM armement WHERE name = 'R-33')),
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM armement WHERE name = 'R-37')),
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM armement WHERE name = 'R-60'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM wars WHERE name = 'Guerre froide'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM missions WHERE name = 'Patrouille aérienne de combat')),
((SELECT id FROM airplanes WHERE name = 'MiG-31'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 22.69, wingspan = 13.46, height = 6.15, wing_area = 61.6,
  empty_weight = 21820, mtow = 46200, service_ceiling = 20600, climb_rate = 208,
  combat_radius = 720, crew = 2, g_limit_pos = 5.0,
  engine_name = 'Soloviev D-30F6', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 93.0, thrust_wet = 152.0,
  production_start = 1975, production_end = 1994, units_built = 519,
  operators_count = 2,
  nickname = 'Foxhound',
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'MiG-25' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Mikoyan_MiG-31',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Mikoyan_MiG-31'
WHERE name = 'MiG-31';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 33000000, unit_cost_year = 1988,
  variants    = E'- **MiG-31B/BS** : version de série initiale\n- **MiG-31BM** : modernisation profonde (nouveau radar Zaslon-M, R-37M)\n- **MiG-31K** : porteur du missile hypersonique Kinzhal',
  variants_en = E'- **MiG-31B/BS** : initial production variant\n- **MiG-31BM** : deep upgrade (Zaslon-M radar, R-37M)\n- **MiG-31K** : Kinzhal hypersonic missile carrier'
WHERE name = 'MiG-31';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nÉvolution ultra-rapide du MiG-25 des années 1980, conçu comme intercepteur longue portée pour la défense de l''immense territoire soviétique. Biplace, radar **Zaslon** à balayage électronique — premier PESA opérationnel au monde.\n\n## Carrière opérationnelle\nInterception de bombardiers américains SR-71 et B-52 sur les routes arctiques durant la guerre froide. Engagé en Syrie et en Ukraine. Porteur du missile hypersonique **Kinzhal** dans la version MiG-31K (depuis 2018).\n\n## Héritage\nToujours unique au monde : aucun autre intercepteur pur n''a jamais égalé son profil Mach 3 + radar longue portée. Prévu en service jusqu''en 2030+. Successeur envisagé : **PAK DP / MiG-41**.',
  description_en = E'## Genesis\nUltra-fast evolution of the MiG-25 in the 1980s, designed as a long-range interceptor to defend the vast Soviet territory. Two-seat, with an electronically-scanned **Zaslon** radar — the first operational PESA in the world.\n\n## Operational career\nIntercepted US SR-71 and B-52 bombers on Arctic routes during the Cold War. Used in Syria and Ukraine. Carrier of the **Kinzhal** hypersonic missile in the MiG-31K variant (since 2018).\n\n## Legacy\nStill unique: no other pure interceptor has ever matched its Mach 3 + long-range-radar profile. Planned in service through 2030+. Proposed successor: **PAK DP / MiG-41**.'
WHERE name = 'MiG-31';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=DvWvLLszSug'
WHERE name = 'MiG-31';
