-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'MiG-29',
    'MiG-29',
    'Mikoyan MiG-29 Fulcrum',
    'Mikoyan MiG-29 Fulcrum',
    'Chasseur multirôle soviétique/russe de 4e génération',
    'Soviet/Russian 4th-generation multirole fighter',
    '/assets/airplanes/mig29.jpg',
    'Le Mikoyan MiG-29 Fulcrum est un avion de chasse multirôle développé par le bureau MiG pour les forces aériennes soviétiques, puis russes. Classé dans la 4e génération, il est conçu pour la supériorité aérienne et les combats rapprochés, avec une grande maniabilité et une robustesse exceptionnelle. Largement exporté, il a été utilisé dans de nombreux conflits par diverses nations.',
    'The Mikoyan MiG-29 Fulcrum is a multirole fighter aircraft developed by the MiG bureau for the Soviet and later Russian air forces. Classified as 4th generation, it is designed for air superiority and close combat, with high maneuverability and exceptional ruggedness. Widely exported, it has been used in many conflicts by various nations.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1974-01-01',
    '1977-10-06',
    '1983-07-01',
    2450.0,
    1430.0,
    (SELECT id FROM manufacturer WHERE code = 'MIG'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Actif',
    'Active',
    11000.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM tech WHERE name = 'Aile à forte flèche')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM tech WHERE name = 'Radar N019')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM tech WHERE name = 'Système de contrôle de vol numérique')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM armement WHERE name = 'GSh-30-1')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM armement WHERE name = 'R-60')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM armement WHERE name = 'R-73')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM armement WHERE name = 'R-27R')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM armement WHERE name = 'FAB-500'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM wars WHERE name = 'Guerre de Yougoslavie')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'MiG-29'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 17.32, wingspan = 11.36, height = 4.73, wing_area = 38.0,
  empty_weight = 11000, mtow = 20000, service_ceiling = 18013, climb_rate = 330,
  combat_radius = 700, crew = 1, g_limit_pos = 9.0,
  engine_name = 'Klimov RD-33', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 49.4, thrust_wet = 81.4,
  production_start = 1982, production_end = NULL, units_built = 1600,
  operators_count = 25,
  nickname = 'Fulcrum',
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'MiG-23' LIMIT 1),
  rival_id = (SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Mikoyan_MiG-29',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Mikoyan_MiG-29'
WHERE name = 'MiG-29';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 29000000, unit_cost_year = 2010,
  variants    = E'- **MiG-29A/S** : versions initiales monoplace\n- **MiG-29UB** : biplace d''entraînement\n- **MiG-29K/KUB** : version navalisée (porte-avions russe + indien)\n- **MiG-29M/M2** : modernisation dite « MiG-35 »\n- **MiG-29SMT** : version export étendue',
  variants_en = E'- **MiG-29A/S** : initial single-seat versions\n- **MiG-29UB** : two-seat trainer\n- **MiG-29K/KUB** : carrier-borne (Russian + Indian carriers)\n- **MiG-29M/M2** : upgrade known as "MiG-35"\n- **MiG-29SMT** : extended export variant'
WHERE name = 'MiG-29';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nChasseur multi-rôle développé dans les années 1970-80 comme réponse soviétique au F-16 et au F/A-18 américains. Philosophie **low-mix** dans le couple Su-27/MiG-29 (le MiG étant le plus léger et le moins cher).\n\n## Carrière opérationnelle\nExporté dans **25+ pays** du Pacte de Varsovie, du monde arabe, de l''Inde, de l''Iran. Engagements majeurs : guerre du Golfe (1991, contre F-15 américains), Kosovo (1999), Érythrée-Éthiopie, Soudan, Syrie. **Rival direct du F-16** dans les exercices internationaux.\n\n## Héritage\nPlus de **1 600 exemplaires** construits. Toujours en service dans de nombreuses armées. Base du **MiG-35** modernisé.',
  description_en = E'## Genesis\nMulti-role fighter developed in the 1970s-80s as the Soviet answer to the US F-16 and F/A-18. **Low-mix** philosophy in the Su-27/MiG-29 pair (the MiG being lighter and cheaper).\n\n## Operational career\nExported to **25+ countries** across the Warsaw Pact, the Arab world, India, Iran. Major engagements: Gulf War (1991, against US F-15s), Kosovo (1999), Eritrea-Ethiopia, Sudan, Syria. **Direct rival of the F-16** in international exercises.\n\n## Legacy\nMore than **1,600 built**. Still in service in many air forces. Basis for the upgraded **MiG-35**.'
WHERE name = 'MiG-29';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=sWGjdtKv2kk'
WHERE name = 'MiG-29';
