-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'MiG-21',
    'MiG-21',
    'Mikoyan-Gourevitch MiG-21 Fishbed',
    'Mikoyan-Gurevich MiG-21 Fishbed',
    'Chasseur soviétique de 3e génération',
    'Soviet 3rd-generation fighter',
    '/assets/airplanes/mig21.jpg',
    'Le Mikoyan-Gourevitch MiG-21 Fishbed est un avion de chasse supersonique développé pour les forces aériennes soviétiques. Classé dans la 3e génération, il est connu pour sa simplicité, sa vitesse et sa maniabilité, servant principalement comme intercepteur et chasseur léger. Largement exporté, il a été un pilier des forces aériennes du Pacte de Varsovie et a participé à de nombreux conflits de la Guerre froide à nos jours.',
    'The Mikoyan-Gurevich MiG-21 Fishbed is a supersonic fighter aircraft developed for the Soviet air forces. Classified as 3rd generation, it is known for its simplicity, speed and maneuverability, serving mainly as an interceptor and light fighter. Widely exported, it was a pillar of Warsaw Pact air forces and has participated in many conflicts from the Cold War to the present.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1954-01-01',
    '1956-06-14',
    '1959-01-01',
    2230.0,
    1210.0,
    (SELECT id FROM manufacturer WHERE code = 'MIG'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Chasseur'),
    'Actif',
    'Active',
    5843.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM tech WHERE name = 'Aile delta')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM tech WHERE name = 'Réacteur Tumansky R-25')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM tech WHERE name = 'Radar RP-21')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM armement WHERE name = 'GSh-23')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM armement WHERE name = 'R-3S')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM armement WHERE name = 'R-60')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM armement WHERE name = 'FAB-250')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM armement WHERE name = 'S-5'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM wars WHERE name = 'Guerre du Vietnam')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM wars WHERE name = 'Guerre des Six Jours')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM wars WHERE name = 'Guerre du Kippour')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'MiG-21'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 14.50, wingspan = 7.15, height = 4.10, wing_area = 23.0,
  empty_weight = 5350, mtow = 9100, service_ceiling = 17800, climb_rate = 225,
  combat_radius = 370, crew = 1, g_limit_pos = 8.0,
  engine_name = 'Tumanski R-25-300', engine_count = 1,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 40.2, thrust_wet = 69.6,
  production_start = 1959, production_end = 1985, units_built = 11496,
  operators_count = 40,
  nickname = 'Fishbed',
  successor_id = (SELECT id FROM airplanes WHERE name = 'MiG-23' LIMIT 1),
  rival_id = (SELECT id FROM airplanes WHERE name = 'F-5 Freedom Fighter' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Mikoyan-Gourevitch_MiG-21',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Mikoyan-Gurevich_MiG-21'
WHERE name = 'MiG-21';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 3000000, unit_cost_year = 1975,
  variants    = E'- **MiG-21F-13** : version export initiale\n- **MiG-21PF/PFM** : intercepteur tous temps (radar RP-21)\n- **MiG-21MF** : chasseur multi-rôle (1970s)\n- **MiG-21bis** : dernière version modernisée (1976)\n- **MiG-21 Lancer** : modernisation roumaine années 90 (Elbit)',
  variants_en = E'- **MiG-21F-13** : initial export version\n- **MiG-21PF/PFM** : all-weather interceptor (RP-21 radar)\n- **MiG-21MF** : multi-role fighter (1970s)\n- **MiG-21bis** : final upgraded variant (1976)\n- **MiG-21 Lancer** : Romanian 90s upgrade (Elbit)'
WHERE name = 'MiG-21';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nDéveloppé par Mikoyan-Gourevitch dans les années 1950 comme réponse soviétique au F-104 américain et au Mirage III français : chasseur léger Mach 2 à aile delta, simple et robuste. Premier vol en 1955.\n\n## Carrière opérationnelle\nLe chasseur supersonique le plus produit de l''histoire : **plus de 11 000 exemplaires** construits (+ 2 400 copies chinoises J-7). Exporté dans **40+ pays**. Engagé au Vietnam (victoires contre F-4 Phantom), au Moyen-Orient (guerres israélo-arabes), en Inde-Pakistan, en Afghanistan, au Yémen.\n\n## Héritage\nToujours en service dans une douzaine de pays (Inde, Corée du Nord, Cuba, Égypte…). Chasseur emblématique du bloc de l''Est et du non-alignement. Son équivalent fonctionnel occidental : le F-5.',
  description_en = E'## Genesis\nDeveloped by Mikoyan-Gurevich in the 1950s as the Soviet answer to the US F-104 and French Mirage III: a simple, robust light delta-wing Mach 2 fighter. First flew in 1955.\n\n## Operational career\nThe most-produced supersonic fighter in history: **more than 11,000 built** (+ 2,400 Chinese J-7 copies). Exported to **40+ countries**. Used in Vietnam (victories against F-4 Phantoms), the Middle East (Arab-Israeli wars), India-Pakistan, Afghanistan, Yemen.\n\n## Legacy\nStill in service in a dozen countries (India, North Korea, Cuba, Egypt…). Iconic fighter of the Eastern Bloc and the non-aligned movement. Its Western functional counterpart: the F-5.'
WHERE name = 'MiG-21';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=9lTkAK3bhOU'
WHERE name = 'MiG-21';
