-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'MiG-23',
    'MiG-23',
    'Mikoyan-Gourevitch MiG-23 Flogger',
    'Mikoyan-Gurevich MiG-23 Flogger',
    'Chasseur multirôle soviétique de 3e génération',
    'Soviet 3rd-generation multirole fighter',
    '/assets/airplanes/mig23.jpg',
    'Le Mikoyan-Gourevitch MiG-23 Flogger est un avion de chasse multirôle à géométrie variable développé pour les forces aériennes soviétiques. Classé dans la 3e génération, il est conçu pour la supériorité aérienne et les frappes au sol, avec une capacité d''adaptation grâce à ses ailes ajustables. Largement exporté, il a été utilisé dans de nombreux conflits de la Guerre froide et au-delà.',
    'The Mikoyan-Gurevich MiG-23 Flogger is a variable-geometry multirole fighter aircraft developed for the Soviet air forces. Classified as 3rd generation, it is designed for air superiority and ground strikes, with adaptation capability thanks to its adjustable wings. Widely exported, it has been used in many Cold War and post-Cold War conflicts.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1964-01-01',
    '1967-06-10',
    '1970-01-01',
    2500.0,
    1900.0,
    (SELECT id FROM manufacturer WHERE code = 'MIG'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Retiré',
    NULL,
    11780.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM tech WHERE name = 'Aile à géométrie variable')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM tech WHERE name = 'Radar RP-23')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM armement WHERE name = 'GSh-23')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM armement WHERE name = 'R-23R')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM armement WHERE name = 'R-60')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM armement WHERE name = 'Kh-23')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM armement WHERE name = 'FAB-500'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM wars WHERE name = 'Guerre du Liban')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'MiG-23'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 16.70, wingspan = 13.97, height = 4.82, wing_area = 37.35,
  empty_weight = 9595, mtow = 17800, service_ceiling = 18500, climb_rate = 240,
  combat_radius = 1150, crew = 1, g_limit_pos = 8.5,
  engine_name = 'Khatchatourov R-35F-300', engine_count = 1,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 83.6, thrust_wet = 127.5,
  production_start = 1969, production_end = 1985, units_built = 5047,
  operators_count = 25,
  nickname = 'Flogger',
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'MiG-21' LIMIT 1),
  successor_id = (SELECT id FROM airplanes WHERE name = 'MiG-29' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Mikoyan-Gourevitch_MiG-23',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Mikoyan-Gurevich_MiG-23'
WHERE name = 'MiG-23';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 6500000, unit_cost_year = 1982,
  variants    = E'- **MiG-23M** : intercepteur monoplace (radar Sapfir-23)\n- **MiG-23MLD** : version optimisée dogfight\n- **MiG-23UB** : biplace d''entraînement\n- **MiG-23BN** : chasseur-bombardier export\n- **MiG-27** : dérivé attaque au sol avec nez fixe',
  variants_en = E'- **MiG-23M** : single-seat interceptor (Sapfir-23 radar)\n- **MiG-23MLD** : dogfight-optimised variant\n- **MiG-23UB** : two-seat trainer\n- **MiG-23BN** : export fighter-bomber\n- **MiG-27** : fixed-nose ground attack derivative'
WHERE name = 'MiG-23';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nPremier chasseur soviétique à **aile à géométrie variable**, développé dans les années 1960 comme réponse au F-111 américain. Intercepteur longue portée et chasseur-bombardier.\n\n## Carrière opérationnelle\nEngagé en Syrie (1973), au Liban (1982 contre les F-15/F-16 israéliens), en Afghanistan, en guerre Iran-Irak. Massivement exporté dans le Pacte de Varsovie et le monde arabe. Plus de **5 000 exemplaires** construits.\n\n## Héritage\nRetiré de la plupart des armées occidentales au profit du MiG-29. Toujours en service en Syrie, Corée du Nord, Algérie. Plateforme du MiG-27 dérivé d''attaque au sol.',
  description_en = E'## Genesis\nFirst Soviet fighter with **variable-sweep wings**, developed in the 1960s as the answer to the US F-111. Long-range interceptor and fighter-bomber.\n\n## Operational career\nUsed in Syria (1973), Lebanon (1982 against Israeli F-15/F-16s), Afghanistan, Iran-Iraq War. Massively exported across the Warsaw Pact and the Arab world. More than **5,000 built**.\n\n## Legacy\nRetired from most Eastern European armies in favour of the MiG-29. Still in service in Syria, North Korea, Algeria. Platform for the derivative MiG-27 ground-attack variant.'
WHERE name = 'MiG-23';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=sKeE5zT_XpM'
WHERE name = 'MiG-23';
