-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'MiG-25',
    'MiG-25',
    'Mikoyan-Gourevitch MiG-25 Foxbat',
    'Mikoyan-Gurevich MiG-25 Foxbat',
    'Intercepteur soviétique de 3e génération',
    'Soviet 3rd-generation interceptor',
    '/assets/airplanes/mig25.jpg',
    'Le Mikoyan-Gourevitch MiG-25 Foxbat est un avion intercepteur et de reconnaissance développé pour les forces aériennes soviétiques. Classé dans la 3e génération, il est conçu pour contrer les bombardiers supersoniques à haute altitude, atteignant des vitesses supérieures à Mach 3 grâce à sa structure en acier inoxydable. Utilisé pendant la Guerre froide, il a également servi dans des conflits au Moyen-Orient.',
    'The Mikoyan-Gurevich MiG-25 Foxbat is an interceptor and reconnaissance aircraft developed for the Soviet air forces. Classified as 3rd generation, it is designed to counter high-altitude supersonic bombers, reaching speeds above Mach 3 thanks to its stainless steel structure. Used during the Cold War, it also served in Middle East conflicts.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1961-01-01',
    '1964-03-06',
    '1970-07-01',
    3400.0,
    1730.0,
    (SELECT id FROM manufacturer WHERE code = 'MIG'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Intercepteur'),
    'Retiré',
    NULL,
    20000.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM tech WHERE name = 'Conception en acier inoxydable')),
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM tech WHERE name = 'Radar RP-25')),
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM tech WHERE name = 'Moteurs Tumansky R-15')),
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM armement WHERE name = 'R-40R')),
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM armement WHERE name = 'R-40T')),
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM armement WHERE name = 'R-60'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM wars WHERE name = 'Guerre froide')),
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM wars WHERE name = 'Guerre du Kippour')),
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'MiG-25'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 19.75, wingspan = 14.01, height = 6.10, wing_area = 61.4,
  empty_weight = 20000, mtow = 36720, service_ceiling = 20700, climb_rate = 208,
  combat_radius = 1730, crew = 1, g_limit_pos = 4.5,
  engine_name = 'Tumansky R-15B-300', engine_count = 2,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 73.5, thrust_wet = 100.1,
  production_start = 1966, production_end = 1984, units_built = 1186,
  operators_count = 8,
  nickname = 'Foxbat',
  successor_id = (SELECT id FROM airplanes WHERE name = 'MiG-31' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Mikoyan-Gourevitch_MiG-25',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Mikoyan-Gurevich_MiG-25'
WHERE name = 'MiG-25';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 30000000, unit_cost_year = 1975,
  variants    = E'- **MiG-25P** : intercepteur initial (radar Smertch-A)\n- **MiG-25PD** : modernisation radar Saphir-25\n- **MiG-25R/RB** : reconnaissance stratégique\n- **MiG-25BM** : suppression défenses (SEAD)',
  variants_en = E'- **MiG-25P** : initial interceptor (Smertch-A radar)\n- **MiG-25PD** : Saphir-25 radar upgrade\n- **MiG-25R/RB** : strategic reconnaissance\n- **MiG-25BM** : SEAD variant'
WHERE name = 'MiG-25';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nIntercepteur ultra-rapide (Mach 3) développé dans les années 1960 en réponse au bombardier stratégique américain **XB-70 Valkyrie**, lui-même annulé entre-temps. Monocoque en acier inoxydable (pas de titane faute d''approvisionnement).\n\n## Carrière opérationnelle\nMissions de reconnaissance au Moyen-Orient (Syrie, Égypte), interception au-dessus du Liban, en Irak (guerre du Golfe — plusieurs abattus par F-15). Célèbre défection du pilote Viktor Belenko au Japon (1976) révélant les secrets de l''appareil à l''Occident.\n\n## Héritage\nRetiré par la Russie en 2013. Le successeur **MiG-31 Foxhound** conserve la philosophie Mach 3 tout en modernisant radar et armement.',
  description_en = E'## Genesis\nUltra-fast interceptor (Mach 3) developed in the 1960s in response to the American **XB-70 Valkyrie** strategic bomber, itself cancelled in the meantime. Stainless-steel monocoque (no titanium due to supply).\n\n## Operational career\nReconnaissance missions over the Middle East (Syria, Egypt), interceptions over Lebanon, Iraq (Gulf War — several shot down by F-15s). Famous defection of pilot Viktor Belenko to Japan (1976) which revealed the aircraft''s secrets to the West.\n\n## Legacy\nRetired by Russia in 2013. Its successor, the **MiG-31 Foxhound**, preserves the Mach 3 philosophy while modernising radar and weaponry.'
WHERE name = 'MiG-25';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=W1L1sU0uI0o'
WHERE name = 'MiG-25';
