-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Mirage III',
    'Mirage III',
    'Dassault Mirage III',
    'Dassault Mirage III',
    'Chasseur français de 3e génération',
    'French 3rd-generation fighter',
    '/assets/airplanes/mirage3.jpg',
    'Le Dassault Mirage III est un avion de chasse emblématique développé par Dassault Aviation pour l''Armée de l''Air française. Premier avion de combat européen à dépasser Mach 2, il est classé dans la 3e génération et a été conçu principalement pour l''interception et la supériorité aérienne. Avec son aile delta, il a été largement exporté et employé dans de nombreux conflits, notamment au Moyen-Orient.',
    'The Dassault Mirage III is an iconic fighter aircraft developed by Dassault Aviation for the French Air Force. The first European combat aircraft to exceed Mach 2, it is classified as 3rd generation and was designed primarily for interception and air superiority. With its delta wing, it was widely exported and employed in many conflicts, notably in the Middle East.',
    (SELECT id FROM countries WHERE code = 'FRA'),
    '1953-01-01',
    '1956-11-17',
    '1961-07-12',
    2350.0,
    2400.0,
    (SELECT id FROM manufacturer WHERE code = 'DAS'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Intercepteur'),
    'Retiré',
    NULL,
    7050.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM tech WHERE name = 'Aile delta')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM tech WHERE name = 'Radar Cyrano')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM tech WHERE name = 'Système de navigation semi-automatique'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM armement WHERE name = 'DEFA 552')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM armement WHERE name = 'Matra R530')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM armement WHERE name = 'Matra R550 Magic')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM armement WHERE name = 'Bombe lisse 400 kg'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM wars WHERE name = 'Guerre des Six Jours')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM wars WHERE name = 'Guerre du Kippour')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM wars WHERE name = 'Conflit israélo-arabe'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Mirage III'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 15.03, wingspan = 8.22, height = 4.25, wing_area = 35.0,
  empty_weight = 7050, mtow = 13700, service_ceiling = 17000, climb_rate = 175,
  combat_radius = 1200, crew = 1, g_limit_pos = 9.0,
  engine_name = 'SNECMA Atar 09C', engine_count = 1,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 41.97, thrust_wet = 60.8,
  production_start = 1961, production_end = 1992, units_built = 1422,
  operators_count = 21,
  successor_id = (SELECT id FROM airplanes WHERE name = 'Mirage F1' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Dassault_Mirage_III',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Dassault_Mirage_III'
WHERE name = 'Mirage III';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 1500000, unit_cost_year = 1963,
  manufacturer_page = 'https://www.dassault-aviation.com/fr/',
  variants    = E'- **Mirage IIIC** : intercepteur monoplace (95 ex. Armée de l''air)\n- **Mirage IIIE** : attaque tous temps\n- **Mirage IIIR/RD** : reconnaissance\n- **Mirage 5** : dérivé VFR simplifié pour l''export\n- **Mirage 50** : ré-engine Atar 9K-50',
  variants_en = E'- **Mirage IIIC** : single-seat interceptor (95 built for French AF)\n- **Mirage IIIE** : all-weather strike\n- **Mirage IIIR/RD** : reconnaissance\n- **Mirage 5** : simplified VFR export derivative\n- **Mirage 50** : Atar 9K-50 re-engined'
WHERE name = 'Mirage III';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nPremier avion de combat français à franchir Mach 2 en vol horizontal (1958). Dassault impose l''aile delta sans empennage horizontal — configuration qui deviendra la signature Dassault jusqu''au Rafale.\n\n## Carrière opérationnelle\nChasseur iconique des années 1960-80 : engagé en guerre du Kippour (Israël, 1973), au Pakistan (1971), en Argentine (1982 Malouines), au Tchad, en Libye. Exporté dans **21 pays**. Succès commercial majeur de Dassault.\n\n## Héritage\nPlus de **1 400 exemplaires** produits — plus grand succès commercial de Dassault jusqu''à l''arrivée du Mirage 2000. A posé les fondements aérodynamiques et industriels qui aboutiront au Rafale 30 ans plus tard.',
  description_en = E'## Genesis\nFirst French combat aircraft to break Mach 2 in level flight (1958). Dassault imposed the tailless delta wing — a configuration that would become the Dassault signature all the way to the Rafale.\n\n## Operational career\nIconic fighter of the 1960s-80s: used in the Yom Kippur War (Israel, 1973), Pakistan (1971), Argentina (1982 Falklands), Chad, Libya. Exported to **21 countries**. Dassault''s first major commercial success.\n\n## Legacy\nMore than **1,400 built** — Dassault''s biggest commercial success until the Mirage 2000. It laid the aerodynamic and industrial foundations that would lead to the Rafale three decades later.'
WHERE name = 'Mirage III';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = 'https://www.dassault-aviation.com/fr/defense/' WHERE name = 'Mirage III';
