-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Mirage 2000',
    'Mirage 2000',
    'Dassault Mirage 2000',
    'Dassault Mirage 2000',
    'Chasseur multirôle français de 4e génération',
    'French 4th-generation multirole fighter',
    '/assets/airplanes/mirage2000.jpg',
    'Le Dassault Mirage 2000 est un avion de chasse multirôle développé par Dassault Aviation pour l''Armée de l''Air française. Appartenant à la 4e génération, il est conçu pour la supériorité aérienne et les frappes au sol, avec une aile delta, un système fly-by-wire et une grande maniabilité. Utilisé dans de nombreux conflits, il est également exporté vers plusieurs pays.',
    'The Dassault Mirage 2000 is a multirole fighter aircraft developed by Dassault Aviation for the French Air Force. Belonging to the 4th generation, it is designed for air superiority and ground strikes, with a delta wing, fly-by-wire system and high maneuverability. Used in many conflicts, it has also been exported to several countries.',
    (SELECT id FROM countries WHERE code = 'FRA'),
    '1975-01-01',
    '1978-03-10',
    '1984-07-02',
    2338.0,
    1550.0,
    (SELECT id FROM manufacturer WHERE code = 'DAS'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Actif',
    'Active',
    7500.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM tech WHERE name = 'Aile delta')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM tech WHERE name = 'Commande de vol électrique (fly-by-wire)')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM tech WHERE name = 'Radar RDM/RDI')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM tech WHERE name = 'Matériaux composites')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM armement WHERE name = 'DEFA 554')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM armement WHERE name = 'Matra R550 Magic')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM armement WHERE name = 'Matra Super 530D')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM armement WHERE name = 'AS-30L')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM armement WHERE name = 'GBU-12 Paveway II'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'Mirage 2000'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 14.36, wingspan = 9.13, height = 5.20, wing_area = 41.0,
  empty_weight = 7500, mtow = 17500, service_ceiling = 17060, climb_rate = 285,
  combat_radius = 1480, crew = 1, g_limit_pos = 9.0, g_limit_neg = -3.2,
  engine_name = 'SNECMA M53-P2', engine_count = 1,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 64.3, thrust_wet = 95.1,
  production_start = 1978, production_end = 2007, units_built = 601,
  operators_count = 9,
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'Mirage F1' LIMIT 1),
  successor_id = (SELECT id FROM airplanes WHERE name = 'Rafale' LIMIT 1),
  rival_id = (SELECT id FROM airplanes WHERE name = 'F-16 Fighting Falcon' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Dassault_Mirage_2000',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Dassault_Mirage_2000',
  variants    = E'- **Mirage 2000C** : intercepteur monoplace\n- **Mirage 2000B** : biplace d''entraînement\n- **Mirage 2000N** : version nucléaire tactique (ASMP)\n- **Mirage 2000D** : attaque au sol conventionnelle\n- **Mirage 2000-5/9** : export, radar RDY + MICA',
  variants_en = E'- **Mirage 2000C** : single-seat interceptor\n- **Mirage 2000B** : two-seat trainer\n- **Mirage 2000N** : tactical nuclear strike (ASMP)\n- **Mirage 2000D** : conventional ground attack\n- **Mirage 2000-5/9** : export, RDY radar + MICA'
WHERE name = 'Mirage 2000';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 23000000, unit_cost_year = 1990,
  manufacturer_page = 'https://www.dassault-aviation.com/fr/defense/mirage-2000/'
WHERE name = 'Mirage 2000';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nDassault revient à l''aile delta dans les années 1970 avec **commandes de vol électriques** et instabilité volontaire. Objectif : rattraper l''avance américaine représentée par le F-16 tout en assurant la mission nucléaire tactique française.\n\n## Carrière opérationnelle\nChasseur principal de l''Armée de l''air française pendant 35 ans. Engagé en guerre du Golfe (1991), Kosovo, Afghanistan, Libye (2011), Sahel (Barkhane). Exporté en Inde, Égypte, Grèce, Taïwan, Émirats arabes unis, Pérou, Brésil.\n\n## Héritage\nPlus de **600 exemplaires** produits. Remplacé progressivement par le Rafale dans l''Armée de l''air. Rival direct du F-16, vainqueur de plusieurs exercices en dogfight avec F-15 américain.',
  description_en = E'## Genesis\nDassault returned to the delta wing in the 1970s with **fly-by-wire controls** and deliberate instability. The aim: match the American F-16 head-start while ensuring the French tactical nuclear mission.\n\n## Operational career\nMain French Air Force fighter for 35 years. Engaged in the Gulf War (1991), Kosovo, Afghanistan, Libya (2011), Sahel (Barkhane). Exported to India, Egypt, Greece, Taiwan, UAE, Peru, Brazil.\n\n## Legacy\nMore than **600 built**. Progressively replaced by the Rafale in the French Air Force. Direct rival of the F-16, victor in several dogfight exercises against the US F-15.'
WHERE name = 'Mirage 2000';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = 'https://www.dassault-aviation.com/fr/defense/' WHERE name = 'Mirage 2000';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=WsFGyKRVbUY'
WHERE name = 'Mirage 2000';
