-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Mirage IV',
    'Mirage IV',
    'Dassault Mirage IV',
    'Dassault Mirage IV',
    'Bombardier stratégique français de 3e génération',
    'French 3rd-generation strategic bomber',
    '/assets/airplanes/mirage4.jpg',
    'Le Dassault Mirage IV est un bombardier stratégique supersonique développé par Dassault Aviation pour l''Armée de l''Air française. Classé dans la 3e génération, il a été conçu pour la dissuasion nucléaire avec des capacités de pénétration à basse altitude. Utilisé comme vecteur principal de la force de frappe nucléaire française pendant la Guerre froide, il a été adapté plus tard pour des missions de reconnaissance.',
    'The Dassault Mirage IV is a supersonic strategic bomber developed by Dassault Aviation for the French Air Force. Classified as 3rd generation, it was designed for nuclear deterrence with low-altitude penetration capabilities. Used as the main vector of the French nuclear strike force during the Cold War, it was later adapted for reconnaissance missions.',
    (SELECT id FROM countries WHERE code = 'FRA'),
    '1956-01-01',
    '1959-06-17',
    '1964-10-01',
    2340.0,
    4000.0,
    (SELECT id FROM manufacturer WHERE code = 'DAS'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Bombardier'),
    'Retiré',
    NULL,
    14450.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM tech WHERE name = 'Aile delta')),
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM tech WHERE name = 'Système de ravitaillement en vol automatique')),
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM tech WHERE name = 'Soute à armement pressurisée')),
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM armement WHERE name = 'AN-11')),
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM armement WHERE name = 'AN-22')),
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM armement WHERE name = 'ASMP')),
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM armement WHERE name = 'ASMP-A'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM wars WHERE name = 'Guerre froide'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM missions WHERE name = 'Dissuasion nucléaire')),
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'Mirage IV'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 23.49, wingspan = 11.85, height = 5.4, wing_area = 78.0,
  empty_weight = 14500, mtow = 31600, service_ceiling = 20000, climb_rate = 300,
  combat_radius = 1240, crew = 2,
  engine_name = 'SNECMA Atar 9K', engine_count = 2,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 49.0, thrust_wet = 70.6,
  production_start = 1959, production_end = 1968, units_built = 62,
  operators_count = 1,
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Dassault_Mirage_IV',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Dassault_Mirage_IV'
WHERE name = 'Mirage IV';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 4000000, unit_cost_year = 1964,
  manufacturer_page = 'https://www.dassault-aviation.com/fr/',
  variants    = E'- **Mirage IVA** : bombardier stratégique, porteur de la bombe AN-11/AN-22\n- **Mirage IVP** : modernisation, porteur du missile ASMP (mission nucléaire tactique jusqu''en 1996)',
  variants_en = E'- **Mirage IVA** : strategic bomber, AN-11/AN-22 nuclear delivery\n- **Mirage IVP** : upgrade, ASMP missile carrier (tactical nuclear role until 1996)'
WHERE name = 'Mirage IV';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nBombardier stratégique supersonique développé dans les années 1950 pour porter la **force de dissuasion nucléaire française** (FOST air). Premier vol en 1959, mise en service en 1964.\n\n## Carrière opérationnelle\nArme centrale de la **dissuasion nucléaire aérienne** française durant toute la guerre froide. Modernisé en Mirage IVP pour tirer le missile ASMP (Air-Sol Moyenne Portée). Reconverti en reconnaissance stratégique à la fin de sa carrière.\n\n## Héritage\nRetiré en 1996 (frappes nucléaires) et 2005 (reconnaissance). Symbole de la souveraineté française en matière de dissuasion. Seul bombardier stratégique supersonique développé en Europe occidentale.',
  description_en = E'## Genesis\nSupersonic strategic bomber developed in the 1950s to carry the **French nuclear deterrent** (FOST air component). First flew in 1959, entered service in 1964.\n\n## Operational career\nCentral weapon of the French **airborne nuclear deterrent** throughout the Cold War. Upgraded as Mirage IVP to fire the ASMP (medium-range air-to-surface) missile. Converted to strategic reconnaissance at the end of its career.\n\n## Legacy\nRetired in 1996 (nuclear strike) and 2005 (reconnaissance). A symbol of French sovereignty in deterrence. The only supersonic strategic bomber ever developed in Western Europe.'
WHERE name = 'Mirage IV';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = 'https://www.dassault-aviation.com/fr/defense/' WHERE name = 'Mirage IV';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=STwN8daYHnc'
WHERE name = 'Mirage IV';
