-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Mirage F1',
    'Mirage F1',
    'Dassault Mirage F1',
    'Dassault Mirage F1',
    'Chasseur multirôle français de 3e génération',
    'French 3rd-generation multirole fighter',
    '/assets/airplanes/miragef1.jpg',
    'Le Dassault Mirage F1 est un avion de chasse multirôle développé par Dassault Aviation pour l''Armée de l''Air française. Successeur du Mirage III, il est classé dans la 3e génération avec une amélioration de la maniabilité à basse vitesse grâce à son aile en flèche. Utilisé pour la supériorité aérienne et les frappes au sol, il a été exporté et engagé dans plusieurs conflits.',
    'The Dassault Mirage F1 is a multirole fighter aircraft developed by Dassault Aviation for the French Air Force. Successor to the Mirage III, it is classified as 3rd generation with improved low-speed maneuverability thanks to its swept wing. Used for air superiority and ground strikes, it has been exported and engaged in several conflicts.',
    (SELECT id FROM countries WHERE code = 'FRA'),
    '1964-01-01',
    '1966-12-23',
    '1973-06-14',
    2338.0,
    3300.0,
    (SELECT id FROM manufacturer WHERE code = 'DAS'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Retiré',
    NULL,
    7400.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM tech WHERE name = 'Aile en flèche')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM tech WHERE name = 'Radar Cyrano IV')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM tech WHERE name = 'Perche de ravitaillement en vol')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM armement WHERE name = 'DEFA 553')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM armement WHERE name = 'Matra R550 Magic')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM armement WHERE name = 'Matra Super 530F')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM armement WHERE name = 'AS-30')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM armement WHERE name = 'Bombe lisse 250 kg'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'Mirage F1'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 15.30, wingspan = 8.40, height = 4.50, wing_area = 25.0,
  empty_weight = 7400, mtow = 16200, service_ceiling = 20000, climb_rate = 243,
  combat_radius = 425, crew = 1, g_limit_pos = 9.0,
  engine_name = 'SNECMA Atar 9K-50', engine_count = 1,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 49.0, thrust_wet = 70.6,
  production_start = 1973, production_end = 1992, units_built = 726,
  operators_count = 11,
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'Mirage III' LIMIT 1),
  successor_id = (SELECT id FROM airplanes WHERE name = 'Mirage 2000' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Dassault_Mirage_F1',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Dassault_Mirage_F1'
WHERE name = 'Mirage F1';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 10000000, unit_cost_year = 1982,
  manufacturer_page = 'https://www.dassault-aviation.com/fr/',
  variants    = E'- **Mirage F1C** : intercepteur monoplace\n- **Mirage F1B** : biplace d''entraînement\n- **Mirage F1CR** : reconnaissance\n- **Mirage F1CT** : attaque tactique\n- **Mirage F1CG/EQ/M** : versions export (Grèce, Irak, Maroc…)',
  variants_en = E'- **Mirage F1C** : single-seat interceptor\n- **Mirage F1B** : two-seat trainer\n- **Mirage F1CR** : reconnaissance\n- **Mirage F1CT** : tactical strike\n- **Mirage F1CG/EQ/M** : export (Greece, Iraq, Morocco…)'
WHERE name = 'Mirage F1';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nPremier chasseur Dassault à aile en flèche (rupture avec le delta Mirage III/5). Conçu dans les années 1970 pour remplacer le Mirage III comme intercepteur principal de l''Armée de l''air française.\n\n## Carrière opérationnelle\nExporté dans **11 pays** (Grèce, Irak, Jordanie, Koweït, Maroc, Espagne, Afrique du Sud…). Utilisé par l''Irak pendant la guerre Iran-Irak et la guerre du Golfe. Engagé par la France au Tchad, en Irak (2003).\n\n## Héritage\nRetiré de l''Armée de l''air française en 2014. Toujours en service en Iran et au Maroc. Chaînon majeur entre le Mirage III et le Mirage 2000, premier Dassault à aile classique.',
  description_en = E'## Genesis\nFirst Dassault fighter with a swept wing (breaking from the delta of the Mirage III/5). Designed in the 1970s to replace the Mirage III as the main interceptor of the French Air Force.\n\n## Operational career\nExported to **11 countries** (Greece, Iraq, Jordan, Kuwait, Morocco, Spain, South Africa…). Used by Iraq during the Iran-Iraq War and the Gulf War. Engaged by France in Chad, Iraq (2003).\n\n## Legacy\nRetired from the French Air Force in 2014. Still in service in Iran and Morocco. Major link between the Mirage III and the Mirage 2000, the first swept-wing Dassault fighter.'
WHERE name = 'Mirage F1';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = 'https://www.dassault-aviation.com/fr/defense/' WHERE name = 'Mirage F1';
