INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Rafale',
    'Rafale',
    'Dassault Rafale',
    'Dassault Rafale',
    'Chasseur multirôle français de 4e génération',
    'French 4th-generation multirole fighter',
    '/assets/airplanes/rafale.jpg',
    'Le Dassault Rafale est un avion de combat multirôle développé par Dassault Aviation. Conçu pour opérer dans des missions air-air et air-sol, il intègre des technologies avancées comme la furtivité partielle, un radar AESA et des systèmes de guerre électronique sophistiqués. Utilisé par l''Armée de l''Air française et la Marine nationale, il excelle dans la supériorité aérienne, les frappes de précision et la reconnaissance.',
    'The Dassault Rafale is a multirole combat aircraft developed by Dassault Aviation. Designed to operate in air-to-air and air-to-ground missions, it integrates advanced technologies such as partial stealth, an AESA radar and sophisticated electronic warfare systems. Used by the French Air Force and the French Navy, it excels in air superiority, precision strikes and reconnaissance.',
    (SELECT id FROM countries WHERE code = 'FRA'),
    '1982-12-01',
    '1986-07-04',
    '2001-05-18',
    2450.0,
    3700.0,
    (SELECT id FROM manufacturer WHERE code = 'DAS'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Actif',
    'Active',
    10000.0
);

INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM tech WHERE name = 'Aile canard delta')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM tech WHERE name = 'Système SPECTRA')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM tech WHERE name = 'Radar RBE2 AESA')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM tech WHERE name = 'Fusion de capteurs'));

INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM armement WHERE name = 'GIAT 30M791')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM armement WHERE name = 'MICA IR')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM armement WHERE name = 'MICA EM')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM armement WHERE name = 'Meteor')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM armement WHERE name = 'SCALP EG')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM armement WHERE name = 'AM39 Exocet'));

INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM missions WHERE name = 'Attaque antinavire'));

INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'Rafale'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));
-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js

BEGIN;

UPDATE airplanes SET
  -- ── Strate 1 : fiche technique étendue ─────────────────────────
  length            = 15.27,       -- mètres
  wingspan          = 10.80,
  height            = 5.34,
  wing_area         = 45.7,        -- m²
  empty_weight      = 10300,       -- kg (variante C)
  mtow              = 24500,       -- kg
  service_ceiling   = 15240,       -- m (50 000 ft)
  climb_rate        = 305,         -- m/s (≈ 60 000 ft/min)
  g_limit_pos       = 9.0,
  g_limit_neg       = -3.2,
  combat_radius     = 1850,        -- km avec ravitaillement interne
  crew              = 1,           -- C monoplace ; B biplace

  -- ── Strate 2 : motorisation ────────────────────────────────────
  engine_name       = 'Snecma M88-2E4',
  engine_count      = 2,
  engine_type       = 'Turbofan avec postcombustion',
  engine_type_en    = 'Afterburning turbofan',
  thrust_dry        = 50.04,       -- kN par moteur
  thrust_wet        = 75.62,       -- kN par moteur (PC)

  -- ── Strate 3 : production & service ────────────────────────────
  production_start  = 1986,        -- premier vol prototype A
  production_end    = NULL,        -- toujours en production (backlog > 2030)
  units_built       = 240,
  unit_cost_usd     = 85000000,    -- 85 M$ unitaire (export 2024)
  unit_cost_year    = 2024,
  operators_count   = 6,           -- France, Égypte, Qatar, Inde, Grèce, Croatie (+ commandes Indonésie/UAE/Serbie)
  -- E'' prefix requis pour interpréter \n comme newline réel (sinon PG stocke
  -- les 2 caractères littéraux \ + n et le markdown parser front rend comme texte).
  variants          = E'- **Rafale C** : monoplace, Armée de l''air française\n- **Rafale B** : biplace, Armée de l''air française\n- **Rafale M** : monoplace navalisé, Marine nationale (catapultage + crosse d''appontage)\n- **Standard F3-R / F4.1 / F4.2** : évolutions logicielles et armement (Meteor, Scalp, ASMPA)',
  variants_en       = E'- **Rafale C** : single-seat, French Air Force\n- **Rafale B** : two-seat, French Air Force\n- **Rafale M** : single-seat carrier-borne, French Navy (catapult launch + arrestor hook)\n- **Standard F3-R / F4.1 / F4.2** : software and weapons upgrades (Meteor, Scalp, ASMPA)',

  -- ── Strate 4 : qualitatif + références croisées ────────────────
  stealth_level     = 'reduite',   -- signature réduite, pas furtivité classe 5e gen
  nickname          = 'Omnirôle',

  -- Mirage 2000 comme prédécesseur — lookup par nom (INSERT ordonné)
  predecessor_id    = (SELECT id FROM airplanes WHERE name = 'Mirage 2000' LIMIT 1),

  -- Pas de successeur encore en service (FCAS/NGF prévu ~2040)
  successor_id      = NULL,

  -- Eurofighter Typhoon comme rival européen direct
  rival_id          = (SELECT id FROM airplanes WHERE name LIKE 'Eurofighter%' ORDER BY id LIMIT 1),

  -- ── Strate 6 : médias externes ─────────────────────────────────
  wikipedia_fr      = 'https://fr.wikipedia.org/wiki/Dassault_Rafale',
  wikipedia_en      = 'https://en.wikipedia.org/wiki/Dassault_Rafale',
  -- YouTube à compléter manuellement (ID stable vérifié) — laissé NULL
  -- pour éviter un lien mort.
  youtube_showcase  = NULL,
  manufacturer_page = 'https://www.dassault-aviation.com/fr/defense/rafale/',

  -- ── Strate 5 : narratif markdown ───────────────────────────────
  description = E'## Genèse\nDans les années 1980, la France quitte le programme européen **EFA** (futur Eurofighter) pour développer un chasseur multirôle 100% français, adapté à la fois à l''Armée de l''air et à la Marine nationale. Objectif : remplacer à terme sept types d''appareils différents (Jaguar, Mirage F1, Mirage 2000, Super Étendard, Crusader…) par un seul avion. Le premier démonstrateur **Rafale A** vole en 1986.\n\n## Conception\nLe Rafale combine une aile delta cambrée, des plans canard rapprochés et des commandes de vol électriques (*fly-by-wire*) pour une agilité extrême malgré une instabilité aérodynamique volontaire. Sa signature radar est fortement réduite (formes et matériaux absorbants) sans atteindre la furtivité classe 5e génération. Le système [SPECTRA](https://fr.wikipedia.org/wiki/SPECTRA) assure la guerre électronique intégrée : détection, brouillage, leurrage automatique.\n\n## Carrière opérationnelle\nPremier engagement en combat réel au-dessus de l''**Afghanistan** en 2007. Déploiements ultérieurs :\n- **Libye** (2011) : première utilisation du missile de croisière Scalp\n- **Mali** (2013) : opération Serval\n- **Syrie / Irak** (2015) : opération Chammal\n- **Proche-Orient** (2024) : interception de drones iraniens lors de l''attaque sur Israël\n\n## Anecdote\nPremier avion de combat européen à tirer un missile **Meteor** en opérations réelles. Lors des essais de catapultage embarqué sur porte-avions américains, le Rafale M a démontré une compatibilité totale avec les procédures de la **US Navy** — unique cas d''un chasseur non-américain interopérable avec le CVN de l''US Navy.\n\n## Place dans l''histoire\nDernier chasseur de **4e génération avancée** développé en Europe occidentale de manière quasi-souveraine. Son succès à l''export (Égypte, Qatar, Inde, Grèce, Croatie, Indonésie, UAE, Serbie) — démarré à partir de 2015 après plus de 10 ans de revers commerciaux — en fait le symbole de la résilience de la base industrielle française. Il prépare l''avènement du **FCAS / NGF**, chasseur 6e génération franco-allemand-espagnol prévu pour ~2040.',

  description_en = E'## Genesis\nIn the 1980s, France withdrew from the European EFA programme (future Eurofighter) to develop a 100% French multi-role fighter suited to both the Air Force and the Navy. The goal was to replace seven different aircraft types (Jaguar, Mirage F1, Mirage 2000, Super Étendard, Crusader…) with a single platform. The **Rafale A** demonstrator first flew in 1986.\n\n## Design\nRafale combines a cambered delta wing, close-coupled canards and digital fly-by-wire controls for extreme agility despite deliberate aerodynamic instability. Its radar signature is substantially reduced (shapes and RAM materials) without reaching fifth-generation stealth levels. The integrated [SPECTRA](https://en.wikipedia.org/wiki/SPECTRA) system handles electronic warfare: detection, jamming, automatic decoying.\n\n## Operational career\nFirst real combat use over **Afghanistan** in 2007. Later deployments:\n- **Libya** (2011) — first operational Scalp cruise missile firing\n- **Mali** (2013) — Operation Serval\n- **Syria / Iraq** (2015) — Operation Chammal\n- **Middle East** (2024) — interception of Iranian drones during the attack on Israel\n\n## Anecdote\nFirst European combat aircraft to fire a **Meteor** missile in actual operations. During carrier qualification trials on US Navy CVNs, the Rafale M demonstrated complete interoperability with US Navy procedures — the only non-American fighter fully compatible with US carrier operations.\n\n## Place in history\nThe last **advanced 4th-generation** fighter developed in Western Europe with near-full sovereignty. Its export success (Egypt, Qatar, India, Greece, Croatia, Indonesia, UAE, Serbia) — finally achieved from 2015 after more than a decade of commercial setbacks — symbolises the resilience of France''s defence industrial base. It now paves the way for the **FCAS / NGF**, the Franco-German-Spanish sixth-generation fighter slated for the 2040s.'

WHERE name = 'Rafale';

COMMIT;

-- Vérification rapide
-- SELECT name, engine_name, crew, mtow, stealth_level, nickname,
--        (SELECT name FROM airplanes WHERE id = a.predecessor_id) AS predecessor,
--        (SELECT name FROM airplanes WHERE id = a.rival_id) AS rival
-- FROM airplanes a WHERE name = 'Rafale';
