-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'BAE Sea Harrier',
    'BAE Sea Harrier',
    'British Aerospace Sea Harrier',
    'British Aerospace Sea Harrier',
    'Chasseur embarqué VTOL britannique de 3e génération',
    'British 3rd-generation VTOL carrier-based fighter',
    '/assets/airplanes/sea-harrier.jpg',
    'Le British Aerospace Sea Harrier est la version navalisée du Harrier, développée pour la Royal Navy afin d''opérer depuis des porte-aéronefs légers de classe Invincible grâce à son décollage court et atterrissage vertical (STOVL). Classé dans la 3e génération, il combine la poussée vectorielle du réacteur Rolls-Royce Pegasus avec un radar Blue Fox (puis Blue Vixen sur la version FA2) et des missiles air-air pour la défense aérienne de la flotte. Le Sea Harrier s''est illustré de manière décisive pendant la guerre des Malouines en 1982, où il a remporté 20 victoires aériennes sans aucune perte en combat aérien, un bilan exceptionnel qui a démontré la viabilité du concept VTOL en opérations navales. Il a ensuite servi dans les Balkans avant d''être retiré en 2006, remplacé par le Harrier GR.9 puis le F-35B Lightning II.',
    'The British Aerospace Sea Harrier is the navalized version of the Harrier, developed for the Royal Navy to operate from Invincible-class light aircraft carriers thanks to its short take-off and vertical landing (STOVL). Classified as 3rd generation, it combines the vectored thrust of the Rolls-Royce Pegasus engine with a Blue Fox radar (then Blue Vixen on the FA2 version) and air-to-air missiles for fleet air defense. The Sea Harrier distinguished itself decisively during the Falklands War in 1982, where it won 20 air victories without any loss in air combat, an exceptional record that demonstrated the viability of the VTOL concept in operations.',
    (SELECT id FROM countries WHERE code = 'GBR'),
    '1975-01-01',
    '1978-08-20',
    '1980-04-18',
    1185.0,
    3600.0,
    (SELECT id FROM manufacturer WHERE code = 'BAE'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Chasseur'),
    'Retiré',
    NULL,
    6374.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM tech WHERE name = 'Aile en flèche')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM tech WHERE name = 'Moteur à poussée vectorielle')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM tech WHERE name = 'Radar Blue Fox')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM tech WHERE name = 'Système navalisé')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM armement WHERE name = 'ADEN 30 mm')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM armement WHERE name = 'AIM-9 Sidewinder')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM armement WHERE name = 'AIM-120 AMRAAM')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM armement WHERE name = 'Sea Eagle')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM armement WHERE name = 'BL755'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM wars WHERE name = 'Guerre des Malouines')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM wars WHERE name = 'Guerre de Yougoslavie'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM missions WHERE name = 'Patrouille aérienne de combat')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM missions WHERE name = 'Attaque antinavire')),
((SELECT id FROM airplanes WHERE name = 'BAE Sea Harrier'), (SELECT id FROM missions WHERE name = 'Reconnaissance armée'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 14.17, wingspan = 7.70, height = 3.71, wing_area = 18.68,
  empty_weight = 6374, mtow = 11884, service_ceiling = 15240, climb_rate = 50,
  combat_radius = 740, crew = 1, g_limit_pos = 7.8,
  engine_name = 'Rolls-Royce Pegasus 106', engine_count = 1,
  engine_type = 'Turbofan à tuyères vectorielles', engine_type_en = 'Vectored-thrust turbofan',
  thrust_dry = 95.6,
  production_start = 1978, production_end = 1999, units_built = 103,
  operators_count = 2,
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'Hawker Siddeley Harrier' LIMIT 1),
  successor_id = (SELECT id FROM airplanes WHERE name = 'F-35B Lightning II Anglais' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/British_Aerospace_Sea_Harrier',
  wikipedia_en = 'https://en.wikipedia.org/wiki/British_Aerospace_Sea_Harrier'
WHERE name = 'BAE Sea Harrier';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 12000000, unit_cost_year = 1988,
  variants    = E'- **Sea Harrier FRS.1** : version initiale Royal Navy\n- **Sea Harrier FA.2** : modernisation radar Blue Vixen + AMRAAM\n- **Sea Harrier Mk.51** : version export Indian Navy',
  variants_en = E'- **Sea Harrier FRS.1** : initial Royal Navy version\n- **Sea Harrier FA.2** : Blue Vixen radar + AMRAAM upgrade\n- **Sea Harrier Mk.51** : Indian Navy export'
WHERE name = 'BAE Sea Harrier';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nVersion navalisée du Harrier, développée dans les années 1970 pour opérer depuis les nouveaux porte-avions légers britanniques (classe Invincible). Intègre un radar Blue Fox puis Blue Vixen et la capacité d''emporter des missiles AIM-120 AMRAAM.\n\n## Carrière opérationnelle\nHéros de la **guerre des Malouines** (1982) : 28 Sea Harriers revendiquent 20 victoires aériennes (contre Mirage III et A-4 argentins) sans aucune perte en combat. Pont aérien avec porte-avions improvisés.\n\n## Héritage\nRetiré par la Royal Navy en 2006, laissant la Fleet Air Arm sans chasseur embarqué jusqu''au F-35B. Toujours en service dans la **Marine indienne** (ravitaillement via porte-avions INS Vikramaditya).',
  description_en = E'## Genesis\nNavalised Harrier variant developed in the 1970s to operate from the new British light carriers (Invincible class). Integrates a Blue Fox then Blue Vixen radar and the ability to carry AIM-120 AMRAAM missiles.\n\n## Operational career\nHero of the **Falklands War** (1982): 28 Sea Harriers claimed 20 air-to-air victories (against Argentine Mirage III and A-4s) with no combat losses. Air bridge with improvised carriers.\n\n## Legacy\nRetired by the Royal Navy in 2006, leaving the Fleet Air Arm without a carrier fighter until the F-35B. Still operated by the **Indian Navy** (previously on INS Vikramaditya carrier).'
WHERE name = 'BAE Sea Harrier';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=d9ui9QikkkQ'
WHERE name = 'BAE Sea Harrier';
