-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'SR-71 Blackbird',
    'SR-71 Blackbird',
    'Lockheed SR-71 Blackbird',
    'Lockheed SR-71 Blackbird',
    'Avion de reconnaissance stratégique américain de 3e génération',
    'American 3rd-generation strategic reconnaissance aircraft',
    '/assets/airplanes/sr71-blackbird.jpg',
    'Le Lockheed SR-71 Blackbird est un avion de reconnaissance stratégique à longue portée et haute altitude, développé pour l''US Air Force. Classé dans la 3e génération, il est célèbre pour sa vitesse exceptionnelle (plus de Mach 3) et son design furtif précoce, conçu pour échapper aux défenses ennemies. Utilisé pendant la Guerre froide, il a établi des records de vitesse et d''altitude inégalés.',
    'The Lockheed SR-71 Blackbird is a long-range, high-altitude strategic reconnaissance aircraft developed for the US Air Force. Classified as 3rd generation, it is famous for its exceptional speed (over Mach 3) and its early stealth design, designed to evade enemy defenses. Used during the Cold War, it set unmatched speed and altitude records.',
    (SELECT id FROM countries WHERE code = 'USA'),
    '1960-01-01',
    '1964-12-22',
    '1966-01-01',
    3529.0,
    5400.0,
    (SELECT id FROM manufacturer WHERE code = 'LM'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Reconnaissance'),
    'Retiré',
    NULL,
    30600.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'SR-71 Blackbird'), (SELECT id FROM tech WHERE name = 'Conception aérodynamique pour haute altitude')),
((SELECT id FROM airplanes WHERE name = 'SR-71 Blackbird'), (SELECT id FROM tech WHERE name = 'Matériaux résistants à la chaleur')),
((SELECT id FROM airplanes WHERE name = 'SR-71 Blackbird'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle')),
((SELECT id FROM airplanes WHERE name = 'SR-71 Blackbird'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'SR-71 Blackbird'), (SELECT id FROM tech WHERE name = 'Conception furtive'));

-- Insertion des armements
-- Le SR-71 n'était pas armé, donc pas d'insertion dans airplane_armement
-- Il était équipé de capteurs de reconnaissance (caméras, radars, etc.), mais ce ne sont pas des "armements" dans votre base.

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'SR-71 Blackbird'), (SELECT id FROM wars WHERE name = 'Guerre froide')),
((SELECT id FROM airplanes WHERE name = 'SR-71 Blackbird'), (SELECT id FROM wars WHERE name = 'Guerre du Vietnam'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'SR-71 Blackbird'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'SR-71 Blackbird'), (SELECT id FROM missions WHERE name = 'Guerre électronique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 32.74, wingspan = 16.94, height = 5.64, wing_area = 170.0,
  empty_weight = 27215, mtow = 78000, service_ceiling = 25900, climb_rate = NULL,
  combat_radius = 3200, crew = 2, g_limit_pos = 5.0,
  engine_name = 'Pratt & Whitney J58', engine_count = 2,
  engine_type = 'Turboréacteur à double flux hybride', engine_type_en = 'Hybrid turbo-ramjet',
  thrust_dry = 140.0, thrust_wet = 151.0,
  production_start = 1964, production_end = 1968, units_built = 32,
  operators_count = 1,
  nickname = 'Blackbird',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Lockheed_SR-71_Blackbird',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Lockheed_SR-71_Blackbird'
WHERE name = 'SR-71 Blackbird';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 34000000, unit_cost_year = 1966
WHERE name = 'SR-71 Blackbird';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nProgramme top-secret développé par le **Skunk Works** de Lockheed dans les années 1960, successeur du U-2. Conçu pour voler à Mach 3+ à 25 000 m d''altitude, là où aucun missile soviétique ne pouvait l''intercepter.\n\n## Carrière opérationnelle\nMissions de reconnaissance stratégique durant toute la guerre froide : URSS, Cuba, Vietnam, Moyen-Orient, Corée. Titulaire du **record mondial de vitesse** pour un avion à propulsion aérobique (Mach 3.32, 1976). Jamais abattu malgré 800+ tentatives d''interception.\n\n## Héritage\nRetiré en 1999. **Aucun successeur n''a jamais égalé ses performances**. Remplacé fonctionnellement par les satellites et les drones. Le SR-72 hypersonique reste à l''état de projet.',
  description_en = E'## Genesis\nTop-secret programme developed by Lockheed''s **Skunk Works** in the 1960s, successor to the U-2. Designed to fly at Mach 3+ at 25,000 m altitude, where no Soviet missile could intercept it.\n\n## Operational career\nStrategic reconnaissance missions throughout the Cold War: USSR, Cuba, Vietnam, Middle East, Korea. Holder of the **world speed record** for an air-breathing aircraft (Mach 3.32, 1976). Never shot down despite 800+ interception attempts.\n\n## Legacy\nRetired in 1999. **No successor has ever matched its performance**. Functionally replaced by satellites and drones. The hypersonic SR-72 remains a concept.'
WHERE name = 'SR-71 Blackbird';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=vpVT5Lr0BbI'
WHERE name = 'SR-71 Blackbird';
