-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Su-15',
    'Su-15',
    'Sukhoi Su-15 Flagon',
    'Sukhoi Su-15 Flagon',
    'Intercepteur soviétique de 2e génération',
    'Soviet 2nd-generation interceptor',
    '/assets/airplanes/su15.jpg',
    'Le Sukhoi Su-15 Flagon est un avion intercepteur supersonique développé pour les forces aériennes soviétiques. Classé dans la 2e génération, il est conçu pour contrer les bombardiers à haute altitude et les avions espions pendant la Guerre froide, avec une capacité tous temps grâce à son radar. Utilisé principalement pour la défense aérienne, il a été impliqué dans des incidents célèbres comme l''interception du vol KAL 007.',
    'The Sukhoi Su-15 Flagon is a supersonic interceptor aircraft developed for the Soviet air forces. Classified as 2nd generation, it is designed to counter high-altitude bombers and spy planes during the Cold War, with all-weather capability thanks to its radar. Used mainly for air defense, it was involved in famous incidents such as the interception of KAL 007 flight.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1962-01-01',
    '1965-05-30',
    '1967-04-01',
    2230.0,
    1550.0,
    (SELECT id FROM manufacturer WHERE code = 'SUK'),
    (SELECT id FROM generation WHERE generation = 2),
    (SELECT id FROM type WHERE name = 'Intercepteur'),
    'Retiré',
    NULL,
    10675.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM tech WHERE name = 'Aile delta')),
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM tech WHERE name = 'Radar RP-15')),
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM tech WHERE name = 'Moteurs Tumansky R-11')),
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM armement WHERE name = 'R-60')),
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM armement WHERE name = 'R-23R')),
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM armement WHERE name = 'R-23T'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM wars WHERE name = 'Guerre froide'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Su-15'), (SELECT id FROM missions WHERE name = 'Patrouille aérienne de combat'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 22.07, wingspan = 9.34, height = 4.84, wing_area = 36.0,
  empty_weight = 10874, mtow = 19100, service_ceiling = 18500, climb_rate = 175,
  combat_radius = 700, crew = 1,
  engine_name = 'Tumansky R-11F2S-300', engine_count = 2,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 36.78, thrust_wet = 59.75,
  production_start = 1966, production_end = 1981, units_built = 1290,
  operators_count = 3,
  nickname = 'Flagon',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Soukho%C3%AF_Su-15',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Sukhoi_Su-15'
WHERE name = 'Su-15';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 5000000, unit_cost_year = 1975,
  variants    = E'- **Su-15TM** : version de série principale (radar Taifun-M)\n- **Su-15UM** : biplace d''entraînement'
WHERE name = 'Su-15';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nIntercepteur longue portée soviétique des années 1960, développé pour protéger les centres urbains. Aile delta, double réacteur, radar **Taifun** à balayage mécanique. Production soviétique uniquement — jamais exporté.\n\n## Carrière opérationnelle\nTristement célèbre pour avoir abattu par erreur le **vol coréen KAL 007** en 1983 (269 morts) — incident diplomatique majeur de la guerre froide. Également responsable de la destruction d''un Grumman G-222 italien en 1988.\n\n## Héritage\nRetiré en 1996. Sa brutalité d''utilisation et sa priorité absolue de l''interception en faisaient un symbole controversé de la doctrine **PVO Strany** (défense aérienne territoriale).',
  description_en = E'## Genesis\nSoviet long-range interceptor of the 1960s, developed to protect urban centres. Delta wing, twin engines, **Taifun** mechanically-scanned radar. Soviet production only — never exported.\n\n## Operational career\nInfamously known for shooting down **Korean Air Lines Flight 007** by mistake in 1983 (269 killed) — a major Cold War diplomatic incident. Also responsible for destroying an Italian Grumman G-222 in 1988.\n\n## Legacy\nRetired in 1996. Its brutal use and absolute priority on interception made it a controversial symbol of the **PVO Strany** (territorial air defence) doctrine.'
WHERE name = 'Su-15';

-- [auto:008] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  variants_en = E'- **Su-15TM** : main production variant (Taifun-M radar)\n- **Su-15UM** : two-seat trainer'
WHERE name = 'Su-15';
