-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Su-17',
    'Su-17',
    'Sukhoi Su-17 Fitter',
    'Sukhoi Su-17 Fitter',
    'Chasseur-bombardier soviétique de 3e génération',
    'Soviet 3rd-generation fighter-bomber',
    '/assets/airplanes/su17.jpg',
    'Le Sukhoi Su-17 Fitter est un chasseur-bombardier à géométrie variable développé pour les forces aériennes soviétiques. Classé dans la 3e génération, il est une évolution du Su-7, conçu pour des missions d''attaque au sol et d''appui aérien rapproché avec une capacité de supériorité aérienne limitée. Largement exporté, il a été utilisé dans plusieurs conflits au Moyen-Orient et en Afghanistan.',
    'The Sukhoi Su-17 Fitter is a variable-geometry fighter-bomber developed for the Soviet air forces. Classified as 3rd generation, it is an evolution of the Su-7, designed for ground attack and close air support missions with limited air superiority capability. Widely exported, it has been used in several conflicts in the Middle East and Afghanistan.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1964-01-01',
    '1966-08-02',
    '1970-01-01',
    2230.0,
    2300.0,
    (SELECT id FROM manufacturer WHERE code = 'SUK'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Appui aérien'),
    'Retiré',
    NULL,
    12000.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM tech WHERE name = 'Aile à géométrie variable')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM tech WHERE name = 'Radar Klen')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM armement WHERE name = 'GSh-30-2')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM armement WHERE name = 'Kh-23')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM armement WHERE name = 'FAB-500')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM armement WHERE name = 'S-5')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM armement WHERE name = 'R-60'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM missions WHERE name = 'Suppression des défenses aériennes ennemies')),
((SELECT id FROM airplanes WHERE name = 'Su-17'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 18.75, wingspan = 13.68, height = 5.12, wing_area = 38.5,
  empty_weight = 10767, mtow = 19500, service_ceiling = 16350, climb_rate = 230,
  combat_radius = 1150, crew = 1, g_limit_pos = 7.0,
  engine_name = 'Lyulka AL-21F-3', engine_count = 1,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 76.5, thrust_wet = 110.0,
  production_start = 1969, production_end = 1990, units_built = 2867,
  operators_count = 16,
  nickname = 'Fitter',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Soukho%C3%AF_Su-17',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Sukhoi_Su-17'
WHERE name = 'Su-17';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 5000000, unit_cost_year = 1975,
  variants    = E'- **Su-17M2/M3/M4** : évolutions successives soviétiques\n- **Su-20** : version export dégradée (Pacte de Varsovie)\n- **Su-22** : version export Atar (Pérou, Égypte, Libye, Syrie)',
  variants_en = E'- **Su-17M2/M3/M4** : successive Soviet upgrades\n- **Su-20** : degraded Warsaw Pact export\n- **Su-22** : Atar-engined export (Peru, Egypt, Libya, Syria)'
WHERE name = 'Su-17';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nDéveloppé dans les années 1960 par Soukhoï comme chasseur-bombardier à **aile à géométrie variable** (variante du Su-7). Plusieurs versions export : Su-20 (Pacte de Varsovie dégradé), Su-22 (export mondial avec moteur Atar).\n\n## Carrière opérationnelle\nEngagé en Afghanistan (guerre soviétique 1979-1989), en Iran-Irak, en Érythrée-Éthiopie, au Soudan, au Yémen. Un des rares avions à avoir servi dans plus de **15 armées différentes**.\n\n## Héritage\nRetiré de Russie en 1998, toujours en service en Syrie, Libye, Vietnam, Pérou, Angola. **Plus de 2 800 exemplaires** produits — un succès quantitatif majeur.',
  description_en = E'## Genesis\nDeveloped in the 1960s by Sukhoi as a fighter-bomber with **variable-sweep wings** (a Su-7 derivative). Several export variants: Su-20 (degraded Warsaw Pact), Su-22 (worldwide export with Atar engine).\n\n## Operational career\nUsed in Afghanistan (Soviet war 1979-1989), Iran-Iraq, Eritrea-Ethiopia, Sudan, Yemen. One of the few aircraft to have served in more than **15 different air forces**.\n\n## Legacy\nRetired by Russia in 1998, still in service in Syria, Libya, Vietnam, Peru, Angola. **More than 2,800 built** — a major quantitative success.'
WHERE name = 'Su-17';
