-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Su-24',
    'Su-24',
    'Sukhoi Su-24 Fencer',
    'Sukhoi Su-24 Fencer',
    'Chasseur-bombardier soviétique/russe de 3e génération',
    'Soviet/Russian 3rd-generation fighter-bomber',
    '/assets/airplanes/su24.jpg',
    'Le Sukhoi Su-24 Fencer est un chasseur-bombardier à géométrie variable développé pour les forces aériennes soviétiques, puis russes. Classé dans la 3e génération, il est conçu pour des missions de frappe tactique et stratégique à basse altitude, avec une capacité tous temps grâce à son radar de suivi de terrain. Utilisé dans de nombreux conflits, il reste un pilier des opérations air-sol russes.',
    'The Sukhoi Su-24 Fencer is a variable-geometry fighter-bomber developed for the Soviet and later Russian air forces. Classified as 3rd generation, it is designed for tactical and strategic strike missions at low altitude, with all-weather capability thanks to its terrain-following radar. Used in many conflicts, it remains a pillar of Russian air-to-ground operations.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1965-01-01',
    '1970-01-17',
    '1974-02-01',
    2320.0,
    2775.0,
    (SELECT id FROM manufacturer WHERE code = 'SUK'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Bombardier'),
    'Actif',
    'Active',
    22320.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM tech WHERE name = 'Aile à géométrie variable')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM tech WHERE name = 'Radar Puma')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM armement WHERE name = 'GSh-6-23')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM armement WHERE name = 'Kh-25ML')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM armement WHERE name = 'Kh-29L')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM armement WHERE name = 'FAB-500')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM armement WHERE name = 'S-8'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM missions WHERE name = 'Suppression des défenses aériennes ennemies')),
((SELECT id FROM airplanes WHERE name = 'Su-24'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 22.67, wingspan = 17.64, height = 6.19, wing_area = 55.2,
  empty_weight = 22300, mtow = 43755, service_ceiling = 11000, climb_rate = 150,
  combat_radius = 615, crew = 2, g_limit_pos = 6.0,
  engine_name = 'Saturn AL-21F-3A', engine_count = 2,
  engine_type = 'Turboréacteur avec postcombustion', engine_type_en = 'Afterburning turbojet',
  thrust_dry = 76.5, thrust_wet = 110.0,
  production_start = 1971, production_end = 1993, units_built = 1400,
  operators_count = 4,
  nickname = 'Fencer',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Soukho%C3%AF_Su-24',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Sukhoi_Su-24'
WHERE name = 'Su-24';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 10000000, unit_cost_year = 1985,
  variants    = E'- **Su-24M** : version de série principale (avionique PNK Puma)\n- **Su-24MR** : reconnaissance tactique\n- **Su-24MP** : guerre électronique\n- **Su-24M2** : modernisation profonde (avionique numérique)',
  variants_en = E'- **Su-24M** : main production variant (PNK Puma avionics)\n- **Su-24MR** : tactical reconnaissance\n- **Su-24MP** : electronic warfare\n- **Su-24M2** : deep upgrade (digital avionics)'
WHERE name = 'Su-24';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nÉquivalent soviétique du **F-111 Aardvark** américain, développé dans les années 1970 comme chasseur-bombardier tout temps à aile à géométrie variable. Biplace côte à côte (pilote + navigateur système).\n\n## Carrière opérationnelle\nEngagé en Afghanistan (1979-1989), en Tchétchénie (1994-1996, 1999-2000), en Géorgie (2008), en Syrie (depuis 2015), en Ukraine (2022+). Spécialisé dans la **frappe de précision tous temps**, y compris nucléaire tactique.\n\n## Héritage\nModernisé en Su-24M2. Progressivement remplacé par le Su-34 russe à partir des années 2000, mais encore en service en Russie, Ukraine, Syrie, Algérie, Iran.',
  description_en = E'## Genesis\nSoviet equivalent of the US **F-111 Aardvark**, developed in the 1970s as an all-weather variable-sweep-wing fighter-bomber. Side-by-side two-seater (pilot + weapon system officer).\n\n## Operational career\nUsed in Afghanistan (1979-1989), Chechnya (1994-1996, 1999-2000), Georgia (2008), Syria (since 2015), Ukraine (2022+). Specialised in **all-weather precision strike**, including tactical nuclear.\n\n## Legacy\nUpgraded to Su-24M2. Gradually replaced by the Russian Su-34 from the 2000s, but still in service in Russia, Ukraine, Syria, Algeria, Iran.'
WHERE name = 'Su-24';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=jklGQxAOoo8'
WHERE name = 'Su-24';
