-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Su-25',
    'Su-25',
    'Sukhoi Su-25 Frogfoot',
    'Sukhoi Su-25 Frogfoot',
    'Avion d''appui aérien rapproché soviétique/russe de 3e génération',
    'Soviet/Russian 3rd-generation close air support aircraft',
    '/assets/airplanes/su25.jpg',
    'Le Sukhoi Su-25 Frogfoot est un avion d''appui aérien rapproché développé pour les forces aériennes soviétiques, puis russes. Classé dans la 3e génération, il est conçu pour fournir un soutien direct aux troupes au sol avec une robustesse exceptionnelle et une forte capacité d''armement. Surnommé le "char volant", il a été largement utilisé dans des conflits comme l''Afghanistan et reste en service dans plusieurs pays.',
    'The Sukhoi Su-25 Frogfoot is a close air support aircraft developed for the Soviet and later Russian air forces. Classified as 3rd generation, it is designed to provide direct support to ground troops with exceptional ruggedness and strong weapon capacity. Nicknamed the "flying tank", it has been widely used in conflicts such as Afghanistan and remains in service in several countries.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1972-01-01',
    '1975-02-22',
    '1981-07-01',
    975.0,
    1850.0,
    (SELECT id FROM manufacturer WHERE code = 'SUK'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Appui aérien'),
    'Actif',
    'Active',
    9500.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM tech WHERE name = 'Blindage en titane')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM tech WHERE name = 'Canon GSh-30-2')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM armement WHERE name = 'GSh-30-2')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM armement WHERE name = 'Kh-25ML')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM armement WHERE name = 'FAB-500')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM armement WHERE name = 'S-8')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM armement WHERE name = 'S-25'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM wars WHERE name = 'Guerre Iran-Irak'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM missions WHERE name = 'Suppression des défenses aériennes ennemies')),
((SELECT id FROM airplanes WHERE name = 'Su-25'), (SELECT id FROM missions WHERE name = 'Reconnaissance armée'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 15.33, wingspan = 14.36, height = 4.80, wing_area = 33.7,
  empty_weight = 9800, mtow = 17600, service_ceiling = 7000, climb_rate = 60,
  combat_radius = 375, crew = 1, g_limit_pos = 6.5,
  engine_name = 'Soyuz/Tumansky R-195', engine_count = 2,
  engine_type = 'Turboréacteur', engine_type_en = 'Turbojet',
  thrust_dry = 44.18,
  production_start = 1978, production_end = NULL, units_built = 1024,
  operators_count = 15,
  nickname = 'Frogfoot',
  rival_id = (SELECT id FROM airplanes WHERE name = 'A-10 Thunderbolt II' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Soukho%C3%AF_Su-25',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Sukhoi_Su-25'
WHERE name = 'Su-25';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 11000000, unit_cost_year = 2010,
  variants    = E'- **Su-25** : version initiale série\n- **Su-25UB/UBK** : biplaces d''entraînement\n- **Su-25T/TM (Su-39)** : attaque antichar avancée\n- **Su-25SM/SM3** : modernisation russe (avionique, GLONASS)',
  variants_en = E'- **Su-25** : initial series\n- **Su-25UB/UBK** : two-seat trainers\n- **Su-25T/TM (Su-39)** : advanced anti-tank variant\n- **Su-25SM/SM3** : Russian modernisation (avionics, GLONASS)'
WHERE name = 'Su-25';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nÉquivalent soviétique de l''**A-10 américain**, développé dans les années 1970 pour l''appui aérien rapproché. Blindé (cockpit en titane), deux moteurs de secours, canon GSh-30-2 de 30 mm. Pas de postcombustion — optimisé basse altitude.\n\n## Carrière opérationnelle\nBaptême du feu en **Afghanistan** (1981-1989), où il s''illustre face aux moudjahidines. Engagé en Tchétchénie, Géorgie, Ukraine. Exporté en Irak, Iran, Corée du Nord, Angola, Soudan, Pérou.\n\n## Héritage\nToujours en production (Su-25SM3 modernisé). Plus de **1 000 exemplaires** construits. Symbole de la puissance de feu au sol soviétique.',
  description_en = E'## Genesis\nSoviet equivalent of the US **A-10**, developed in the 1970s for close air support. Armoured (titanium cockpit), twin redundant engines, 30 mm GSh-30-2 cannon. No afterburner — optimised for low altitude.\n\n## Operational career\nCombat debut in **Afghanistan** (1981-1989), where it proved itself against the mujahideen. Used in Chechnya, Georgia, Ukraine. Exported to Iraq, Iran, North Korea, Angola, Sudan, Peru.\n\n## Legacy\nStill in production (upgraded Su-25SM3). More than **1,000 built**. Symbol of Soviet ground firepower.'
WHERE name = 'Su-25';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=t6qlOg3niIc'
WHERE name = 'Su-25';
