-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Su-27',
    'Su-27',
    'Sukhoi Su-27 Flanker',
    'Sukhoi Su-27 Flanker',
    'Chasseur multirôle soviétique/russe de 4e génération',
    'Soviet/Russian 4th-generation multirole fighter',
    '/assets/airplanes/su27.jpg',
    'Le Sukhoi Su-27 Flanker est un avion de chasse multirôle développé pour les forces aériennes soviétiques, puis russes. Classé dans la 4e génération, il est conçu pour la supériorité aérienne avec une maniabilité exceptionnelle et une capacité de frappe au sol secondaire. Rival direct des chasseurs occidentaux comme le F-15, il a été largement exporté et a servi de base à de nombreuses variantes modernes.',
    'The Sukhoi Su-27 Flanker is a multirole fighter aircraft developed for the Soviet and later Russian air forces. Classified as 4th generation, it is designed for air superiority with exceptional maneuverability and secondary ground strike capability. Direct rival of Western fighters such as the F-15, it has been widely exported and has served as the basis for numerous modern variants.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1974-01-01',
    '1977-05-20',
    '1982-06-20',
    2500.0,
    3530.0,
    (SELECT id FROM manufacturer WHERE code = 'SUK'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Chasseur'),
    'Actif',
    'Active',
    16400.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM tech WHERE name = 'Aile à forte flèche')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM tech WHERE name = 'Radar N001')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM tech WHERE name = 'Système de contrôle de vol numérique')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM tech WHERE name = 'Système de fusion de capteurs'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM armement WHERE name = 'GSh-30-1')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM armement WHERE name = 'R-27R')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM armement WHERE name = 'R-73')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM armement WHERE name = 'R-77')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM armement WHERE name = 'FAB-500'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM wars WHERE name = 'Guerre froide')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM missions WHERE name = 'Patrouille aérienne de combat')),
((SELECT id FROM airplanes WHERE name = 'Su-27'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 21.94, wingspan = 14.70, height = 5.93, wing_area = 62.0,
  empty_weight = 16380, mtow = 33000, service_ceiling = 18500, climb_rate = 325,
  combat_radius = 1500, crew = 1, g_limit_pos = 9.0,
  engine_name = 'Saturn AL-31F', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 74.5, thrust_wet = 122.6,
  production_start = 1981, production_end = NULL, units_built = 809,
  operators_count = 9,
  nickname = 'Flanker',
  successor_id = (SELECT id FROM airplanes WHERE name = 'Su-35' LIMIT 1),
  rival_id = (SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Soukho%C3%AF_Su-27',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Sukhoi_Su-27'
WHERE name = 'Su-27';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 30000000, unit_cost_year = 1990,
  manufacturer_page = 'https://www.sukhoi.org/eng/',
  variants    = E'- **Su-27P/S** : monoplace intercepteur\n- **Su-27UB** : biplace d''entraînement\n- **Su-27SM/SM3** : modernisations russes successives\n- **Su-27SK / Su-27SKM** : export Chine (dérive vers J-11)',
  variants_en = E'- **Su-27P/S** : single-seat interceptor\n- **Su-27UB** : two-seat trainer\n- **Su-27SM/SM3** : Russian upgrade series\n- **Su-27SK / Su-27SKM** : Chinese export (led to J-11)'
WHERE name = 'Su-27';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nChasseur de supériorité aérienne développé par Soukhoï dans les années 1970-80 comme équivalent du F-15 américain. Base technologique de toute la famille russe moderne (Su-30, Su-33, Su-34, Su-35, Su-57).\n\n## Carrière opérationnelle\nPilier de la défense aérienne soviétique puis russe. Engagé en Abkhazie (1992-1993), en Érythrée-Éthiopie, en Géorgie (2008), en Syrie (2015+), en Ukraine (2022+). Adopté massivement par la Chine (licence pour le J-11).\n\n## Héritage\nPlus de **800 exemplaires** produits + 500 copies chinoises. Rival du F-15 sur le marché export (Inde, Chine, Vietnam, Éthiopie, Indonésie). Successeur : le **Su-35** modernisé.',
  description_en = E'## Genesis\nAir-superiority fighter developed by Sukhoi in the 1970s-80s as the equivalent of the US F-15. Technology base for the entire modern Russian family (Su-30, Su-33, Su-34, Su-35, Su-57).\n\n## Operational career\nBackbone of Soviet then Russian air defence. Used in Abkhazia (1992-1993), Eritrea-Ethiopia, Georgia (2008), Syria (2015+), Ukraine (2022+). Massively adopted by China (license for the J-11).\n\n## Legacy\nMore than **800 built** + 500 Chinese copies. Rival of the F-15 on export markets (India, China, Vietnam, Ethiopia, Indonesia). Successor: the upgraded **Su-35**.'
WHERE name = 'Su-27';

-- [auto:010] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = NULL WHERE name = 'Su-27';
