-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Su-30',
    'Su-30',
    'Sukhoi Su-30 Flanker-C',
    'Sukhoi Su-30 Flanker-C',
    'Chasseur multirôle russe de 4e génération avancée',
    'Advanced Russian 4th-generation multirole fighter',
    '/assets/airplanes/su30.jpg',
    'Le Sukhoi Su-30 Flanker-C est un chasseur multirôle biplace dérivé du Su-27, développé pour les forces aériennes russes. Classé dans la 4e génération avancée (souvent appelée 4++), il excelle dans la supériorité aérienne et les frappes au sol grâce à sa maniabilité, son radar avancé et sa capacité de ravitaillement en vol. Largement exporté, il est utilisé dans des conflits modernes et est un pilier des forces aériennes russes.',
    'The Sukhoi Su-30 Flanker-C is a twin-seat multirole fighter derived from the Su-27, developed for the Russian air forces. Classified as advanced 4th generation (often called 4++), it excels in air superiority and ground strikes thanks to its maneuverability, advanced radar and aerial refueling capability. Widely exported, it is used in modern conflicts and is a pillar of the Russian air forces.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1986-01-01',
    '1989-12-31',
    '1992-04-01',
    2120.0,
    3000.0,
    (SELECT id FROM manufacturer WHERE code = 'SUK'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Actif',
    'Active',
    17700.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM tech WHERE name = 'Aile à forte flèche')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM tech WHERE name = 'Radar N011M Bars')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM tech WHERE name = 'Système de ravitaillement en vol')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM tech WHERE name = 'Système de contrôle de vol numérique')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM tech WHERE name = 'Système de fusion de capteurs'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM armement WHERE name = 'GSh-30-1')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM armement WHERE name = 'R-27R')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM armement WHERE name = 'R-73')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM armement WHERE name = 'R-77')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM armement WHERE name = 'Kh-29L'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM missions WHERE name = 'Patrouille aérienne de combat')),
((SELECT id FROM airplanes WHERE name = 'Su-30'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 21.94, wingspan = 14.70, height = 6.36, wing_area = 62.0,
  empty_weight = 18400, mtow = 38800, service_ceiling = 17300, climb_rate = 230,
  combat_radius = 1500, crew = 2, g_limit_pos = 9.0,
  engine_name = 'Saturn AL-31FP', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion et poussée vectorielle', engine_type_en = 'Thrust-vectoring afterburning turbofan',
  thrust_dry = 74.5, thrust_wet = 122.6,
  production_start = 1994, production_end = NULL, units_built = 630,
  operators_count = 10,
  nickname = 'Flanker-C',
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'Su-27' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Soukho%C3%AF_Su-30',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Sukhoi_Su-30'
WHERE name = 'Su-30';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 50000000, unit_cost_year = 2018,
  manufacturer_page = 'https://www.sukhoi.org/eng/',
  variants    = E'- **Su-30MK** : version export initiale\n- **Su-30MKK** : export Chine\n- **Su-30MKI** : export Inde (canards, AL-31FP vectoriel)\n- **Su-30SM** : version russe moderne\n- **Su-30MKM/MKA/MKV** : Malaisie, Algérie, Venezuela',
  variants_en = E'- **Su-30MK** : initial export\n- **Su-30MKK** : Chinese export\n- **Su-30MKI** : Indian export (canards, thrust-vectoring AL-31FP)\n- **Su-30SM** : modern Russian version\n- **Su-30MKM/MKA/MKV** : Malaysia, Algeria, Venezuela'
WHERE name = 'Su-30';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nÉvolution biplace multi-rôle du Su-27 développée dans les années 1990-2000. Plusieurs variantes d''export nommées selon le client : **MKK** (Chine), **MKI** (Inde, avec canards et poussée vectorielle), **MKM** (Malaisie), **SM** (Russie).\n\n## Carrière opérationnelle\nChasseur principal de l''Indian Air Force (272 ex. MKI), de la Chine, du Vietnam, d''Algérie, Venezuela, Ouganda. Engagé en Syrie (Russie), en Ukraine (Russie, 2022+). Grand succès à l''export russe des années 2000.\n\n## Héritage\nProduit à **600+ exemplaires**. L''équivalent fonctionnel russe du F-15E américain. Son succès a financé la base industrielle russe d''aviation de combat pendant la décennie de crise post-soviétique.',
  description_en = E'## Genesis\nTwo-seat multi-role evolution of the Su-27 developed in the 1990s-2000s. Several export variants named after the customer: **MKK** (China), **MKI** (India, with canards and thrust vectoring), **MKM** (Malaysia), **SM** (Russia).\n\n## Operational career\nMain fighter of the Indian Air Force (272 MKI), China, Vietnam, Algeria, Venezuela, Uganda. Used in Syria (Russia), in Ukraine (Russia, 2022+). Major Russian export success in the 2000s.\n\n## Legacy\nProduced to **600+ airframes**. The Russian functional counterpart of the US F-15E. Its success funded the Russian combat-aviation industrial base through the post-Soviet crisis decade.'
WHERE name = 'Su-30';

-- [auto:010] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = NULL WHERE name = 'Su-30';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=gNx6DV8EcF8'
WHERE name = 'Su-30';
