-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Su-34',
    'Su-34',
    'Sukhoi Su-34 Fullback',
    'Sukhoi Su-34 Fullback',
    'Chasseur-bombardier russe de 4e génération avancée',
    'Advanced Russian 4th-generation fighter-bomber',
    '/assets/airplanes/su34.jpg',
    'Le Sukhoi Su-34 Fullback est un chasseur-bombardier biplace dérivé du Su-27, développé pour les forces aériennes russes. Classé dans la 4e génération avancée (souvent appelée 4++), il est conçu pour des missions de frappe tactique et stratégique avec une capacité tous temps et une grande précision. Équipé d’un poste de pilotage côte à côte, il est utilisé dans des conflits modernes comme la guerre en Syrie.',
    'The Sukhoi Su-34 Fullback is a twin-seat fighter-bomber derived from the Su-27, developed for the Russian air forces. Classified as advanced 4th generation (often called 4++), it is designed for tactical and strategic strike missions with all-weather capability and high precision. Equipped with a side-by-side cockpit, it has been used in modern conflicts such as the war in Syria.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1986-01-01',
    '1990-04-13',
    '2014-03-20',
    1900.0,
    4000.0,
    (SELECT id FROM manufacturer WHERE code = 'SUK'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Bombardier'),
    'Actif',
    'Active',
    22500.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM tech WHERE name = 'Poste de pilotage côte à côte')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM tech WHERE name = 'Radar V004')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM armement WHERE name = 'GSh-30-1')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM armement WHERE name = 'Kh-29L')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM armement WHERE name = 'Kh-59')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM armement WHERE name = 'FAB-500')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM armement WHERE name = 'KAB-500L'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM missions WHERE name = 'Suppression des défenses aériennes ennemies')),
((SELECT id FROM airplanes WHERE name = 'Su-34'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 23.34, wingspan = 14.70, height = 6.09, wing_area = 62.0,
  empty_weight = 22500, mtow = 45100, service_ceiling = 14650, climb_rate = NULL,
  combat_radius = 1100, crew = 2, g_limit_pos = 7.0,
  engine_name = 'Saturn AL-31F-M1', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 74.5, thrust_wet = 122.6,
  production_start = 2006, production_end = NULL, units_built = 150,
  operators_count = 1,
  nickname = 'Fullback',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Soukho%C3%AF_Su-34',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Sukhoi_Su-34'
WHERE name = 'Su-34';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 36000000, unit_cost_year = 2015,
  manufacturer_page = 'https://www.sukhoi.org/eng/'
WHERE name = 'Su-34';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nChasseur-bombardier lourd développé dans les années 1990-2000 par Soukhoï, héritier du Su-24. Cockpit blindé côte à côte, grande autonomie, capacité d''emport massive. Classé par l''OTAN comme **« Fullback »**.\n\n## Carrière opérationnelle\nEngagé en Géorgie (2008), en Syrie (depuis 2015), en Ukraine (2022+). Rôle central dans la doctrine russe de frappe conventionnelle de précision. Plusieurs pertes en Ukraine face aux défenses anti-aériennes occidentales.\n\n## Héritage\nProduction en cours (150+ exemplaires). Remplace progressivement les Su-24 de l''aviation tactique russe. Seule nation utilisatrice : la Russie.',
  description_en = E'## Genesis\nHeavy fighter-bomber developed in the 1990s-2000s by Sukhoi, heir to the Su-24. Armoured side-by-side cockpit, long range, massive payload. NATO reporting name: **"Fullback"**.\n\n## Operational career\nUsed in Georgia (2008), Syria (since 2015), Ukraine (2022+). Central role in the Russian doctrine of conventional precision strike. Several losses in Ukraine against Western air defences.\n\n## Legacy\nProduction ongoing (150+ airframes). Progressively replaces the Russian tactical Su-24. Only operator: Russia.'
WHERE name = 'Su-34';

-- [auto:010] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = NULL WHERE name = 'Su-34';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=xIHrT4o_yeI'
WHERE name = 'Su-34';
