-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Su-35',
    'Su-35',
    'Sukhoi Su-35 Flanker-E',
    'Sukhoi Su-35 Flanker-E',
    'Chasseur multirôle russe de 4e génération avancée',
    'Advanced Russian 4th-generation multirole fighter',
    '/assets/airplanes/su35.jpg',
    'Le Sukhoi Su-35 Flanker-E est une version modernisée du Su-27, classée comme un chasseur multirôle de 4e génération avancée (souvent appelée 4++). Développé par Sukhoi, il excelle dans la supériorité aérienne et les frappes au sol grâce à ses moteurs à poussée vectorielle, son radar avancé et sa maniabilité exceptionnelle. Utilisé par les forces aériennes russes, il a été déployé dans des conflits récents.',
    'The Sukhoi Su-35 Flanker-E is a modernized version of the Su-27, classified as an advanced 4th-generation multirole fighter (often called 4++). Developed by Sukhoi, it excels in air superiority and ground strikes thanks to its thrust-vectoring engines, advanced radar and exceptional maneuverability. Used by the Russian air forces, it has been deployed in recent conflicts.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '2005-01-01',
    '2008-02-19',
    '2014-02-12',
    2500.0,
    3600.0,
    (SELECT id FROM manufacturer WHERE code = 'SUK'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Actif',
    'Active',
    19000.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM tech WHERE name = 'Aile à forte flèche')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM tech WHERE name = 'Radar Irbis-E')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM tech WHERE name = 'Système de contrôle de vol numérique')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM tech WHERE name = 'Moteurs à poussée vectorielle')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM tech WHERE name = 'Système de fusion de capteurs'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM armement WHERE name = 'GSh-30-1')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM armement WHERE name = 'R-73')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM armement WHERE name = 'R-77')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM armement WHERE name = 'Kh-29L')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM armement WHERE name = 'KAB-500L'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM missions WHERE name = 'Interception')),
((SELECT id FROM airplanes WHERE name = 'Su-35'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 21.9, wingspan = 15.3, height = 5.90, wing_area = 62.0,
  empty_weight = 19000, mtow = 34500, service_ceiling = 18000, climb_rate = 280,
  combat_radius = 1580, crew = 1, g_limit_pos = 9.0,
  engine_name = 'Saturn AL-41F1S (117S)', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion et poussée vectorielle', engine_type_en = 'Thrust-vectoring afterburning turbofan',
  thrust_dry = 86.3, thrust_wet = 142.0,
  production_start = 2007, production_end = NULL, units_built = 180,
  operators_count = 3,
  nickname = 'Flanker-E',
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'Su-27' LIMIT 1),
  rival_id = (SELECT id FROM airplanes WHERE name = 'F-15E Strike Eagle' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Soukho%C3%AF_Su-35',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Sukhoi_Su-35'
WHERE name = 'Su-35';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 65000000, unit_cost_year = 2020,
  manufacturer_page = 'https://www.sukhoi.org/eng/'
WHERE name = 'Su-35';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nVersion ultra-modernisée du Su-27 développée dans les années 2000. Radar PESA **Irbis-E** très longue portée (400 km), moteurs **AL-41F1S** à poussée vectorielle bi-axiale, avionique numérique complète.\n\n## Carrière opérationnelle\nEngagé en Syrie (depuis 2016) et en Ukraine (2022+). Plusieurs pertes en combat aérien face aux F-15/F-16 ukrainiens modernisés et aux défenses sol-air. Exporté en Chine, Égypte, Iran.\n\n## Héritage\nChasseur le plus capable de la Russie avant l''arrivée du Su-57. Considéré comme un **« 4++ génération »** compétitif face aux F-15EX, F-16V, Rafale et Eurofighter.',
  description_en = E'## Genesis\nUltra-modernised Su-27 variant developed in the 2000s. Very-long-range **Irbis-E** PESA radar (400 km), **AL-41F1S** engines with two-axis thrust vectoring, fully digital avionics.\n\n## Operational career\nUsed in Syria (since 2016) and Ukraine (2022+). Several air-combat losses against upgraded Ukrainian F-15/F-16s and surface-to-air defences. Exported to China, Egypt, Iran.\n\n## Legacy\nThe most capable Russian fighter before the arrival of the Su-57. Considered a **"4++ generation"** competitor to the F-15EX, F-16V, Rafale and Eurofighter.'
WHERE name = 'Su-35';

-- [auto:010] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = NULL WHERE name = 'Su-35';
