-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Su-57',
    'Su-57',
    'Sukhoi Su-57 Felon',
    'Sukhoi Su-57 Felon',
    'Chasseur furtif russe de 5e génération',
    'Russian 5th-generation stealth fighter',
    '/assets/airplanes/su57.jpg',
    'Le Sukhoi Su-57 Felon est un avion de chasse multirôle furtif développé par Sukhoi pour les forces aériennes russes. Classé dans la 5e génération, il est conçu pour la supériorité aérienne et les frappes au sol, avec une furtivité avancée, des capteurs intégrés et une supercroisière. Premier avion furtif russe opérationnel, il vise à concurrencer les chasseurs américains comme le F-22 et le F-35.',
    'The Sukhoi Su-57 Felon is a stealth multirole fighter aircraft developed by Sukhoi for the Russian air forces. Classified as 5th generation, it is designed for air superiority and ground strikes, with advanced stealth, integrated sensors and supercruise. The first operational Russian stealth aircraft, it aims to compete with American fighters such as the F-22 and F-35.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '2002-01-01',
    '2010-01-29',
    '2020-12-25',
    2470.0,
    3500.0,
    (SELECT id FROM manufacturer WHERE code = 'SUK'),
    (SELECT id FROM generation WHERE generation = 5),
    (SELECT id FROM type WHERE name = 'Multirôle'),
    'Actif',
    'Active',
    18500.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM tech WHERE name = 'Conception furtive')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM tech WHERE name = 'Radar N036')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM tech WHERE name = 'Système de fusion de capteurs')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM tech WHERE name = 'Système de contrôle de vol numérique')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM tech WHERE name = 'Moteurs à poussée vectorielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM armement WHERE name = 'GSh-30-1')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM armement WHERE name = 'R-73')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM armement WHERE name = 'R-77')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM armement WHERE name = 'Kh-59')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM armement WHERE name = 'KAB-500L'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM missions WHERE name = 'Supériorité aérienne')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'Su-57'), (SELECT id FROM missions WHERE name = 'Interception'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 20.1, wingspan = 14.1, height = 4.74, wing_area = 78.8,
  empty_weight = 18500, mtow = 35000, service_ceiling = 20000, climb_rate = 330,
  combat_radius = 1500, crew = 1, g_limit_pos = 9.0,
  engine_name = 'Saturn AL-41F1 (izdeliye 117)', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion et poussée vectorielle', engine_type_en = 'Thrust-vectoring afterburning turbofan',
  thrust_dry = 88.3, thrust_wet = 147.2,
  production_start = 2014, production_end = NULL, units_built = 22,
  operators_count = 1,
  stealth_level = 'moderee',
  nickname = 'Felon',
  rival_id = (SELECT id FROM airplanes WHERE name = 'F-22 Raptor' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Soukho%C3%AF_Su-57',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Sukhoi_Su-57'
WHERE name = 'Su-57';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 50000000, unit_cost_year = 2020,
  manufacturer_page = 'https://www.sukhoi.org/eng/',
  variants    = E'- **Su-57** : version de série initiale\n- **Su-57M** : modernisation prévue (moteur Izdeliye 30)\n- **Su-75 Checkmate** : monomoteur dérivé (prototype)',
  variants_en = E'- **Su-57** : initial production version\n- **Su-57M** : planned upgrade (Izdeliye 30 engine)\n- **Su-75 Checkmate** : single-engine derivative (prototype)'
WHERE name = 'Su-57';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nProgramme **PAK FA** (T-50) lancé en 2002 pour doter la Russie de son premier chasseur de 5e génération, réponse au F-22 Raptor et au F-35 américains. Premier vol en 2010, mise en service très lente.\n\n## Carrière opérationnelle\nEngagement limité en Syrie (2018) et en Ukraine (2022+). Plusieurs pertes au sol revendiquées par l''Ukraine. Utilisation très prudente par l''aviation russe pour préserver les rares exemplaires produits.\n\n## Héritage\nProduction extrêmement limitée (~22 ex. en 2024) à cause des sanctions et des difficultés techniques. Exporté en Algérie (commande). Rival officiel du F-22 et du J-20 chinois, mais en retard technologique réel.',
  description_en = E'## Genesis\nThe **PAK FA** (T-50) programme launched in 2002 to give Russia its first fifth-generation fighter, an answer to the US F-22 Raptor and F-35. First flew in 2010, very slow entry into service.\n\n## Operational career\nLimited use in Syria (2018) and Ukraine (2022+). Several ground losses claimed by Ukraine. Very cautious use by the Russian air force to preserve the few airframes produced.\n\n## Legacy\nExtremely limited production (~22 built by 2024) due to sanctions and technical difficulties. Exported to Algeria (order). Official rival of the F-22 and Chinese J-20, but with a real technological lag.'
WHERE name = 'Su-57';

-- [auto:010] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = NULL WHERE name = 'Su-57';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=Gsg-4Uk8Bzg'
WHERE name = 'Su-57';
