-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Super Étendard',
    'Super Étendard',
    'Dassault Super Étendard',
    'Dassault Super Étendard',
    'Chasseur naval français de 3e génération',
    'French 3rd-generation naval fighter',
    '/assets/airplanes/super-etendard.jpg',
    'Le Dassault Super Étendard est un avion de chasse embarqué développé par Dassault Aviation pour la Marine nationale française. Évolution de l''Étendard IV, il est classé dans la 3e génération et a été conçu principalement pour des missions antinavires et d''attaque au sol. Équipé pour opérer depuis des porte-avions, il est célèbre pour son rôle dans l''utilisation du missile Exocet.',
    'The Dassault Super Étendard is a carrier-based fighter aircraft developed by Dassault Aviation for the French Navy. Evolution of the Étendard IV, it is classified as 3rd generation and was designed primarily for anti-ship and ground attack missions. Equipped to operate from aircraft carriers, it is famous for its role in the use of the Exocet missile.',
    (SELECT id FROM countries WHERE code = 'FRA'),
    '1970-01-01',
    '1974-10-28',
    '1978-06-27',
    1180.0,
    1820.0,
    (SELECT id FROM manufacturer WHERE code = 'DAS'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Appui aérien'),
    'Retiré',
    NULL,
    6500.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM tech WHERE name = 'Système navalisé')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM tech WHERE name = 'Liaison de données tactique')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM armement WHERE name = 'DEFA 552')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM armement WHERE name = 'AM39 Exocet')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM armement WHERE name = 'AS-30L')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM armement WHERE name = 'Bombe lisse 400 kg'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM wars WHERE name = 'Guerre des Malouines')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM wars WHERE name = 'Guerre du Liban')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM wars WHERE name = 'Guerre du Golfe'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM missions WHERE name = 'Attaque antinavire')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM missions WHERE name = 'Appui aérien rapproché')),
((SELECT id FROM airplanes WHERE name = 'Super Étendard'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 14.31, wingspan = 9.60, height = 3.86, wing_area = 28.4,
  empty_weight = 6500, mtow = 12000, service_ceiling = 13700, climb_rate = 100,
  combat_radius = 650, crew = 1, g_limit_pos = 6.5,
  engine_name = 'SNECMA Atar 8K-50', engine_count = 1,
  engine_type = 'Turboréacteur', engine_type_en = 'Turbojet',
  thrust_dry = 49.0,
  production_start = 1976, production_end = 1983, units_built = 85,
  predecessor_id = (SELECT id FROM airplanes WHERE name = 'Étendard IV' LIMIT 1),
  successor_id = (SELECT id FROM airplanes WHERE name = 'Rafale' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Dassault_Super_%C3%89tendard',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Dassault-Breguet_Super_%C3%89tendard'
WHERE name = 'Super Étendard';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 15000000, unit_cost_year = 1983,
  operators_count = 2,
  manufacturer_page = 'https://www.dassault-aviation.com/fr/',
  variants    = E'- **Super Étendard Modernisé (SEM)** : upgrade radar Anémone, nav centralisée\n- Standard **SEM Rover** : compatibilité nouvelles liaisons de données',
  variants_en = E'- **Super Étendard Modernisé (SEM)** : Anémone radar upgrade, centralised navigation\n- **SEM Rover** : new data links compatibility'
WHERE name = 'Super Étendard';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nÉvolution profonde de l''Étendard IV développée dans les années 1970 pour doter la Marine nationale d''une capacité d''**attaque nucléaire tactique** depuis porte-avions (missile ASMP, tête nucléaire TN-81).\n\n## Carrière opérationnelle\nCélèbre pour avoir coulé le destroyer britannique **HMS Sheffield** en 1982 durant la guerre des Malouines, avec un missile **Exocet** tiré par l''aviation argentine. Engagements français : Kosovo, Afghanistan, Libye, Mali, Irak (opération Chammal 2015).\n\n## Héritage\nRetiré en 2016 après 38 ans de service, remplacé par le Rafale Marine. Dernier chasseur français mono-réacteur en service.',
  description_en = E'## Genesis\nDeep evolution of the Étendard IV developed in the 1970s to give the French Navy a **tactical nuclear strike** capability from carriers (ASMP missile, TN-81 warhead).\n\n## Operational career\nFamous for sinking British destroyer **HMS Sheffield** in 1982 during the Falklands War with an Argentine-launched **Exocet** missile. French engagements: Kosovo, Afghanistan, Libya, Mali, Iraq (Operation Chammal 2015).\n\n## Legacy\nRetired in 2016 after 38 years of service, replaced by the Rafale Marine. The last single-engined French fighter in service.'
WHERE name = 'Super Étendard';

-- [auto:009] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET manufacturer_page = 'https://www.dassault-aviation.com/fr/defense/' WHERE name = 'Super Étendard';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=-AaD39SvV4A'
WHERE name = 'Super Étendard';
