-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Tu-160',
    'Tu-160',
    'Tupolev Tu-160 Blackjack',
    'Tupolev Tu-160 Blackjack',
    'Bombardier stratégique soviétique/russe de 4e génération',
    'Soviet/Russian 4th-generation strategic bomber',
    '/assets/airplanes/tu160.jpg',
    'Le Tupolev Tu-160 Blackjack est un bombardier stratégique supersonique à géométrie variable développé pour les forces aériennes soviétiques, puis russes. Classé dans la 4e génération, il est conçu pour des missions de frappe stratégique et nucléaire à longue portée, capable de transporter des missiles de croisière et des bombes. Plus grand bombardier supersonique au monde, il reste en service actif et a été modernisé pour les opérations contemporaines.',
    'The Tupolev Tu-160 Blackjack is a variable-geometry supersonic strategic bomber developed for the Soviet and later Russian air forces. Classified as 4th generation, it is designed for long-range strategic and nuclear strike missions, capable of carrying cruise missiles and bombs. The largest supersonic bomber in the world, it remains in active service and has been modernized for contemporary operations.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1975-01-01',
    '1981-12-18',
    '1987-04-30',
    2220.0,
    12300.0,
    (SELECT id FROM manufacturer WHERE code = 'TUP'),
    (SELECT id FROM generation WHERE generation = 4),
    (SELECT id FROM type WHERE name = 'Bombardier'),
    'Actif',
    'Active',
    110000.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM tech WHERE name = 'Aile à géométrie variable')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM tech WHERE name = 'Radar Obzor-K')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM tech WHERE name = 'Moteurs à turbofan')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM armement WHERE name = 'Kh-55')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM armement WHERE name = 'Kh-555')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM armement WHERE name = 'Kh-101')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM armement WHERE name = 'Kh-102'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM wars WHERE name = 'Guerre froide')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM missions WHERE name = 'Dissuasion nucléaire')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Tu-160'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 54.1, wingspan = 55.7, height = 13.1, wing_area = 360.0,
  empty_weight = 110000, mtow = 275000, service_ceiling = 16000, climb_rate = 70,
  combat_radius = 7300, crew = 4,
  engine_name = 'Kuznetsov NK-32', engine_count = 4,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 137.3, thrust_wet = 245.0,
  production_start = 1984, production_end = NULL, units_built = 36,
  operators_count = 1,
  nickname = 'Blackjack',
  rival_id = (SELECT id FROM airplanes WHERE name = 'B-1 Lancer' LIMIT 1),
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Tupolev_Tu-160',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Tupolev_Tu-160'
WHERE name = 'Tu-160';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 250000000, unit_cost_year = 2017,
  variants    = E'- **Tu-160** : version de série initiale\n- **Tu-160M/M2** : modernisation en cours (relance production 2017)',
  variants_en = E'- **Tu-160** : initial production version\n- **Tu-160M/M2** : ongoing modernisation (production restarted 2017)'
WHERE name = 'Tu-160';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nPlus grand et plus lourd bombardier supersonique jamais construit. Développé dans les années 1980 comme équivalent soviétique du B-1 américain. Surnommé le **« Cygne blanc »** (Белый лебедь) par ses équipages.\n\n## Carrière opérationnelle\nBombardier stratégique de pénétration, porteur de missiles Kh-55 puis Kh-101. Engagé en Syrie (2015+) et Ukraine (2022+). La production a été **relancée en 2017** (variante Tu-160M), une première pour un avion stratégique depuis 20 ans.\n\n## Héritage\nSeul bombardier supersonique lourd encore en service mondialement. Capacité d''emport inégalée : 40+ tonnes d''armement. Rival direct du B-1B Lancer américain. Production prévue jusqu''en 2030+.',
  description_en = E'## Genesis\nThe largest and heaviest supersonic bomber ever built. Developed in the 1980s as the Soviet equivalent of the US B-1. Nicknamed the **"White Swan"** (Белый лебедь) by its crews.\n\n## Operational career\nStrategic penetration bomber, carrying Kh-55 then Kh-101 missiles. Used in Syria (2015+) and Ukraine (2022+). Production was **restarted in 2017** (Tu-160M variant), a first for a strategic aircraft in 20 years.\n\n## Legacy\nThe only heavy supersonic bomber still in service worldwide. Unmatched payload capability: 40+ tonnes of weapons. Direct rival of the US B-1B Lancer. Production planned through 2030+.'
WHERE name = 'Tu-160';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=SR8341rxmeM'
WHERE name = 'Tu-160';
