-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Tu-22M',
    'Tu-22M',
    'Tupolev Tu-22M Backfire',
    'Tupolev Tu-22M Backfire',
    'Bombardier stratégique soviétique/russe de 3e génération',
    'Soviet/Russian 3rd-generation strategic bomber',
    '/assets/airplanes/tu22.jpg',
    'Le Tupolev Tu-22M Backfire est un bombardier stratégique à géométrie variable développé pour les forces aériennes soviétiques, puis russes. Classé dans la 3e génération, il est conçu pour des missions de frappe stratégique et antinavire à longue portée, capable de transporter des missiles de croisière et des bombes conventionnelles. Utilisé pendant la Guerre froide et dans des conflits modernes, il reste un élément clé de la flotte russe.',
    'The Tupolev Tu-22M Backfire is a variable-geometry strategic bomber developed for the Soviet and later Russian air forces. Classified as 3rd generation, it is designed for long-range strategic and anti-ship strike missions, capable of carrying cruise missiles and conventional bombs. Used during the Cold War and in modern conflicts, it remains a key element of the Russian fleet.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1964-01-01',
    '1969-08-30',
    '1972-06-01',
    2000.0,
    7000.0,
    (SELECT id FROM manufacturer WHERE code = 'TUP'),
    (SELECT id FROM generation WHERE generation = 3),
    (SELECT id FROM type WHERE name = 'Bombardier'),
    'Actif',
    'Active',
    54000.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM tech WHERE name = 'Aile à géométrie variable')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM tech WHERE name = 'Radar PN-AD')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM tech WHERE name = 'Réacteur à postcombustion')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM tech WHERE name = 'Système de navigation et d''attaque intégré'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM armement WHERE name = 'GSh-23')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM armement WHERE name = 'Kh-22')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM armement WHERE name = 'Kh-32')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM armement WHERE name = 'FAB-3000')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM armement WHERE name = 'FAB-5000'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM wars WHERE name = 'Guerre froide')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM wars WHERE name = 'Guerre d''Afghanistan')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM missions WHERE name = 'Attaque antinavire')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM missions WHERE name = 'Frappe tactique')),
((SELECT id FROM airplanes WHERE name = 'Tu-22M'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 42.46, wingspan = 34.28, height = 10.4, wing_area = 232.0,
  empty_weight = 58000, mtow = 126000, service_ceiling = 13100, climb_rate = 65,
  combat_radius = 2410, crew = 4,
  engine_name = 'Kuznetsov NK-25', engine_count = 2,
  engine_type = 'Turbofan avec postcombustion', engine_type_en = 'Afterburning turbofan',
  thrust_dry = 137.3, thrust_wet = 245.0,
  production_start = 1972, production_end = 1993, units_built = 497,
  operators_count = 1,
  nickname = 'Backfire',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Tupolev_Tu-22M',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Tupolev_Tu-22M'
WHERE name = 'Tu-22M';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 100000000, unit_cost_year = 1987,
  variants    = E'- **Tu-22M2** : version de série initiale\n- **Tu-22M3** : version majoritaire (moteurs NK-25, prise d''air simplifiée)\n- **Tu-22M3M** : modernisation actuelle (2018+)'
WHERE name = 'Tu-22M';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nBombardier stratégique supersonique soviétique à **aile à géométrie variable**, développé dans les années 1970 comme équivalent du B-1 américain. Classifié « **Backfire** » par l''OTAN.\n\n## Carrière opérationnelle\nEngagé en Afghanistan (1979-1989), Tchétchénie, Géorgie (2008), Syrie (2015+), Ukraine (2022+). Porteur principal des missiles anti-navires **Kh-22** et **Kh-32** longue portée.\n\n## Héritage\nModernisé en **Tu-22M3M** depuis 2018 (avionique numérique, missiles Kh-32). Toujours exclusivement russe. Plus de **500 exemplaires** construits.',
  description_en = E'## Genesis\nSoviet supersonic strategic bomber with **variable-sweep wings**, developed in the 1970s as the equivalent of the US B-1. NATO reporting name: **"Backfire"**.\n\n## Operational career\nUsed in Afghanistan (1979-1989), Chechnya, Georgia (2008), Syria (2015+), Ukraine (2022+). Main carrier of the long-range anti-ship **Kh-22** and **Kh-32** missiles.\n\n## Legacy\nUpgraded to **Tu-22M3M** since 2018 (digital avionics, Kh-32 missiles). Still exclusively Russian. More than **500 built**.'
WHERE name = 'Tu-22M';

-- [auto:008] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  variants_en = E'- **Tu-22M2** : initial production variant\n- **Tu-22M3** : main variant (NK-25 engines, simplified intake)\n- **Tu-22M3M** : current modernisation (2018+)'
WHERE name = 'Tu-22M';

-- [auto:012] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=MRqMhdq8BtA'
WHERE name = 'Tu-22M';
