-- Insertion dans airplanes
INSERT INTO airplanes (
    name,
    name_en,
    complete_name,
    complete_name_en,
    little_description,
    little_description_en,
    image_url,
    description,
    description_en,
    country_id,
    date_concept,
    date_first_fly,
    date_operationel,
    max_speed,
    max_range,
    id_manufacturer,
    id_generation,
    type,
    status,
    status_en,
    weight
) VALUES (
    'Tu-95',
    'Tu-95',
    'Tupolev Tu-95 Bear',
    'Tupolev Tu-95 Bear',
    'Bombardier stratégique soviétique/russe de 2e génération',
    'Soviet/Russian 2nd-generation strategic bomber',
    '/assets/airplanes/tu95.jpg',
    'Le Tupolev Tu-95 Bear est un bombardier stratégique à longue portée développé pour les forces aériennes soviétiques, puis russes. Classé dans la 2e génération, il est propulsé par quatre moteurs à turbopropulseurs et conçu pour des missions de frappe stratégique et de dissuasion nucléaire. En service depuis les années 1950, il reste opérationnel grâce à des modernisations et est célèbre pour sa portée exceptionnelle et sa longévité.',
    'The Tupolev Tu-95 Bear is a long-range strategic bomber developed for the Soviet and later Russian air forces. Classified as 2nd generation, it is powered by four turboprop engines and designed for strategic strike and nuclear deterrence missions. In service since the 1950s, it remains operational thanks to modernizations and is famous for its exceptional range and longevity.',
    (SELECT id FROM countries WHERE code = 'RUS'),
    '1950-01-01',
    '1952-11-12',
    '1956-05-01',
    925.0,
    15000.0,
    (SELECT id FROM manufacturer WHERE code = 'TUP'),
    (SELECT id FROM generation WHERE generation = 2),
    (SELECT id FROM type WHERE name = 'Bombardier'),
    'Actif',
    'Active',
    90000.0
);

-- Insertion des technologies
INSERT INTO airplane_tech (id_airplane, id_tech) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM tech WHERE name = 'Moteurs à turbopropulseurs')),
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM tech WHERE name = 'Radar Obzor-K')),
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM tech WHERE name = 'Système de navigation inertielle')),
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM tech WHERE name = 'Système de contre-mesures électroniques'));

-- Insertion des armements
INSERT INTO airplane_armement (id_airplane, id_armement) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM armement WHERE name = 'GSh-23')),
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM armement WHERE name = 'Kh-55')),
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM armement WHERE name = 'Kh-555')),
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM armement WHERE name = 'FAB-3000'));

-- Insertion des guerres
INSERT INTO airplane_wars (id_airplane, id_wars) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM wars WHERE name = 'Guerre froide')),
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM wars WHERE name = 'Guerre civile syrienne'));

-- Insertion des missions
INSERT INTO airplane_missions (id_airplane, id_mission) VALUES
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM missions WHERE name = 'Frappe stratégique')),
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM missions WHERE name = 'Dissuasion nucléaire')),
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM missions WHERE name = 'Reconnaissance stratégique')),
((SELECT id FROM airplanes WHERE name = 'Tu-95'), (SELECT id FROM missions WHERE name = 'Patrouille aérienne de combat'));

-- [auto:005] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  length = 46.2, wingspan = 50.04, height = 12.12, wing_area = 310.0,
  empty_weight = 90000, mtow = 188000, service_ceiling = 12000, climb_rate = 10,
  combat_radius = 6400, crew = 4,
  engine_name = 'Kuznetsov NK-12MV', engine_count = 4,
  engine_type = 'Turbopropulseur', engine_type_en = 'Turboprop',
  thrust_dry = 11185,
  production_start = 1952, production_end = 1994, units_built = 410,
  operators_count = 1,
  nickname = 'Bear',
  wikipedia_fr = 'https://fr.wikipedia.org/wiki/Tupolev_Tu-95',
  wikipedia_en = 'https://en.wikipedia.org/wiki/Tupolev_Tu-95'
WHERE name = 'Tu-95';

-- [auto:006] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  unit_cost_usd = 60000000, unit_cost_year = 2010,
  variants    = E'- **Tu-95MS** : bombardier stratégique porteur de missiles de croisière Kh-55\n- **Tu-95MSM** : modernisation récente (Kh-101/Kh-102)\n- **Tu-142** : patrouille maritime / ASW'
WHERE name = 'Tu-95';

-- [auto:007] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  description = E'## Genèse\nBombardier stratégique développé dans les années 1950 par Tupolev. Unique en son genre : **quatre turbopropulseurs contrarotatifs** (hélices à 8 pales) permettant une très longue autonomie intercontinentale.\n\n## Carrière opérationnelle\nMission principale : patrouille stratégique longue durée, souvent au large des côtes américaines et européennes (interceptions par F-4, F-14, F-16, F-22, Eurofighter). Engagé en Syrie (2015+) et Ukraine (2022+) comme porteur de missiles de croisière **Kh-101** et **Kh-102**.\n\n## Héritage\nLe seul bombardier stratégique à hélices encore en service dans le monde. **Plus de 70 ans de carrière** prévue (jusque vers 2040). Symbole du pouvoir aérien russe et de la dissuasion nucléaire.',
  description_en = E'## Genesis\nStrategic bomber developed in the 1950s by Tupolev. Unique design: **four contra-rotating turboprops** (8-blade propellers) giving very long intercontinental range.\n\n## Operational career\nPrimary mission: long-duration strategic patrol, often off the US and European coasts (intercepted by F-4, F-14, F-16, F-22, Eurofighter). Used in Syria (2015+) and Ukraine (2022+) as a carrier of **Kh-101** and **Kh-102** cruise missiles.\n\n## Legacy\nThe only turboprop strategic bomber still in service in the world. **More than 70 years of career** planned (through approximately 2040). Symbol of Russian air power and nuclear deterrence.'
WHERE name = 'Tu-95';

-- [auto:008] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET
  variants_en = E'- **Tu-95MS** : strategic bomber carrying Kh-55 cruise missiles\n- **Tu-95MSM** : recent modernisation (Kh-101/Kh-102)\n- **Tu-142** : maritime patrol / ASW'
WHERE name = 'Tu-95';

-- [auto:011] enrichment block — generated by sync-enrichment-to-backups.js
UPDATE airplanes SET youtube_showcase = 'https://www.youtube.com/watch?v=-8eG0vuTA0I'
WHERE name = 'Tu-95';
